Update backup/restore docs BOP-1113
Mirantis/mke-docs pull request #102
Opened 2024-10-01 17:50 UTC by tppolkow

2024-10-01 23:13 UTC, KoryKessel-Mirantis commented on content/docs/operations/backup-restore/in-cluster.md
> +You can then download or upload backups using the UI options provided.
```suggestion
## Access the MinIO Console

1. Obtain the username from your cluster:

   ```shell
   kubectl --kubeconfig <path_to_kubeconfig> get secret -n mke minio-credentials -o jsonpath='{.data.root-user}' | 
   base64 -d
   ```

2. Obtain the password from your cluster:

   ```shell
   kubectl --kubeconfig <path_to_kubeconfig> get secret -n mke minio-credentials -o jsonpath='{.data.root- 
   password}' | base64 -d
   ```

3.  Navigate to the external address for your ingress controller under `/minio/`.

     Example:
     
     `https://<external_address>/minio/`

4. Log in using the username and password. The Velero bucket displays under the Object browser, and you can download or upload backups, using the options provided by the MinIO UI.
```

2024-10-02 15:20 UTC, tppolkow commented on content/docs/operations/backup-restore/in-cluster.md
> +You can then download or upload backups using the UI options provided.
done

2024-10-02 15:20 UTC, tppolkow commented on content/docs/operations/backup-restore/_index.md
>  backup functionality should work, however, even if
done

2024-10-02 15:21 UTC, tppolkow commented
@KoryKessel-Mirantis I believe I've addressed all your comments. Please take another look.

2024-10-02 16:09 UTC, KoryKessel-Mirantis requested changes

2024-10-02 16:09 UTC, KoryKessel-Mirantis commented on content/docs/operations/backup-restore/in-cluster.md
> +```shell
Please add a space between the step and the codeblock, and also indent the codeblock so it aligns under the text following the number.

2024-10-02 16:09 UTC, KoryKessel-Mirantis commented on content/docs/operations/backup-restore/in-cluster.md
> +Example:
Please add a space between the step and "Example:", and also indent "Example:" and the URL so they aligns under the text following the number.

2024-10-02 16:09 UTC, KoryKessel-Mirantis commented on content/docs/operations/backup-restore/in-cluster.md
> +![img_2.png](img_2.png)
Please add a space after the period that follows the '4'. Also, please indent the image under the text that follows the number.

2024-10-02 16:09 UTC, KoryKessel-Mirantis commented on content/docs/operations/backup-restore/in-cluster.md
> +To access the MinIO console, first get the generated credentials from your cluster
```suggestion
To access the MinIO Console:
```

2024-10-02 16:09 UTC, KoryKessel-Mirantis commented on content/docs/operations/backup-restore/in-cluster.md
> +## Accessing the minio console
```suggestion
## Accessing the MinIO Console
```

2024-10-02 16:09 UTC, KoryKessel-Mirantis commented on content/docs/operations/backup-restore/_index.md
>  addon](https://microk8s.io/docs/addon-minio).
```suggestion
add-on](https://microk8s.io/docs/addon-minio).
```

2024-10-02 16:09 UTC, KoryKessel-Mirantis commented on content/docs/operations/backup-restore/in-cluster.md
>  provider, the [MinIO addon](https://microk8s.io/docs/addon-minio).
```suggestion
provider, the [MinIO add-on](https://microk8s.io/docs/addon-minio).
```

2024-10-02 17:29 UTC, tppolkow commented on content/docs/operations/backup-restore/in-cluster.md
> +```shell
done

2024-10-02 17:29 UTC, tppolkow commented on content/docs/operations/backup-restore/in-cluster.md
> +```shell
done

2024-10-02 17:29 UTC, tppolkow commented on content/docs/operations/backup-restore/in-cluster.md
> +Example:
done

2024-10-02 17:29 UTC, tppolkow commented on content/docs/operations/backup-restore/in-cluster.md
> +![img_2.png](img_2.png)
done

2024-10-02 17:31 UTC, tppolkow commented on content/docs/operations/backup-restore/in-cluster.md
> +To access the MinIO console, first get the generated credentials from your cluster
done

2024-10-02 17:32 UTC, tppolkow commented on content/docs/operations/backup-restore/in-cluster.md
> +## Accessing the minio console
done

2024-10-02 17:32 UTC, tppolkow commented on content/docs/operations/backup-restore/in-cluster.md
>  provider, the [MinIO addon](https://microk8s.io/docs/addon-minio).
done, I've also adjusted the link to https://min.io/ instead of microk8s.

2024-10-02 17:32 UTC, tppolkow commented on content/docs/operations/backup-restore/_index.md
>  addon](https://microk8s.io/docs/addon-minio).
done + adjusted link

2024-10-02 22:31 UTC, KoryKessel-Mirantis requested changes
For reasons unknown, there is one edit I want to request that I cannot input as a comment. In in-cluster.md, there is a codeblock where the indention is just a space off.

To list the restores, run:
```shell
 mkectl restore list
 ```
Please add a line between the text and the codeblock, and move the last two lines of the codeblock a single space to the left:

To list the restores, run:
```shell
mkectl restore list
```

2024-10-02 22:31 UTC, KoryKessel-Mirantis commented on content/docs/operations/backup-restore/in-cluster.md
>  applied a blueprint with the default MKE backup configuration.
```suggestion
{{< callout type="info" >}}
  The offered instructions assume that you have created a cluster and
applied a blueprint with the default MKE backup configuration.
{{< /callout >}}
```

2024-10-02 22:55 UTC, KoryKessel-Mirantis approved these changes

2024-10-02 22:56 UTC, merged