Update authentication
Mirantis/mke-docs pull request #103
Opened 2024-10-01 17:55 UTC by nwneisen

Read through the authentication docs after not looking at them for a while. These are the changes that I saw that should be made

2024-10-03 14:43 UTC, KoryKessel-Mirantis requested changes

2024-10-03 14:43 UTC, KoryKessel-Mirantis commented on content/docs/operations/authentication/_index.md
> +and handles the complexity of the various protocols.
```suggestion
MKE uses [Dex](https://dexidp.io/) for authentication. Dex serves as a proxy
between your MKE cluster and your authentication providers, combining the
configuration of multiple authentication providers into a single configuration
while also handling the complexity of the various protocols.
```

2024-10-03 14:43 UTC, KoryKessel-Mirantis commented on content/docs/operations/authentication/_index.md
> +  of using Okta as an authentication provider for either protocol.
```suggestion
- **Identity Provider (IdP):** To use OIDC or SAML, you must configure an identity provider. For examples of how to use Okta as an authentication service provider for either of these protocols, refer to [OIDC](../../operations/authentication/oidc-providers/oidc) or [SAML](../../operations/authentication/saml-providers/saml).
```

2024-10-03 14:43 UTC, KoryKessel-Mirantis commented on content/docs/operations/authentication/_index.md
> +  example server on your local machine can be found at [LDAP](../../operations/authentication/ldap).
```suggestion
- **LDAP Server:** To use LDAP, you must have an LDAP server configured. An
  example server on your local machine is available at [LDAP](../../operations/authentication/ldap).
```

2024-10-03 14:43 UTC, KoryKessel-Mirantis commented on content/docs/operations/authentication/_index.md
> +time unit (e.g. `1h` for one hour).
```suggestion
You can use the `expiry` section of the configuration file to set the expiration time for refresh and id tokens, in the format of number + time unit format. For example, `1h` to designate one hour.
```

2024-10-03 14:43 UTC, KoryKessel-Mirantis commented on content/docs/operations/authentication/_index.md
> +
Need a short lead in sentence for the table. Something like, "The `expiry` configuration fields are defined in the following table:" Not sure of the correct word, but I am sure you are...maybe 'parameters', or 'options'?

2024-10-03 15:00 UTC, nwneisen commented on content/docs/operations/authentication/LDAP.md
> +5. Enter your credentials and click **Sign In**. If authentication is successful,
This step is the only one that actually has the user enter credentials. 

Step 2 is literally a button that says "Click here to login" and directs the user to a set of buttons that let the user select with type of authentication to login with and then directs them to a page with the username and password fields

2024-10-03 15:09 UTC, nwneisen commented on content/docs/operations/authentication/OIDC.md
> +   login page.
`Redirect` or `direct` should be used here over `call`

```suggestion
3. Select **Log in with OIDC** to redirect to the login page for your OIDC service provider.
```

2024-10-03 15:09 UTC, nwneisen commented on content/docs/operations/authentication/SAML.md
> +   login page.
```suggestion
3. Select **Log in with OIDC** to redirect to the login page for your OIDC service provider.
```

2024-10-03 15:09 UTC, nwneisen commented on content/docs/operations/authentication/_index.md
> +  example server on your local machine can be found at [LDAP](../../operations/authentication/ldap).
```suggestion
- **LDAP Server:** To use LDAP, you must have an LDAP server configured. An example of setting up an OpenLDAP server can be found at [LDAP](../../operations/authentication/ldap).
```

2024-10-03 16:19 UTC, KoryKessel-Mirantis commented on content/docs/operations/authentication/_index.md
> +  example server on your local machine can be found at [LDAP](../../operations/authentication/ldap).
Howzabout:

**LDAP Server:** To use LDAP, you must have an LDAP server configured. A setup example for an OpenLDAP server is available at [LDAP](../../operations/authentication/ldap).

2024-10-03 22:24 UTC, KoryKessel-Mirantis requested changes

2024-10-03 22:24 UTC, KoryKessel-Mirantis commented on content/docs/operations/authentication/LDAP.md
>  The MKE configuration file `authentication.ldap` fields are detailed below:
The paragraph above the info directive suffices as the table lead-in. Let's get ride of this line.

2024-10-03 22:24 UTC, KoryKessel-Mirantis commented on content/docs/tutorials/authentication-provider-setup/using-okta-as-a-saml-provider.md
> +This example demonstrates how to set up Okta as a SAML provider for MKE 4. For the full list of SAML configurations, see the [SAML](../../../../docs/operations/authentication/saml) documentation.
Can this sentence be transformed to echo the same lead-in sentence for the OIDC tutorial?

"To configure an Okta application to serve as your [SAML authentication (../../../../docs/operations/authentication/saml) provider for MKE 4:"

If that works, let's drop the second sentence.

2024-10-03 22:24 UTC, KoryKessel-Mirantis commented on content/docs/tutorials/authentication-provider-setup/using-okta-as-a-saml-provider.md
> +## Set up a SAML application in Okta
Please delete this heading as it is nothing more than an echo of the topic heading.

2024-10-03 22:24 UTC, KoryKessel-Mirantis commented on content/docs/tutorials/authentication-provider-setup/using-okta-as-a-saml-provider.md
> +Navigate to (Okta)[https://www.okta.com/] and sign in to your accounts dashboard.
Please make this line step 1 and +1 the steps that follow accordingly.

2024-10-03 22:24 UTC, KoryKessel-Mirantis commented on content/docs/tutorials/authentication-provider-setup/using-okta-as-a-saml-provider.md
> +title: Using Okta as a SAML provider
```suggestion
title: Setting up Okta as a SAML provider
```

2024-10-03 22:24 UTC, KoryKessel-Mirantis commented on content/docs/tutorials/authentication-provider-setup/using-okta-as-a-saml-provider.md
> +title: Using Okta as a SAML provider
Thinking the filename should change to reflect the suggested edit to the topic title, too.

2024-10-03 22:24 UTC, KoryKessel-Mirantis commented on content/docs/tutorials/authentication-provider-setup/using-okta-as-an-oidc-provider.md
> +title: Using Okta as an OIDC provider
```suggestion
title: Setting up Okta as an OIDC provider
```

2024-10-03 22:24 UTC, KoryKessel-Mirantis commented on content/docs/tutorials/authentication-provider-setup/using-okta-as-an-oidc-provider.md
> +title: Using Okta as an OIDC provider
Thinking the filename should change to reflect the suggested edit to the topic title, too.

2024-10-04 22:45 UTC, KoryKessel-Mirantis requested changes

2024-10-04 22:45 UTC, KoryKessel-Mirantis commented on content/docs/operations/authentication/_index.md
> +Authentication is is always enabled, however, the settings for each of the
```suggestion
Authentication is always enabled, however, the settings for each of the
```

2024-10-04 22:45 UTC, KoryKessel-Mirantis commented on content/docs/operations/authentication/_index.md
> +| `expiry.refreshTokens.reuseInterval`     | Interval to allow getting the same refresh token from the refresh endpoint |
So as not to screw up the table formatting, I am foregoing the Suggestion tool. I have a few asks, though:

1. Please put a period at the end of each description.
2. Please remove the 'The' from the first six descriptions and capitalize the word that follows.
3. Please change 'it's' on line 67 to 'it is'.
4. Should "every-request" be in code/command font?
5. Please change "Interval to allow getting" to "Interval for obtaining".

2024-10-04 22:45 UTC, KoryKessel-Mirantis commented on content/docs/tutorials/authentication-provider-setup/setting-up-okta-as-a-saml-provider.md
> +1. Navigate to (Okta)[https://www.okta.com/] and sign in to your accounts dashboard.
Should "accounts dashboard" be "**Accounts** dashboard"?

2024-10-04 22:45 UTC, KoryKessel-Mirantis commented on content/docs/tutorials/authentication-provider-setup/setting-up-okta-as-a-saml-provider.md
> +3. For **App name**, choose a name that you can easily remember.
```suggestion
3. Enter an **App name** that is easy to remember.
```

2024-10-04 22:45 UTC, KoryKessel-Mirantis commented on content/docs/tutorials/authentication-provider-setup/setting-up-okta-as-a-saml-provider.md
> +   The `ssoURL` is the MetadataURL with the final metadata removed from the path.
```suggestion
8. Click **Assign** -> **Assign to people**.
9. Click the blue **Assign** button that corresponds to the account you want to use for authentication.

    - Okta generates the `ssoURL` and certificate under the **Sign On** tab.
    - The **ssoURL** is the MetadataURL with the final metadata removed from the path.
```

2024-10-04 22:45 UTC, KoryKessel-Mirantis commented on content/docs/tutorials/authentication-provider-setup/setting-up-okta-as-a-saml-provider.md
> +8. Download the certificate to the system from which you will run mkectl:
```suggestion
10. Download the certificate to the system from which you will run `mkectl`:
```

2024-10-04 22:45 UTC, KoryKessel-Mirantis commented on content/docs/tutorials/authentication-provider-setup/setting-up-okta-as-a-saml-provider.md
> +9. Run the `mkectl apply` command with your MKE configuration file.
```suggestion
11. Run the `mkectl apply` command using your MKE configuration file.
```

2024-10-04 22:45 UTC, KoryKessel-Mirantis commented on content/docs/tutorials/authentication-provider-setup/setting-up-okta-as-an-oidc-provider.md
> +2. Select **Log in with SAML**. This will redirect you to Okta's
```suggestion
2. Select **Log in with SAML**. This will redirect you to the Okta
```

2024-10-04 22:45 UTC, KoryKessel-Mirantis commented on content/docs/tutorials/authentication-provider-setup/setting-up-okta-as-a-saml-provider.md
> +2. Select **Log in with OIDC**. This will redirect you to Okta's
```suggestion
2. Select **Log in with OIDC**. This will redirect you to the Okta
```

2024-10-07 14:56 UTC, nwneisen commented on content/docs/tutorials/authentication-provider-setup/setting-up-okta-as-a-saml-provider.md
> +1. Navigate to (Okta)[https://www.okta.com/] and sign in to your accounts dashboard.
It should be "your account's dashboard"

2024-10-07 22:46 UTC, KoryKessel-Mirantis commented on content/docs/tutorials/authentication-provider-setup/setting-up-okta-as-a-saml-provider.md
> +1. Navigate to (Okta)[https://www.okta.com/] and sign in to your accounts dashboard.
Yeah, but no. We strive to eliminate anthropomorphization, meaning in this case that the account is unable to _own_ the dashboard...or anything for that matter. :-)

2024-10-08 15:16 UTC, KoryKessel-Mirantis approved these changes

2024-10-08 15:17 UTC, merged