Add ldap server example
Mirantis/mke-docs pull request #105
Opened 2024-10-01 18:36 UTC by nwneisen

#91 

Adds an example of setting up an LDAP server

2024-10-02 19:22 UTC, nwneisen commented on content/docs/tutorials/authentication-provider-setup/ldap-provider-setup.md
> +This example shows how to create an LDAP server for testing LDAP authentication with MKE 4. For the full list of LDAP configurations, see the [LDAP](../../../../docs/operations/authentication/ldap) d
```suggestion
To create a local LDAP server to test [LDAP authentication](../../../../docs/operations/authentication/ldap) with MKE4
```

2024-10-02 19:27 UTC, nwneisen commented on content/docs/tutorials/authentication-provider-setup/ldap-provider-setup.md
> +
I could see procedures being done under these headers but I think removing them will make for a very long run-on checklist that doesn't break apart the different actions that are being done. These headers also create sublinks that are extremely useful when referring to docs.

We can do it if you want but from a readers perspective they help to break the steps apart in to larger sections and users will be able to tell what part they need to replace for the setup they want to use. i.e. if I was setting up a production LDAP server, I would replace this **Running and LDAP server for testing ** section and the rest of this would be the same process.

2024-10-03 16:23 UTC, KoryKessel-Mirantis commented on content/docs/tutorials/authentication-provider-setup/ldap-provider-setup.md
> +This example shows how to create an LDAP server for testing LDAP authentication with MKE 4. For the full list of LDAP configurations, see the [LDAP](../../../../docs/operations/authentication/ldap) d
Can I have my colon back? :-)

2024-10-03 17:20 UTC, nwneisen commented on content/docs/tutorials/authentication-provider-setup/ldap-provider-setup.md
> +```
My linter keeps moving the code back which tells me this is a standard me nono. I can put it in but if anyone edits it then their linter might try to move it.

2024-10-04 23:26 UTC, KoryKessel-Mirantis requested changes

2024-10-04 23:26 UTC, KoryKessel-Mirantis commented on content/docs/tutorials/authentication-provider-setup/setting-up-openldap-as-an-ldap-provider.md
> +> **Note** Running the development server requires [Docker and docker compose](https://docs.docker.com/engine/install/) to be installed on your machine. Docker compose is now part of docker
Edit note to:

{{< callout type="info" >}}
To run the development server you must have [Docker and docker compose](https://docs.docker.com/engine/install/) installed on your system.
{{< /callout >}}

2024-10-04 23:26 UTC, KoryKessel-Mirantis commented on content/docs/tutorials/authentication-provider-setup/setting-up-openldap-as-an-ldap-provider.md
> +## Set up an LDAP server
The title of the topic is sufficient as a lead-in. Let's drop this heading.

2024-10-04 23:26 UTC, KoryKessel-Mirantis commented on content/docs/tutorials/authentication-provider-setup/setting-up-openldap-as-an-ldap-provider.md
> +   Create a file called `config-ldap.ldif` with the following content:
```suggestion
1. Create a file called `config-ldap.ldif` with the following content:
```

2024-10-04 23:26 UTC, KoryKessel-Mirantis commented on content/docs/tutorials/authentication-provider-setup/setting-up-openldap-as-an-ldap-provider.md
> +   The config-ldap.ldif file will be loaded into the Docker container for the LDAP server, from where the server will run the file to create a number of default users.
```suggestion
   The `config-ldap.ldif file` will be loaded into the Docker container for the LDAP server, from where the server will run the file to create a number of default users.
```

2024-10-04 23:26 UTC, KoryKessel-Mirantis commented on content/docs/tutorials/authentication-provider-setup/setting-up-openldap-as-an-ldap-provider.md
> +   Create a file called `docker-compose.yml` with the following content:
```suggestion
2. Create a docker compose file called `docker-compose.yml`, containing the following content:
```

2024-10-04 23:26 UTC, KoryKessel-Mirantis commented on content/docs/tutorials/authentication-provider-setup/setting-up-openldap-as-an-ldap-provider.md
> +   The server can now be started with the command
```suggestion
3. Start the server:
```

2024-10-04 23:26 UTC, KoryKessel-Mirantis commented on content/docs/tutorials/authentication-provider-setup/setting-up-openldap-as-an-ldap-provider.md
> +   This docker compose file will copy in the `config-ldap.ldif` configuration file and use it when setting up the LDAP server. The server will expose the LDAP service on port 389 for non-tls and 636
```suggestion
   The Docker Compose file copies in the `config-ldap.ldif` configuration file and uses it in setting up the LDAP server, which exposes the LDAP service on port `389` for non-TLS and on `636` for TLS.
```

2024-10-04 23:26 UTC, KoryKessel-Mirantis commented on content/docs/tutorials/authentication-provider-setup/setting-up-openldap-as-an-ldap-provider.md
> +An example MKE4 configuration for LDAP is shown below. This configuration is for the example LDAP server.
```suggestion
An example configuration for LDAP is shown below, for the exemplified LDAP server:
```

2024-10-04 23:26 UTC, KoryKessel-Mirantis commented on content/docs/tutorials/authentication-provider-setup/setting-up-openldap-as-an-ldap-provider.md
> +Run the `mkectl apply` command with the configuration file to apply the configuration to MKE.
```suggestion
Run the `mkectl apply` command using the configuration file to apply the configuration to MKE.
```

2024-10-07 14:45 UTC, nwneisen commented on content/docs/tutorials/authentication-provider-setup/setting-up-openldap-as-an-ldap-provider.md
> +> **Note** Running the development server requires [Docker and docker compose](https://docs.docker.com/engine/install/) to be installed on your machine. Docker compose is now part of docker
Changed but I used `OpenLDAP server` instead of development server.

2024-10-08 16:48 UTC, KoryKessel-Mirantis requested changes

2024-10-08 16:48 UTC, KoryKessel-Mirantis commented on content/docs/tutorials/authentication-provider-setup/setting-up-openldap-as-an-ldap-provider.md
> +> **Note** To the the OpenLDAP server you must have [Docker and docker compose](https://docs.docker.com/engine/install/) installed on your system.
```suggestion
>{{< callout type="info" >}}
  To run the OpenLDAP server you must have [Docker and docker compose](https://docs.docker.com/engine/install/) installed on your system.
{{< /callout >}}
```

2024-10-08 16:48 UTC, KoryKessel-Mirantis commented on content/docs/tutorials/authentication-provider-setup/setting-up-openldap-as-an-ldap-provider.md
> +2. Create the docker compose file called `docker-compose.yml`, containing the following content:
```suggestion
2. Create a Docker Compose file named `docker-compose.yml` that contains the following content:
```

2024-10-08 16:48 UTC, KoryKessel-Mirantis commented on content/docs/tutorials/authentication-provider-setup/setting-up-openldap-as-an-ldap-provider.md
> +   The Docker Compose file copies in the `config-ldap.ldif` configuration file and uses it in setting up the LDAP server which exposes the LDAP service on port `389` for non-TLS and `636` for TLS.
```suggestion
   The Docker Compose file copies in the `config-ldap.ldif` configuration file and uses it to set up the LDAP server, which exposes the LDAP service on port `389` for non-TLS and `636` for TLS.
```

2024-10-08 16:48 UTC, KoryKessel-Mirantis commented on content/docs/tutorials/authentication-provider-setup/setting-up-openldap-as-an-ldap-provider.md
> +2. Select **Log in with LDAP**. This will redirect you to the LDAP login page.
```suggestion
2. Select **Log in with LDAP** to access the LDAP login page.
```

2024-10-08 16:48 UTC, KoryKessel-Mirantis commented on content/docs/tutorials/k0s-in-aws/terraform-scenario.md
> +   setting `apiServer.externalAddress` to the output of the `terraform output -raw lb_dns_name` command.
```suggestion
   If the `yq` tool is not installed, edit the `mke4.yaml` file to set `apiServer.externalAddress` as the output of the `terraform output -raw lb_dns_name` command.
```

2024-10-08 16:54 UTC, nwneisen commented on content/docs/tutorials/k0s-in-aws/terraform-scenario.md
> +   setting `apiServer.externalAddress` to the output of the `terraform output -raw lb_dns_name` command.
This looks like some kind of rebase error. I'm going to leave this change out since it doesn't relate to my PR and I will remove this change from my commit

2024-10-08 17:02 UTC, KoryKessel-Mirantis requested changes

2024-10-08 18:34 UTC, KoryKessel-Mirantis approved these changes

2024-10-08 18:38 UTC, merged