[BOP-1035][BOP-1065] add docs for metallb and nfd
Mirantis/mke-docs pull request #106
Opened 2024-10-01 19:52 UTC by sakshisharma84

2024-10-15 20:24 UTC, quadespresso requested changes

2024-10-15 20:24 UTC, quadespresso commented on content/docs/operations/metallb/_index.md
> +```
1. Shouldn't the YAML doc also begin with `---`?
2. Overall formatting appears to be incorrect.

Suggested revision:

```yaml
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.240-192.168.1.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: example
  namespace: metallb-system
```

2024-10-15 20:24 UTC, quadespresso commented on content/docs/operations/metallb/_index.md
> +```yaml
Looks like this should be `toml` and not `yaml`.

2024-10-17 14:45 UTC, sakshisharma84 commented on content/docs/operations/metallb/_index.md
> +```
@quadespresso 

> Shouldn't the YAML doc also begin with ---?
Not necessarily. It works even w/o it. And if it looks better in the docs, I can definitely add it.

2024-10-17 14:47 UTC, sakshisharma84 commented on content/docs/operations/metallb/_index.md
> +```
done!

2024-10-17 14:47 UTC, sakshisharma84 commented on content/docs/operations/metallb/_index.md
> +```yaml
done!

2024-10-22 02:12 UTC, quadespresso requested changes

2024-10-22 02:12 UTC, quadespresso commented on content/docs/operations/metallb/_index.md
> +| [[cluster_config.metallb_config.metallb_ip_addr_pool]]         | `Deprecated`                            |
Apologies for the nits being picked here, but I'm wondering whether each of the table values should be formatted as code...?

eg,
```
| MKE-3                                                          | MKE-4                                   |
|----------------------------------------------------------------|-----------------------------------------|
| `[cluster_config.metallb_config.enabled]`                      | `addons.metallb.enabled`                  |
| `[[cluster_config.metallb_config.metallb_ip_addr_pool]]`       | `Deprecated`  
```

Also, could I get clarification where `addons.metallb.enabled` is located in the output of `mkectl init`?

If from this block:
```yaml
spec:
  addons:
    - chart:
        name: metallb
        repo: https://metallb.github.io/metallb
        values: |
          controller:
            tolerations:
              - key: node-role.kubernetes.io/master
                operator: Exists
                effect: NoSchedule
          speaker:
            frr:
              enabled: false
        version: 0.14.7
      dryRun: false
      enabled: false
      kind: chart
      name: metallb
      namespace: metallb-system
```

then wouldn't the JSONpath be `addons[0].enabled` or more precisely `.spec.addons[0].enabled`?

I had a quick go with a few alternatives; nothing seemed to align with `addons.metallb.enabled`:

```bash
❯ mkectl init | yq 'addons'
Error: 1:1: invalid input text "addons"

❯ mkectl init | yq '.addons'
null

❯ mkectl init | yq '.spec.addons'
- chart:
    name: metallb
    repo: https://metallb.github.io/metallb
    values: |
      controller:
          tolerations:
              - key: node-role.kubernetes.io/master
                operator: Exists
                effect: NoSchedule
      speaker:
          frr:
              enabled: false
    version: 0.14.7
  dryRun: false
  enabled: false
  kind: chart
  name: metallb
  namespace: metallb-system

❯ mkectl init | yq '.spec.addons.metal'
Error: cannot index array with 'metal' (strconv.ParseInt: parsing "metal": invalid syntax)

❯ mkectl init | yq '.spec.addons[0].chart.name'
metallb

❯ mkectl init | yq '.spec.addons[0].enabled'
false
```

2024-10-22 02:12 UTC, quadespresso commented on content/docs/operations/metallb/_index.md
> +| chart.values.speaker.frr.enabled      | Indicates whether FRR is enabled for metallb speaker      | false                                                                                     |
I think columns 1 and 3 should have their values formatted as code. All rows, except for the one item I called out elsewhere as needing a `yaml` code fence.

2024-10-22 18:08 UTC, quadespresso submitted a review, later dismissed
Missed this one last night.

2024-10-22 18:08 UTC, quadespresso commented on content/docs/operations/metallb/_index.md
> +| chart.values.controller.tolerations   | Indicates the tolerations for the metallb controller pod  | - key: node-role.kubernetes.io/master<br><br/>operator: Exists <br><br/>effect: NoSchedule|
For just this row, the third column should probably be reformatted as `yaml` code fence, ie,

    ```yaml
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
    ```

2024-10-23 09:02 UTC, KoryKessel-Mirantis requested changes
First Docs review round for MetalLB content. NFD to follow.

2024-10-25 20:31 UTC, ry4nz commented
@quadespresso @KoryKessel-Mirantis Please review again.

2024-10-28 13:47 UTC, ry4nz commented
@KoryKessel-Mirantis Let's merge as is then you may work on the formatting later?

2024-10-28 19:19 UTC, KoryKessel-Mirantis approved these changes

2024-10-28 23:10 UTC, merged

2024-10-28 23:44 UTC, KoryKessel-Mirantis commented on content/docs/operations/metallb/_index.md
> +| chart.values.speaker.frr.enabled      | Indicates whether FRR is enabled for metallb speaker      | false                                                                                     |
@quadespresso, for the second-to-last column 3, I am going to need guidance...guessing this is the so-called "yaml code fende"?