Add docs for cloud provider
Mirantis/mke-docs pull request #107
Opened 2024-10-01 20:21 UTC by tppolkow

2024-10-04 15:04 UTC, KoryKessel-Mirantis requested changes

2024-10-07 19:14 UTC, tppolkow commented on content/docs/operations/cloudprovider/cloudprovider.md
> +To use other cloud providers, you must set MKE to run with "external" cloud provider and install the cloud provider yourself.
done

2024-10-07 19:14 UTC, tppolkow commented on content/docs/operations/cloudprovider/cloudprovider.md
> +Cloud Providers may have additional requirements. Please refer to the specific cloud provider documentation for more information.
done

2024-10-07 19:17 UTC, tppolkow commented on content/docs/operations/cloudprovider/cloudprovider.md
> +Enabling CloudProvider allows your MKE cluster to integrate with cloud provider addons. Currently, only AWS is supported as an MKE managed cloud provider addon.
@KoryKessel-Mirantis The first sentence you added doesn't make sense here, I believe you are defining the low level[ Kubernetes cloud provider](https://github.com/kubernetes/cloud-provider), but this is an interface designed to be used by developers developing their own cloud provider addons ( hence the `shared interfaces that are implemented by Kubernetes cloud service providers` ). It doesn't really make sense here as here they are enabling the "implemented interface" i.e the AWS cloud provider (which implements the generic Kubernetes defined interface)

2024-10-07 19:17 UTC, tppolkow commented on content/docs/operations/cloudprovider/cloudprovider.md
> +## Pre-requisites
done

2024-10-10 22:57 UTC, KoryKessel-Mirantis commented on content/docs/operations/cloudprovider/cloudprovider.md
> +Enabling CloudProvider allows your MKE cluster to integrate with cloud provider addons. Currently, only AWS is supported as an MKE managed cloud provider addon.
Workshopped the paragraph to goodness in Slack and tapped the agreed-to edit into my suggested change.

2024-10-16 15:54 UTC, KoryKessel-Mirantis requested changes

2024-10-16 15:54 UTC, KoryKessel-Mirantis commented on content/docs/operations/cloudprovider/cloudprovider.md
> +CloudProvider support is disabled by default. To enable CloudProvider support, configure
Still pending?

2024-10-16 15:54 UTC, KoryKessel-Mirantis commented on content/docs/operations/cloudprovider/cloudprovider.md
> +**Configuration parameters**
Still pending?

2024-10-16 15:54 UTC, KoryKessel-Mirantis commented on content/docs/operations/cloudprovider/cloudprovider.md
> +title: CloudProvider
Still pending?

2024-10-16 15:54 UTC, KoryKessel-Mirantis commented on content/docs/operations/cloudprovider/cloudprovider.md
> +For using the MKE managed AWS Cloud Provider you will need to ensure your nodes have certain IAM policies. See the official AWS cloud provider [documentation](https://cloud-provider-aws.sigs.k8s.io/p
Still pending?

2024-10-16 15:54 UTC, KoryKessel-Mirantis commented on content/docs/operations/cloudprovider/cloudprovider.md
> +## Example: Create an NLB with Cloud Provider AWS
Still pending?

2024-10-16 16:12 UTC, KoryKessel-Mirantis requested changes

2024-10-16 16:12 UTC, KoryKessel-Mirantis commented on content/docs/operations/cloudprovider/cloudprovider.md
> +AWS is currently the only managed cloud service provider add-on supported by MKE 4. To use a different cloud service provider, you must set MKE 4 to run with "external" cloud provider and install the
```suggestion
AWS is currently the only managed cloud service provider add-on supported by MKE 4. To use a different cloud service provider, before installing that provider you must change the `provider` parameter under `cloudProvider` in the MKE configuration file to `external`:

```yaml
  cloudProvider:
    enabled: true
    provider: aws
```
```

change the `enabled` parameter under `cloudProvider` in the MKE configuration file to `true`:

2024-10-16 16:20 UTC, tppolkow commented on content/docs/operations/cloudprovider/cloudprovider.md
> +## Example: Create an NLB with Cloud Provider AWS
@KoryKessel-Mirantis Cloud Provider has many uses that are up to the user. This example is just one way users could use cloud provider. I feel your edit could make users think this is an integral part of cloud provider set up, which it is not.

2024-10-16 21:05 UTC, tppolkow commented on content/docs/operations/cloudprovider/cloudprovider.md
> +## Example: Create an NLB with Cloud Provider AWS
commiting this given the first line of the section says its an example.

2024-10-16 21:42 UTC, KoryKessel-Mirantis requested changes

2024-10-16 21:42 UTC, KoryKessel-Mirantis commented on content/docs/operations/cloudprovider/cloudprovider.md
> +```
```suggestion
1. Create a sample nginx deployment:

   ```shell
   cat <<EOF | kubectl --kubeconfig ~/.mke/mke.kubeconf apply -f -
   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: nginx-deployment
   spec:
     replicas: 3  
     selector:
       matchLabels:
         app: nginx
     template:
       metadata:
         labels:
           app: nginx
       spec:
         containers:
         - name: nginx-container
           image: nginx:latest
           ports:
           - containerPort: 80
   EOF
   ```
```

2024-10-16 21:42 UTC, KoryKessel-Mirantis commented on content/docs/operations/cloudprovider/cloudprovider.md
> +```
```suggestion
2. Create a service of type LoadBalancer:

   ```shell
   cat <<EOF | kubectl --kubeconfig ~/.mke/mke.kubeconf apply -f -
   apiVersion: v1
   kind: Service
   metadata:
     name: nginx-service
     annotations:
       service.beta.kubernetes.io/aws-load-balancer-type: nlb
   spec:
     selector:
       app: nginx
     ports:
       - protocol: TCP
         port: 80
         targetPort: 80
     type: LoadBalancer
   EOF
   ```
```

2024-10-16 21:42 UTC, KoryKessel-Mirantis commented on content/docs/operations/cloudprovider/cloudprovider.md
> +```
```suggestion
3. Check the status of the service:

   ```shell
   kubectl --kubeconfig ~/.mke/mke.kubeconf get service
   NAME            TYPE           CLUSTER-IP     EXTERNAL-IP                                                                        PORT(S)        AGE
   kubernetes      ClusterIP      10.96.0.1      <none>                                                                             443/TCP        14m
   nginx-service   LoadBalancer   10.96.177.89   afdf81e0681274c52acbb7b45add87a1-637d0d850105ea92.elb.ca-central-1.amazonaws.com   80:32927/TCP   63s
   ```
```

2024-10-16 21:42 UTC, KoryKessel-Mirantis commented on content/docs/operations/cloudprovider/cloudprovider.md
> +![aws-lb.png](aws-lb.png)
```suggestion
The load balancer should now be visible in AWS console.

![aws-lb.png](aws-lb.png)
```

2024-10-16 21:42 UTC, KoryKessel-Mirantis commented on content/docs/operations/cloudprovider/cloudprovider.md
> +![aws-lb-provisioned.png](aws-lb-provisioned.png)
```suggestion
Once the load balancer finishes provisioning you should be able to access nginx through the external IP.

![aws-lb-provisioned.png](aws-lb-provisioned.png)
```

2024-10-16 21:42 UTC, KoryKessel-Mirantis commented on content/docs/operations/cloudprovider/cloudprovider.md
> +Once you have enabled the cloud provider in your MKE configuration, and applied the mke configuration, you can create an NLB using the following steps:
```suggestion
An example is offered below of how to use cloud provider AWS to create a Network Load Balancer (NLB) in your MKE cluster. 

Once you have enabled the cloud provider through the MKE configuration file and have applied it, you can create an NLB as follows:
```

2024-10-16 21:42 UTC, KoryKessel-Mirantis commented on content/docs/operations/cloudprovider/cloudprovider.md
> +Refer to the documentation for your chosen cloud service provider to learn of any proprietary requirements.
```suggestion
## Prerequisites

Refer to the documentation for your chosen cloud service provider to learn of any proprietary requirements.
```

2024-10-17 06:44 UTC, MagdaDziadosz requested changes

2024-10-17 06:44 UTC, MagdaDziadosz commented on content/docs/operations/cloudprovider/cloudprovider.md
> +Once the load balancer finishes provisioning you should be able to access nginx through the external IP.
```suggestion
Once the load balancer finishes provisioning, you should be able to access nginx through the external IP.
```

2024-10-17 06:44 UTC, MagdaDziadosz commented on content/docs/operations/cloudprovider/cloudprovider.md
> +AWS is currently the only managed cloud service provider add-on supported by MKE 4. To use a different cloud service provider, before installing that provider you must change the `provider` parameter
```suggestion
To install a different cloud service provider, you must first change the `provider` parameter
under `cloudProvider` in the MKE configuration file to `external` before proceeding to the installation:
```

2024-10-17 06:44 UTC, MagdaDziadosz commented on content/docs/operations/cloudprovider/cloudprovider.md
> +    provider: aws
```suggestion
    provider: external
```
To match description above

2024-10-17 06:44 UTC, MagdaDziadosz commented on content/docs/operations/cloudprovider/cloudprovider.md
> +Refer to the documentation for your chosen cloud service provider to learn of any proprietary requirements.
```suggestion
Refer to the documentation of your chosen cloud service provider to learn about any proprietary requirements.
```

2024-10-17 06:44 UTC, MagdaDziadosz commented on content/docs/operations/cloudprovider/cloudprovider.md
> +An example is offered below of how to use cloud provider AWS to create a Network Load Balancer (NLB) in your MKE cluster.
```suggestion
Below example ilustrates how to use cloud provider AWS to create a Network Load Balancer (NLB) in your MKE cluster. 
```

2024-10-17 06:44 UTC, MagdaDziadosz commented on content/docs/operations/cloudprovider/cloudprovider.md
> +2. Create a service of type LoadBalancer:
```suggestion
2. Create a service of type `LoadBalancer`:
```

2024-10-18 06:31 UTC, MagdaDziadosz approved these changes

2024-10-18 15:34 UTC, KoryKessel-Mirantis approved these changes

2024-10-18 15:34 UTC, merged