cni-2 updates
Mirantis/mke-docs pull request #116
Opened 2024-10-02 19:23 UTC by vikramhh

updates based on changes made for cni phase 2

2024-10-03 15:12 UTC, KoryKessel-Mirantis requested changes

2024-10-03 15:12 UTC, KoryKessel-Mirantis commented on content/docs/concepts/cni.md
> +once mke3 is successfully upgraded to mke4, it displays a list of ports that are no longer required to be opened on manager and/or worker nodes and could be blocked
```suggestion
{{< callout type="note" >}}
- MKE 4 uses a static port range for Kubernetes NodePorts, from  `32768` to `35535`. 
- Only clusters that use the the default Kubernetes proxier `iptables` can be upgraded from MKE 3 to MKE 4.
- Only KDD-backed MKE 3 clusters can be upgraded to MKE 4.
- Following a successful MKE 3 to MKE 4 upgrade, a list displays that presents the ports that no longer need to be opened on manager or worker nodes. These ports can be blocked.
{{< /callout >}}
```

2024-10-18 15:15 UTC, ry4nz approved these changes

2024-10-18 15:19 UTC, KoryKessel-Mirantis approved these changes

2024-10-18 15:19 UTC, merged