[BOP-1277] Add cadvisor docs
Mirantis/mke-docs pull request #124
Opened 2024-10-02 22:03 UTC by byDimasik

This PR adds cadvisor docs and a few related known issues

In MKE 3, we also provided a full list of cAdvisor metrics - https://docs.mirantis.com/mke/3.7/ops/administer-cluster/collect-cluster-metrics-prometheus/cadvisor-mke-metrics.html
I am not sure if it is up-to-date and if MKE 4 provides the same list of metrics. @nsteph could you advise on that?

2024-10-02 22:06 UTC, byDimasik commented on content/docs/operations/monitoring.md
> +| Prometheus      | enabled       | -                           | Collects and stores metrics                                                           |
I changed the order to have Prometheus first as it's the main monitoring component while all others are various extensions

2024-10-02 22:06 UTC, byDimasik commented on content/docs/operations/monitoring.md
> +Prometheus API is available at `https://<mke4_url>/prometheus/`
We may wanna highlight it more as it's kind of important, but I am not sure what style would be appropriate for that

2024-10-04 17:50 UTC, KoryKessel-Mirantis requested changes

2024-10-04 17:50 UTC, KoryKessel-Mirantis commented on content/docs/operations/monitoring.md
> +1. Run the following command to `port-forward` Prometheus:
```suggestion
1. Port forward Prometheus:
```

2024-10-04 17:50 UTC, KoryKessel-Mirantis commented on content/docs/operations/monitoring.md
> +1. Run the following command to `port-forward` Prometheus:
Please change step 1 of the Grafana section to read the same.

2024-10-04 17:50 UTC, KoryKessel-Mirantis commented on content/docs/operations/monitoring.md
> +and exports information about running containers.
```suggestion
[cAdvisor](https://github.com/google/cadvisor) is an open-source tool that collects, aggregates, processes, 
and exports information for running containers.
```

2024-10-04 17:50 UTC, KoryKessel-Mirantis commented on content/docs/operations/monitoring.md
> +cAdvisor is disabled in MKE by default and may be enabled through the MKE configuration file:
```suggestion
cAdvisor is disabled in MKE by default. You can enable the tool through the MKE configuration file:
```

2024-10-04 17:50 UTC, KoryKessel-Mirantis commented on content/docs/release-notes/known-issues.md
> +When cAdvisor is disabled, on the main page of the dashboard, "Disk Usage" and "Memory" metrics have zero values.
```suggestion
When cAdvisor is disabled, the main page of the dashboard presents a `0` value for the **Disk Usage** and  **Memory** metrics.
```

2024-10-04 17:50 UTC, KoryKessel-Mirantis commented on content/docs/release-notes/known-issues.md
> +When cAdvisor is disabled, on the main page of the dashboard, "Disk Usage" and "Memory" metrics have zero values.
As I have not seen the dashboard, I make an assumption in my previous comment about the actual value presented. If, in fact, the word 'zero' is presented instead, please make the appropriate edit.

2024-10-04 17:50 UTC, KoryKessel-Mirantis commented on content/docs/release-notes/known-issues.md
> +Enable cAdvisor in the config file and apply the config with `mkectl apply`
```suggestion
Enable cAdvisor in the MKE configuration file and run `mkectl apply`.
```

2024-10-04 17:50 UTC, KoryKessel-Mirantis commented on content/docs/release-notes/known-issues.md
> +## [BOP-1299] Max Used Disk and Max CPU labels are swapped in the dashboard
```suggestion
## [BOP-1299] Max Used Disk and Max CPU labels are swapped in the cAdvisor dashboard
```

2024-10-04 17:50 UTC, KoryKessel-Mirantis commented on content/docs/release-notes/known-issues.md
> +## [BOP-1307] Prometheus can be access without authentication
```suggestion
## [BOP-1307] Prometheus can be accessed without authentication
```

2024-10-04 17:50 UTC, KoryKessel-Mirantis commented on content/docs/release-notes/known-issues.md
> +Anyone who knows MKE 4 URL can access Prometheus without authentication.
```suggestion
Any party with knowledge of the MKE 4 URL can access Prometheus without authentication.
```

2024-10-08 19:51 UTC, byDimasik commented on content/docs/operations/monitoring.md
> +and exports information about running containers.
I may not know English, but it looks to me that the meaning was changed there. I stole that line from the official cAdvisor doc - https://github.com/google/cadvisor, and the idea here is that when we have containers running, cAdvisor will collect the information about those containers and make it available via the list of metrics. So, why not 'about'?

2024-10-08 19:52 UTC, byDimasik commented on content/docs/release-notes/known-issues.md
> +When cAdvisor is disabled, on the main page of the dashboard, "Disk Usage" and "Memory" metrics have zero values.
![image](https://github.com/user-attachments/assets/e681e7f5-0487-4973-9ed0-783ae2bd2638)

this is what it looks like

2024-10-08 19:54 UTC, byDimasik commented on content/docs/release-notes/known-issues.md
> +## [BOP-1299] Max Used Disk and Max CPU labels are swapped in the dashboard
I was referring to the MKE Dashboard. In general, the dashboard means the MKE Dashboard because this is the only dashboard we have. Do you want me to change it to "the MKE dashboard"?

2024-10-08 19:56 UTC, byDimasik commented on content/docs/operations/monitoring.md
> +1. Run the following command to `port-forward` Prometheus:
done

2024-10-08 19:56 UTC, byDimasik commented on content/docs/operations/monitoring.md
> +cAdvisor is disabled in MKE by default and may be enabled through the MKE configuration file:
done

2024-10-08 19:56 UTC, byDimasik commented on content/docs/release-notes/known-issues.md
> +When cAdvisor is disabled, on the main page of the dashboard, "Disk Usage" and "Memory" metrics have zero values.
done

2024-10-08 19:56 UTC, byDimasik commented on content/docs/release-notes/known-issues.md
> +Enable cAdvisor in the config file and apply the config with `mkectl apply`
done

2024-10-08 19:56 UTC, byDimasik commented on content/docs/release-notes/known-issues.md
> +## [BOP-1307] Prometheus can be access without authentication
done

2024-10-08 19:56 UTC, byDimasik commented on content/docs/release-notes/known-issues.md
> +Anyone who knows MKE 4 URL can access Prometheus without authentication.
done

2024-10-08 23:00 UTC, KoryKessel-Mirantis commented on content/docs/operations/monitoring.md
> +and exports information about running containers.
Ah, @byDimasik, your English is good! I did not like 'about' and I did not really like 'for' either.

Let's go for overkill precision with 'in reference to'.

2024-10-08 23:03 UTC, KoryKessel-Mirantis commented on content/docs/release-notes/known-issues.md
> +When cAdvisor is disabled, on the main page of the dashboard, "Disk Usage" and "Memory" metrics have zero values.
Thanks for the visual, @byDimasik. Having seen it, though, I would like to change the text to read:

"...presents 0% as the value for..."

2024-10-08 23:04 UTC, KoryKessel-Mirantis commented on content/docs/release-notes/known-issues.md
> +## [BOP-1299] Max Used Disk and Max CPU labels are swapped in the dashboard
Yes, let's say "MKE dashboard" here. There may be others out there who are as easily confused as me. :-)

2024-10-11 20:48 UTC, byDimasik commented on content/docs/operations/monitoring.md
> +and exports information about running containers.
done

2024-10-11 20:49 UTC, byDimasik commented on content/docs/release-notes/known-issues.md
> +When cAdvisor is disabled, on the main page of the dashboard, "Disk Usage" and "Memory" metrics have zero values.
done

2024-10-11 20:49 UTC, byDimasik commented on content/docs/release-notes/known-issues.md
> +## [BOP-1299] Max Used Disk and Max CPU labels are swapped in the dashboard
done

2024-10-11 20:49 UTC, byDimasik commented
@KoryKessel-Mirantis I've addressed all your comments. Please take another look

2024-10-11 22:38 UTC, KoryKessel-Mirantis approved these changes

2024-10-14 10:16 UTC, MagdaDziadosz approved these changes

2024-10-14 10:16 UTC, MagdaDziadosz commented on content/docs/release-notes/known-issues.md
> +When cAdvisor is disabled, the main page of the dashboard presents 0% as the value for the **Disk Usage** and  **Memory** metrics.
```suggestion
When cAdvisor is disabled, the main page of the dashboard presents 0% as the value for the **Disk Usage** and **Memory** metrics.
```

2024-10-14 10:48 UTC, merged