[BOP-1236] Remove instructions on direct config resource editing
Mirantis/mke-docs pull request #125
Opened 2024-10-04 16:10 UTC by byDimasik

We should **never** tell users to modify the config resource directly.

**All changes to the config must be done via mkectl apply or UI**

`kubectl edit` of the config file may lead to errors and instabilities in the cluster and should only be done by an experienced MKE 4 developer or support team member. Users should not attempt editing the config resource by themselves, and our documentation should not advertise this way of modifying the config.

2024-10-04 20:23 UTC, KoryKessel-Mirantis requested changes

2024-10-04 20:23 UTC, KoryKessel-Mirantis commented on content/docs/operations/telemetry.md
> +In the MKE config file, set the `telemetry.enabled` field to `true` to enable telemetry.
```suggestion
1. Access the MKE configuration file.

2. Set the `telemetry.enabled` field to `true`.
```

2024-10-04 20:23 UTC, KoryKessel-Mirantis commented on content/docs/operations/telemetry.md
> +    enabled: true
```suggestion
   ```yaml
   spec:
     tracking:
       enabled: true
   ```

2024-10-04 20:23 UTC, KoryKessel-Mirantis commented on content/docs/operations/telemetry.md
> +Apply the new settings with `mkectl apply`.
```suggestion
3. Run the  `mkectl apply` command to apply the new settings.
```

2024-10-04 20:23 UTC, KoryKessel-Mirantis commented on content/docs/operations/telemetry.md
>  Mirantis by way of a secure Segment endpoint.
Please edit the sentence to read:

"After a few moments, the change will reconcile in the configuration. From this point onward, MKE will transmit key usage data to Mirantis by way of a secure Segment endpoint."

2024-10-04 20:23 UTC, KoryKessel-Mirantis commented on content/docs/operations/telemetry.md
> +    enabled: true
The point here being to have the codeblock align under the step text and not the step number.

2024-10-08 19:45 UTC, byDimasik commented on content/docs/operations/telemetry.md
>  Mirantis by way of a secure Segment endpoint.
done

2024-10-08 19:45 UTC, byDimasik commented on content/docs/operations/telemetry.md
> +Apply the new settings with `mkectl apply`.
done

2024-10-08 19:45 UTC, byDimasik commented on content/docs/operations/telemetry.md
> +In the MKE config file, set the `telemetry.enabled` field to `true` to enable telemetry.
done

2024-10-08 19:45 UTC, byDimasik commented on content/docs/operations/telemetry.md
> +    enabled: true
done

2024-10-09 22:45 UTC, KoryKessel-Mirantis approved these changes

2024-10-09 23:10 UTC, merged