[BOP-1195] Initial docs for kubelet configuration
Mirantis/mke-docs pull request #126
Opened 2024-10-04 22:42 UTC by nsteph

This PR creates some initial docs for configuring the various kube components, with special attention paid to kubelet and kubelet custom profiles.

2024-10-08 22:27 UTC, KoryKessel-Mirantis requested changes

2024-10-08 22:27 UTC, KoryKessel-Mirantis commented on content/docs/operations/kubernetes/kubelet-custom-profiles.md
> +Example: this configuration creates a custom profile named `hardworker` that specifies thresholds for garbage collection of images and eviction.
```suggestion
The following example configuration creates a custom profile named `hardworker` that specifies thresholds for the garbage collection of images and eviction.
```

2024-10-08 22:27 UTC, KoryKessel-Mirantis commented on content/docs/operations/kubernetes/kubelet-custom-profiles.md
> +Hosts may be assigned a custom profile using the `Hosts` section of the MKE config. The profile name is an install-time argument for the host.
```suggestion
Hosts can be assigned a custom profile through the `hosts` section of the MKE configuration file, whereas the profile name is an install time argument for the host.
```

2024-10-08 22:27 UTC, KoryKessel-Mirantis commented on content/docs/operations/kubernetes/kubelet-custom-profiles.md
> +Example: this configuration applies the `hardworker` custom profile to the `localhost` node.
```suggestion
The following example configuration applies the `hardworker` custom profile to the `localhost` node.
```

2024-10-08 22:27 UTC, KoryKessel-Mirantis commented on content/docs/operations/kubernetes/kubelet-custom-profiles.md
> +The Kubelet configuration of each node is created by merging a number of different configuration sources. For MKE, the order is as follows:
```suggestion
The Kubelet configuration of each node is created by merging several different configuration sources. For MKE 4, the order is as follows:
```

2024-10-08 22:27 UTC, KoryKessel-Mirantis commented on content/docs/operations/kubernetes/kubelet-custom-profiles.md
> +- Runtime flags specified in `kubelet.extraArgs` (highest precedence)
```suggestion
1. Structured configuration values specified in the `kubelet` section of the MKE configuration, which is the lowest precedence.
2. Custom profile values specified in `kublelet.customProfiles`.
3. Runtime flags specified in `kubelet.extraArgs`, which is the highest precedence.
```

2024-10-08 22:27 UTC, KoryKessel-Mirantis commented on content/docs/operations/kubernetes/kubelet-custom-profiles.md
> +For a more information about the precedence of Kubelet configuration values, see [kubelet-configuration-merging-order](https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/#kubelet
```suggestion
For more information on Kubelet configuration value precedence, refer to the official Kubernetes documentation [Kubelet configuration merging order](https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/#kubelet-configuration-merging-order).
```

2024-10-14 18:32 UTC, nsteph commented on content/docs/operations/kubernetes/_index.md
> +Advanced: the kubelet may be further configured using the `extraArgs` field. This map creates runtime flags that are passed directly to the kubelet process. Flags configured in this way are applied w
I tried to rewrite these sections for clarity. Does this read better?

"You can further configure a kubelet using the `extraArgs` field to define flags. This field accepts a list of key-value pairs, which are passed directly to the kubelet process at runtime."

2024-10-14 22:21 UTC, KoryKessel-Mirantis approved these changes

2024-10-14 22:25 UTC, merged