[BOP-1313] Add documentation for opa gatekeeper
Mirantis/mke-docs pull request #127
Opened 2024-10-07 17:21 UTC by RaunakShah

2024-10-09 11:59 UTC, MagdaDziadosz requested changes

2024-10-09 11:59 UTC, MagdaDziadosz commented on content/docs/operations/policycontroller/_index.md
> +Currently, the only policy controller supported is [OPA Gatekeeper](https://open-policy-agent.github.io/gatekeeper/website/docs/).
```suggestion
MKE 4 allows installation of third-party policy controllers for Kubernetes. 
[OPA Gatekeeper](https://open-policy-agent.github.io/gatekeeper/website/docs/)
is currently the only supported policy controller.
```
I was not sure about installation vs integration. Do we install it or integrate it in the system?

2024-10-09 11:59 UTC, MagdaDziadosz commented on content/docs/operations/policycontroller/opagatekeeper.md
> +MKE supports the use of OPA Gatekeeper for purposes of policy control.
```suggestion
MKE 4 supports the use of OPA Gatekeeper for purposes of policy control.
```

Is it OPA Gatekeeper or just Gatekeeper, the website linked below states: “Compared to using OPA with its sidecar kube-mgmt (aka Gatekeeper v1.0), Gatekeeper introduces the following functionality”. So are we using 1.0 or older version that should be referred to as just Gatekeeper?

2024-10-09 11:59 UTC, MagdaDziadosz commented on content/docs/operations/policycontroller/opagatekeeper.md
> +- Once OPA Gatekeeper is enabled and the configuration is applied to the cluster, wait for the OPA Gatekeeper pods to enter the `Running` state:
```suggestion
Before proceeding, make sure that OPA Gatekeeper is enabled and the configuration is applied to the cluster.

To check if the OPA Gatekeeper pods have entered the `Running` state, run:
```

2024-10-09 11:59 UTC, MagdaDziadosz commented on content/docs/operations/policycontroller/opagatekeeper.md
> +```bash
```suggestion
Example output:

```bash
```

2024-10-09 11:59 UTC, MagdaDziadosz commented on content/docs/operations/policycontroller/opagatekeeper.md
> +```bash
```suggestion
To create constraint templates and constraints from the open source Gatekeeper library, run:

```bash
```
I removed the link since it was missing, please, add it if needed.

2024-10-09 11:59 UTC, MagdaDziadosz commented on content/docs/operations/policycontroller/opagatekeeper.md
> +```bash
```suggestion
To create pods that are disallowed by the newly created policies, run:

```bash
```

2024-10-09 11:59 UTC, MagdaDziadosz commented on content/docs/operations/policycontroller/opagatekeeper.md
> +- OPA Gatekeeper should disallow the creation of the pod:
```suggestion
To disallow the creation of the pod, run:

```bash
```

2024-10-09 11:59 UTC, MagdaDziadosz commented on content/docs/operations/policycontroller/opagatekeeper.md
> +**OPA Gatekeeper configuration parameters**
```suggestion
## MKE version comparison

```

2024-10-09 11:59 UTC, MagdaDziadosz commented on content/docs/operations/policycontroller/opagatekeeper.md
> +## Migration from MKE3
```suggestion
## Migration from MKE 3
```

2024-10-09 11:59 UTC, MagdaDziadosz commented on content/docs/operations/policycontroller/opagatekeeper.md
> +If OPA Gatekeeper is enabled in MKE3, then the templates and constraints created previously are retained across the migration process. Also, the list of namespaces exempted from policy control are re
```suggestion
If OPA Gatekeeper is enabled in MKE 3, the templates, constraints and list of
namespaces exempted from policy control are retained through the migration process.
```

2024-10-09 11:59 UTC, MagdaDziadosz commented on content/docs/operations/policycontroller/opagatekeeper.md
> +- blueprint-system
```suggestion
The `exemptNamespaces` field lists the namespaces that are exempt from policy enforcement. 
The following namespaces are added by default, and thus cannot be removed:

- `mke`
- `kube-system`
- `kube-public`
- `kube-node-lease`
- `k0s-system`
- `k0s-autopilot`
- `flux-system`
- `blueprint-system`
```

2024-10-09 11:59 UTC, MagdaDziadosz commented on content/docs/operations/policycontroller/opagatekeeper.md
> +To configure OPA Gatekeeper in MKE, set the following fields in the MKE configuration file
```suggestion
To configure OPA Gatekeeper in MKE, set the following fields in the MKE configuration file:
```

2024-10-11 19:08 UTC, RaunakShah commented on content/docs/operations/policycontroller/_index.md
> +Currently, the only policy controller supported is [OPA Gatekeeper](https://open-policy-agent.github.io/gatekeeper/website/docs/).
Install is probably more accurate

2024-10-11 19:08 UTC, RaunakShah commented on content/docs/operations/policycontroller/opagatekeeper.md
> +MKE supports the use of OPA Gatekeeper for purposes of policy control.
OPA is the general term and Gatekeeper is the kubernetes specific implementation. I think upstream, calling it OPA Gatekeeper is more conventional. For example, the images are of the form `openpolicyagent/gatekeeper:`

2024-10-11 19:08 UTC, RaunakShah commented on content/docs/operations/policycontroller/opagatekeeper.md
> +```bash
Thanks for catching this, I added it back

2024-10-11 19:08 UTC, RaunakShah commented on content/docs/operations/policycontroller/opagatekeeper.md
> +- OPA Gatekeeper should disallow the creation of the pod:
> To disallow the creation of the pod, run:

The bash below is an example output of running the command in the previous line. How should we rephrase it?

2024-10-15 21:44 UTC, RaunakShah commented
@MagdaDziadosz I've addressed all your comments, PTAL!

2024-10-16 12:25 UTC, MagdaDziadosz requested changes

2024-10-16 12:25 UTC, MagdaDziadosz commented on content/docs/operations/policycontroller/opagatekeeper.md
> +## Concepts
```suggestion
```

2024-10-17 06:56 UTC, MagdaDziadosz approved these changes

2024-10-17 16:34 UTC, merged