Update telemetry documentation
Mirantis/mke-docs pull request #128
Opened 2024-10-07 17:22 UTC by RaunakShah

Adds the correct way to update the telemetry configuration in MKE4.

2024-10-09 14:24 UTC, KoryKessel-Mirantis commented on content/docs/operations/telemetry.md
> +To enable telemetry for MKE 4, set the `tracking.enabled` section of the MKE configuration file.
```suggestion
You enable telemetry for MKE 4 through the `tracking.enabled` section of the MKE configuration file:
```

2024-10-11 16:23 UTC, KoryKessel-Mirantis commented
Hey @RaunakShah, can you please take a look at https://github.com/Mirantis/mke-docs/issues/132 and perhaps drop a rough note into this PR that addresses @brianbancroft's ask (which, of course, I will be glad to help sharpen up)?

2024-10-11 20:02 UTC, RaunakShah commented
Didn't see that https://github.com/Mirantis/mke-docs/pull/125 addresses the same thing as this PR. So I've updated it to only include the licensing part.

2024-10-11 22:19 UTC, KoryKessel-Mirantis requested changes

2024-10-11 22:19 UTC, KoryKessel-Mirantis commented on content/docs/operations/telemetry.md
> +    In case the license associated with the MKE cluster is invalid or expired, telemetry will be enabled by default and there will be no option to disable it.
```suggestion
    Telemetry is automatically enabled for MKE 4 clusters that are running without a license, with a license that has expired, or with an invalid license. In all of such scenarios, you will only be able to disable telemetry once a valid license has been applied to the cluster.
```

2024-10-11 22:25 UTC, KoryKessel-Mirantis approved these changes

2024-10-11 22:26 UTC, merged