Restructuring of Kubernetes components section.
Mirantis/mke-docs pull request #138
Opened 2024-10-15 13:50 UTC by KoryKessel-Mirantis

2024-10-16 10:20 UTC, MagdaDziadosz requested changes

2024-10-16 10:20 UTC, MagdaDziadosz commented on content/docs/operations/kubernetes/kube-apiserver.md
> +which include pods, services, and replicationcontrollers, among others. The
```suggestion
which include pods, services, and replication controllers, among others. The
```

2024-10-16 10:20 UTC, MagdaDziadosz commented on content/docs/operations/kubernetes/kube-apiserver.md
> +`apiServer` section of the MKE configuration file, an example of which follows:
```suggestion
`apiServer` section of the MKE configuration file:
```

2024-10-16 10:20 UTC, MagdaDziadosz commented on content/docs/operations/kubernetes/kube-controller-manager.md
> +section of the MKE configuration file, an example of which follows:
```suggestion
section of the MKE configuration file:
```

2024-10-16 10:20 UTC, MagdaDziadosz commented on content/docs/operations/kubernetes/kube-scheduler.md
> +  scheduler:
Add missing code example.

2024-10-16 10:20 UTC, MagdaDziadosz commented on content/docs/operations/kubernetes/kube-apiserver.md
> +You can further configure kube-apiserver using the `extraArgs` field to define
```suggestion
You can further configure Kubernetes API server using the `extraArgs` field to define
```

2024-10-16 10:20 UTC, MagdaDziadosz commented on content/docs/operations/kubernetes/kube-controller-manager.md
> +You can further configure kube-controller-manager using the `extraArgs` field
```suggestion
You can further configure Kubernetes controller manager using the `extraArgs` field
```

2024-10-16 10:20 UTC, MagdaDziadosz commented on content/docs/operations/kubernetes/kube-scheduler.md
> +You can further configure kube-scheduler using the `extraArgs` field to define
```suggestion
You can further configure Kubernetes scheduler using the `extraArgs` field to define
```

2024-10-16 10:20 UTC, MagdaDziadosz commented on content/docs/operations/kubernetes/kubelet.md
> +A kubelet custom profile is comprised of a profile name and a set of values.
```suggestion
A kubelet custom profile consists of a profile name and a set of values.
```

2024-10-16 10:20 UTC, MagdaDziadosz commented on content/docs/operations/kubernetes/kubelet.md
> +configuration that is applied to a target node.
```suggestion
configuration applied to a target node.
```

2024-10-16 10:20 UTC, MagdaDziadosz commented on content/docs/operations/kubernetes/kubelet.md
> +configuration file, whereas the profile name is an install time argument for
```suggestion
configuration file, whereas the profile name is an installation time argument for
```

2024-10-16 10:20 UTC, MagdaDziadosz commented on content/docs/operations/kubernetes/kubelet.md
> +For detail on all possible values, refer to the official Kubrernetes
```suggestion
For detail on all possible values, refer to the official Kubernetes
```

2024-10-16 10:20 UTC, MagdaDziadosz commented on content/docs/operations/kubernetes/kubelet.md
> +configuration file, an example of which follows:
```suggestion
configuration file:
```

2024-10-16 10:20 UTC, MagdaDziadosz commented on content/docs/operations/kubernetes/kubelet.md
> +documentation [Set Kubelet Parameters Via a Configuration
```suggestion
documentation [Set Kubelet Parameters Via A Configuration
```

2024-10-16 10:20 UTC, MagdaDziadosz commented on content/docs/operations/kubernetes/kubelet.md
> +that specifies thresholds for the garbage collection of images and eviction.
```suggestion
that specifies thresholds for the garbage collection of images and eviction:
```

2024-10-16 10:20 UTC, MagdaDziadosz commented on content/docs/operations/kubernetes/kubelet.md
> +the `localhost` node.
```suggestion
the `localhost` node:
```

2024-10-16 12:15 UTC, KoryKessel-Mirantis commented on content/docs/operations/kubernetes/kube-scheduler.md
> +  scheduler:
@nsteph, is there more you can offer here for the code example?

2024-10-17 18:51 UTC, nsteph commented on content/docs/operations/kubernetes/kube-scheduler.md
> +  scheduler:
```suggestion
  scheduler:
    profilingEnabled: true
    bindToAll: true
```

2024-10-18 13:08 UTC, KoryKessel-Mirantis commented on content/docs/operations/kubernetes/kubelet.md
> +configuration that is applied to a target node.
```suggestion
A kubelet custom profile comprises a profile name and a set of values.
The profile name identifies the profile and targets it to specific
nodes in the cluster, while the values are merged into the final kubelet
configuration that is applied to a target node.
```

2024-10-18 13:10 UTC, MagdaDziadosz approved these changes

2024-10-18 13:27 UTC, merged