Add SSOMetadataURL example
Mirantis/mke-docs pull request #145
Opened 2024-10-18 16:53 UTC by nwneisen

#71 

Adds an example for the SSOMetaDataURL to the Okta setup.

Created tabs and added more details for manual configuration

Fixed some invalid redirect urls

Replaces #79

2024-10-24 22:46 UTC, KoryKessel-Mirantis requested changes

2024-10-24 22:46 UTC, KoryKessel-Mirantis commented on content/docs/tutorials/authentication-provider-setup/setting-up-okta-as-a-saml-provider.md
> +```yaml
```suggestion
An example of the `saml` section of the MKE 4 configuration file under `authentication` follows:

```yaml
```

2024-10-24 22:46 UTC, KoryKessel-Mirantis commented on content/docs/tutorials/authentication-provider-setup/setting-up-okta-as-a-saml-provider.md
> +Run the `mkectl apply` command with your MKE configuration file.
```suggestion
Once the `saml` section of the MKE 4 configuration file is set, run it with the `mkectl apply` command.
```

2024-10-25 14:38 UTC, nwneisen commented on content/docs/tutorials/authentication-provider-setup/setting-up-okta-as-a-saml-provider.md
> +Example of information provided when you access the `ssoMetadataURL` URL:
```suggestion
Example ssoMetadataURL information:
```

2024-10-25 14:40 UTC, nwneisen commented on content/docs/tutorials/authentication-provider-setup/setting-up-okta-as-a-saml-provider.md
> +```
Carry over the discussion from the previous PR

This is useful for a customer when they are setting up SAML and they wonder what they should be seeing. If the goal of the docs is to "help customers setup an MKE4 cluster", then I suggest we leave this and look for more areas that we can clarify what should be seen for customers.

2024-10-25 14:46 UTC, KoryKessel-Mirantis requested changes

2024-10-25 14:46 UTC, KoryKessel-Mirantis commented on content/docs/tutorials/authentication-provider-setup/setting-up-okta-as-a-saml-provider.md
> +An example of the `saml` section of the MKE 4 configuration file under `authentication` follows:
```suggestion

An example of the `saml` section of the MKE 4 configuration file under `authentication` follows:
```

2024-10-25 14:46 UTC, KoryKessel-Mirantis commented on content/docs/tutorials/authentication-provider-setup/setting-up-okta-as-a-saml-provider.md
> +Example ssoMetadataURL information:
```suggestion
Example `ssoMetadataURL` information:
```

2024-10-25 15:28 UTC, KoryKessel-Mirantis approved these changes
Passing to @MagdaDziadosz for second TW review.

2024-10-28 07:14 UTC, MagdaDziadosz approved these changes

2024-10-28 07:14 UTC, MagdaDziadosz commented on content/docs/tutorials/authentication-provider-setup/setting-up-okta-as-a-saml-provider.md
> +| `usernameAttr` | Attribute used to map the username to the MKE user.
```suggestion
| `usernameAttr` | Attribute that maps the username to the MKE user.                                                                                                                                                                                                                                                            |
```
Changed to match the attribute description below.

2024-10-28 07:14 UTC, MagdaDziadosz commented on content/docs/tutorials/authentication-provider-setup/setting-up-okta-as-a-saml-provider.md
> +Okta provides a metadata URL with which you can configure SAML for MKE 4. MKE is able to obtain information for all SAML configurations in your MKE cluster through that URL, which you configure to th
```suggestion
Okta provides a metadata URL with which you can configure SAML for MKE 4.
MKE is able to obtain information for all SAML configurations in your MKE cluster through that URL,
which you configure to the `ssoMetadataURL` parameter in the `authentication` section of the MKE
configuration file.
```
Broken between few lines to meet our style guidelines.

2024-10-28 12:04 UTC, merged