[DOC] Architecture update
Mirantis/mke-docs pull request #15
Opened 2024-05-29 11:14 UTC by MagdaDziadosz

Update of the architecture section.

2024-06-04 22:04 UTC, KoryKessel-Mirantis commented on content/docs/concepts/architecture/architecture.md
> +Kubernetes platform designed to be secure, scalable, and reliable.
```suggestion
Kubernetes platform that is designed to be secure, scalable, and reliable.
```
```suggestion
Kubernetes platform designed to be secure, scalable, and reliable.
```

2024-06-04 22:05 UTC, KoryKessel-Mirantis commented on content/docs/concepts/architecture/architecture.md
> +MKE 4 is deployed using an MKE configuration file.
```suggestion
You deploy the software using an MKE configuration file.
```

2024-06-04 22:06 UTC, KoryKessel-Mirantis commented on content/docs/concepts/architecture/architecture.md
> +See the [Configuration and blueprints](configuration.md) for more information.
```suggestion
Refer to [Configuration and blueprints](configuration.md) for more information.
```

2024-06-04 22:08 UTC, KoryKessel-Mirantis commented on content/docs/concepts/architecture/architecture.md
> +See the [official k0s documentation](https://docs.k0sproject.io/v1.29.3+k0s.0/)
```suggestion
Refer to the [official k0s documentation](https://docs.k0sproject.io/v1.29.3+k0s.0/)
```

2024-06-04 22:20 UTC, KoryKessel-Mirantis commented on content/docs/concepts/architecture/architecture.md
> +MKE 4 uses a control plane that oversees crucial cluster-wide decisions,
```suggestion
The MKE 4 control plane oversees crucial cluster-wide decisions,
```

2024-06-04 22:22 UTC, KoryKessel-Mirantis commented on content/docs/concepts/architecture/architecture.md
> +and monitors and responds to events within the cluster.
Consider:

The MKE 4 control plane oversees crucial cluster-wide decisions, monitoring and responding to events within the cluster.

2024-06-04 22:29 UTC, KoryKessel-Mirantis commented on content/docs/concepts/architecture/architecture.md
> +While the control plane components can function on any machine in the cluster,
What is meant here by "streamline the process"? What process?

Perhaps something like:

"And while the control plane can function on any machine in the cluster, setup scripts ensure maximum efficiency by running all control plane components on one machine and by excluding user containers from that machine."

2024-06-04 22:30 UTC, KoryKessel-Mirantis commented on content/docs/concepts/architecture/architecture.md
> +By default, MKE 4 installs Calico as the Container Network Interface (CNI) plugin with the following configuration:
```suggestion
By default, Calico is installed as the Container Network Interface (CNI) plugin, with the following configuration:
```

2024-06-04 22:31 UTC, KoryKessel-Mirantis commented on content/docs/concepts/architecture/architecture.md
> +- IPv4 only with a fixed Pod CIDR of `10.244.0.0/16`.
```suggestion
- IPv4 only, with a fixed Pod CIDR of `10.244.0.0/16`.
```

2024-06-04 22:31 UTC, KoryKessel-Mirantis commented on content/docs/concepts/architecture/architecture.md
> +- The datastore mode is set to `kdd`.
```suggestion
- The datastore mode set to `kdd`.
```

2024-06-04 22:32 UTC, KoryKessel-Mirantis commented on content/docs/concepts/architecture/architecture.md
> +- `vxlan` backend, which uses the default port of `4789` for traffic and default virtual network ID of `4096`.
```suggestion
- A `vxlan` backend, which uses the default port of `4789` for traffic and default virtual network ID of `4096`.
```

2024-06-04 22:32 UTC, KoryKessel-Mirantis commented on content/docs/concepts/architecture/architecture.md
> +With the Alpha.1 release, MKE 4 has the following limitations:
```suggestion
The MKE 4 Alpha.1 release has the following limitations:
```

2024-06-04 22:39 UTC, KoryKessel-Mirantis commented on content/docs/concepts/architecture/architecture.md
> +- When a cluster is upgraded from MKE 3, the Calico configuration is not migrated.
```suggestion
- The CNI plugin cannot be changed.
- Calico cannot be reconfigured.
- The Calico configuration is not migrated during an upgrade to MKE4 from MKE 3.
```

2024-06-04 22:42 UTC, KoryKessel-Mirantis commented on content/docs/concepts/architecture/configuration.md
> +In the configuration file, you can:
```suggestion
Use the MKE configuration file to:
```

2024-06-04 22:49 UTC, KoryKessel-Mirantis commented on content/docs/concepts/architecture/configuration.md
> +The configuration file is translated into a more complex blueprint
```suggestion
Once set, the MKE configuration file is translated into a more complex blueprint
```

2024-06-04 22:58 UTC, KoryKessel-Mirantis commented on content/docs/concepts/architecture/configuration.md
> +section of the file:
```suggestion
1. Generate the default MKE configuration file:

```bash
mkectl init > mke.yaml
```
2. Modify the generated file to deploy MKE on the cluster.

3. Modify the `hosts` section of the MKE configuration file to apply the configuration to a set of pre-existing machines:
```

2024-06-04 23:02 UTC, KoryKessel-Mirantis commented on content/docs/concepts/architecture/configuration.md
> +To generate the default MKE configuration file run `mkectl init > mke.yaml` command.
Suggest making this an enumerated procedure:

1. Generate the default MKE configuration file:

```bash
mkectl init > mke.yaml
```
2. Modify the generated file to deploy MKE on the cluster.

3. Modify the `hosts` section of the MKE configuration file to apply the configuration to a set of pre-existing machines:

2024-06-07 14:45 UTC, KoryKessel-Mirantis requested changes

2024-06-07 14:45 UTC, KoryKessel-Mirantis commented on content/docs/concepts/architecture/configuration.md
> +All MKE 4 configuration files are translated into blueprints.
Suggest:

All MKE 4 configuration files are translated into blueprints, a file type that is used to create Kubernetes Custom Resources (CRDs) that are also called blueprints.

Blueprint files must be in Kubernetes YAML format, and they must contain many of the same fields as a standard Kubernetes Object.

MKE 4 uses Blueprint Operator to manage blueprints and their assignments.

2024-06-07 14:45 UTC, KoryKessel-Mirantis commented on content/docs/concepts/architecture/configuration.md
> +A blueprint is composed of three sections:
```suggestion
A blueprint comprises three sections:
```

2024-06-07 14:45 UTC, KoryKessel-Mirantis commented on content/docs/concepts/architecture/configuration.md
> +1. The Kubernetes Provider details with settings for that provider.
Suggest not offering this content as an enumerated list. Instead, let's do a definition list:

<dl>
  <dt><strong>Kubernetes Provider</strong></dt>
  <dd>Details the settings for the provider<br>For the most part, the Kubernetes Provider section is is managed by mkectrl, independently of the user's MKE configuration file. </dd>
  <dt><strong>Infrastructure</strong></dt>
  <dd>Provides details that are used for the Kubernetes Cluster; the hosts section of the MKE configuration file.</dd>
  <dt><strong>Components</strong></dt>
  <dd>Composed of addons that are specified in the MKE configuration file. The `mkectl` command transforms the configuration options 
into specific settings for either Helm or Manifest type addons that are deployed into the cluster.</dd>
</dl>

2024-06-07 14:45 UTC, KoryKessel-Mirantis commented on content/docs/concepts/architecture/configuration.md
> +To see detailed blueprint of an MKE config run `mkectl init --blueprint` command.
```suggestion
To view a detailed blueprint of an MKE configuration, run the `mkectl init --blueprint` command.
```

2024-06-07 14:45 UTC, KoryKessel-Mirantis commented on content/docs/concepts/architecture/configuration.md
> +You can modify the blueprint directly, but any such modification is considered
Suggest breaking this sentence off from the one before it and changing it to a callout:

>It is possible to directly modify a blueprint, however such modifications are considered advanced and support by MKE 4 is not assured.

2024-06-07 14:45 UTC, KoryKessel-Mirantis commented on content/docs/concepts/architecture/migrate-configuration.md
> +If you migrate from MKE 3, you can pass some options to `mkectl` to transfer
Suggest: 

In migrating to MKE 4 from MKE 3, you can directly transfer settings by passing several options to `mkectl`.

2024-06-07 14:45 UTC, KoryKessel-Mirantis commented on content/docs/concepts/architecture/migrate-configuration.md
> +**Convert local MKE 3 config**
Suggest:

**To convert a local MKE 3 configuration for MKE 4:**

Set the `--mke3-config` flag to convert a downloaded MKE 3 configuration file into a valid MKE 4 configuration file, as follows:

2024-06-07 15:11 UTC, KoryKessel-Mirantis commented on content/docs/concepts/architecture/configuration.md
> +A core part of MKE 4 is the ability to selectively install addons from a set of
Suggest editing to read:

A core component of MKE 4 is a default set of curated and tested addons that you can install by running `mkectl init' and subsequently applying the generated configuration file.

Using the MKE configuration file, you can enable and disable the MKE 4 addons, as well as modify their settings. In addition, you can use the 'mkectl init` command with the `--blueprint` option to print the generated blueprint that reflects your current MKE 4 configuration.

2024-06-10 22:47 UTC, KoryKessel-Mirantis approved these changes

2024-06-11 14:44 UTC, nwneisen commented on content/docs/concepts/architecture/architecture.md
> +You deploy the software using an MKE configuration file.
IMO this might read better as

"The entire cluster and its components can be managed using a single configuration file"

2024-06-11 14:44 UTC, nwneisen commented on content/docs/concepts/architecture/architecture.md
> +The MKE 4 control plane oversees crucial cluster-wide decisions, monitoring and
This isn't true. And we don't really have "setup scripts".

Users can select whether a node is used as a manager, worker, or manager+worker in their node configuration section.

2024-06-11 14:44 UTC, nwneisen commented on content/docs/concepts/architecture/configuration.md
> +- Enable or disable certain MKE 4 features.
Enable or disable certain MKE 4 features -> Enable or disable certain MKE components

- Configure features of the different components

2024-06-11 14:44 UTC, nwneisen commented on content/docs/concepts/architecture/configuration.md
> +## Create configuration
This belongs in a "Getting Started" page imo

2024-06-11 14:44 UTC, nwneisen commented on content/docs/concepts/architecture/configuration.md
> +2. Modify the generated file to deploy MKE on the cluster.
Remove 2 and just go to 3

2024-06-11 14:44 UTC, nwneisen commented on content/docs/concepts/architecture/configuration.md
> +to apply the configuration to a set of pre-existing machines:
Make a note that users will have to setup the pre-existing machines

2024-06-11 14:44 UTC, nwneisen commented on content/docs/concepts/architecture/configuration.md
> +## Blueprints
I'm not sure we should really go into any details for blueprints other than say that one is generated from the config and how to view it. For details we should send customers to the blueprint documentationhttps://mirantiscontainers.github.io/blueprint/

2024-06-14 09:43 UTC, KoryKessel-Mirantis commented on content/docs/concepts/architecture/configuration.md
> +to apply the configuration to a set of pre-existing machines:
Added "that you have set up in advance" to the end of the sentence.

2024-06-14 10:18 UTC, KoryKessel-Mirantis commented on content/docs/concepts/architecture/configuration.md
> +## Blueprints
Tabling *Control plane* for Alpha.1 initial docs, with a comment at the bottom of the file to revisit.

2024-06-14 10:22 UTC, KoryKessel-Mirantis commented on content/docs/concepts/architecture/architecture.md
> +The MKE 4 control plane oversees crucial cluster-wide decisions, monitoring and
Tabling Control plane for Alpha.1 initial docs, with a comment at the bottom of the file to revisit.

2024-06-14 10:38 UTC, KoryKessel-Mirantis commented on content/docs/concepts/architecture/configuration.md
> +## Create configuration
Left comment to do this as follow-up to initial publication.

2024-06-14 10:40 UTC, KoryKessel-Mirantis commented on content/docs/concepts/architecture/configuration.md
> +## Blueprints
Left a comment to follow-up on transforming this section following initial publication.

2024-06-14 12:21 UTC, merged