[BOP-1429] Add telemetry information about k0s
Mirantis/mke-docs pull request #157
Opened 2024-10-24 18:59 UTC by RaunakShah

Add doc to call out that MKE 4 telemetry settings are applied to the k0s configuration as well.

2024-10-24 22:57 UTC, KoryKessel-Mirantis requested changes

2024-10-24 22:57 UTC, KoryKessel-Mirantis commented on content/docs/configuration/telemetry.md
> +
```suggestion
{{< callout type="info" >}}
    The MKE 4 telemetry enablement setting is automatically applied to the k0s configuration. 
{{< /callout >}}

```

2024-10-24 22:57 UTC, KoryKessel-Mirantis commented on content/docs/configuration/telemetry.md
> +
@RaunakShah, I think this Info directive should come after the existing Info directive, so that it presents just above the *Enable telemetry through the MKE CLI* heading.

2024-10-25 20:33 UTC, ry4nz approved these changes

2024-10-25 20:59 UTC, KoryKessel-Mirantis approved these changes

2024-10-25 20:59 UTC, merged