[DOC] Edit setup content initial
Mirantis/mke-docs pull request #16
Opened 2024-05-29 14:45 UTC by KoryKessel-Mirantis

Initial edit of MKE 4 Setup content, including text changes and content restructuring/granulation.

2024-05-30 17:31 UTC, nwneisen commented on content/docs/setup/getting-started/Using-the-cluster.md
> +kubeconfig of the cluster to `~/.mke/<cluster name>.kubeconfig`, from where you
My bad. This file is always named `~/.mke/mke.kubeconfig`

2024-05-30 17:38 UTC, nwneisen commented on content/docs/setup/getting-started/Using-the-cluster.md
> +kubeconfig of the cluster to `~/.mke/<cluster name>.kubeconfig`, from where you
Maybe change the wording to be more like

`you can use this kubeconfig using one of the following methods:`

To clarify that all of these don't need to be done

2024-06-06 15:13 UTC, ry4nz commented on content/docs/setup/getting-started/prerequisites.md
> +Currently, MKE 4 is only certified for use on the Ubuntu 20.04 Linux
add Ubuntu 22.04

2024-06-06 15:15 UTC, ry4nz commented on content/docs/setup/getting-started/prerequisites.md
> +
Add: "This is for the current pre-release only", the pre-requisites will change upon GA

2024-06-06 15:16 UTC, ry4nz commented on content/docs/setup/install-mke4-cli.md
> +you have the following tools installed on your system:
this needs to be updated to alpha.1.0

2024-06-06 15:17 UTC, ry4nz commented on content/docs/setup/upgrade-from-mke-3/upgrade-prerequisites.md
> +  Version: v0.0.5
update to v4.0.0-alpha.1.0

2024-06-06 15:20 UTC, ry4nz commented on content/docs/setup/getting-started/prerequisites.md
> +Currently, MKE 4 is only certified for use on the Ubuntu 20.04 Linux
@sergeymirantis How do we want to articulate the supported versions based on https://miracloud.slack.com/archives/C05Q9JN9M7C/p1717651785280469?thread_ts=1717621438.522759&cid=C05Q9JN9M7C

2024-06-06 15:22 UTC, sakshisharma84 commented on content/docs/setup/getting-started/installation.md
> +### Init
You should add Prerequisite section here as well. We need to have mkectl installed in the system prior to this.

2024-06-06 15:23 UTC, sakshisharma84 commented on content/docs/setup/getting-started/installation.md
> +### Init
Please use details from https://github.com/Mirantis/mke-docs/tree/main/content/docs/setup#installation-via-script.

2024-06-06 15:25 UTC, sakshisharma84 commented on content/docs/setup/getting-started/k0s-in-aws/terraform-scenario.md
> +
@KoryKessel-Mirantis we can now use installation script to install all the dependencies. I have included all the details in https://github.com/Mirantis/mke-docs/tree/main/content/docs/setup#installation-via-script. Please use it as reference.

2024-06-06 15:52 UTC, KoryKessel-Mirantis commented on content/docs/setup/getting-started/installation.md
> +### Init
Rather than include a Prerequisites section in a topic in a chapter in which there is a Prerequisites topic, I suggest that we add mkectl as an entry in that Prerequisites topic.

2024-06-06 15:52 UTC, KoryKessel-Mirantis commented on content/docs/setup/upgrade-from-mke-3/upgrade-prerequisites.md
> +  Version: v0.0.5
Done.

2024-06-06 16:06 UTC, sakshisharma84 commented on content/docs/setup/getting-started/installation.md
> +### Init
discussed offline.

2024-06-06 16:17 UTC, KoryKessel-Mirantis commented on content/docs/setup/getting-started/Using-the-cluster.md
> +kubeconfig of the cluster to `~/.mke/<cluster name>.kubeconfig`, from where you
Done.

2024-06-06 16:54 UTC, KoryKessel-Mirantis commented on content/docs/setup/getting-started/installation.md
> +### Init
Created a **Dependencies** section to go at the top of the topic.

2024-06-07 16:59 UTC, ry4nz commented on content/docs/reference/known-issuees.md
> +MKE 4 Alpha.1 known issues with available workarounds include:
```suggestion
MKE 4.0.0-alpha.1.0 known issues with available workarounds include:
```

2024-06-07 17:01 UTC, ry4nz commented on content/docs/reference/known-issuees.md
> +MKE 4 Alpha.1 known issues with available workarounds include:
Actually I don' t now why "known-issues" is in this PR

2024-06-07 17:06 UTC, ry4nz commented on content/docs/setup/getting-started/install-mke4-cli.md
> +[Releases](https://github.com/MirantisContainers/mke/releases) page. Envisioned
This won't be accessible by customers.  Please update using S3 bucket.

2024-06-07 17:07 UTC, ry4nz commented on content/docs/setup/getting-started/install-mke4-cli.md
> +         Version: v4.0.0-alpha.0.3
```suggestion
         Version: v4.0.0-alpha.1.0
```

2024-06-07 17:41 UTC, sakshisharma84 commented on content/docs/setup/getting-started/install-mke4-cli.md
> +[Releases](https://github.com/MirantisContainers/mke/releases) page. Envisioned
Here is the link to the latest mke4 release in s3 bucket. [https://s3.us-east-2.amazonaws.com/packages-stage-mirantis.com/v4.0.0-alpha1.0](https://s3.us-east-2.amazonaws.com/packages-stage-mirantis.com/v4.0.0-alpha1.0/mke_linux_amd64_v1/mkectl)

2024-06-10 16:58 UTC, nwneisen approved these changes
A few comments but looks good overall

2024-06-10 16:58 UTC, nwneisen commented on content/docs/setup/getting-started/installation.md
> +Refer to [Install the MKE 4 CLI](install-mke4-cli) for detailed information.
Let's go for consistency with files within the repo and use `./install-mke4-cli.md`

2024-06-10 16:58 UTC, nwneisen commented on content/docs/setup/getting-started/installation.md
> +## Installation
IMO we should use "Creating a cluster" instead of "installation". I feel that install could get confused with the installation of the cli tool.

2024-06-10 16:58 UTC, nwneisen commented on content/docs/setup/getting-started/installation.md
> +<summary>Example: A ready-to-deploy MKE 4 config file</summary>
We might want to consider not having a default example in the docs since it is the output of `mkectl init` and it will be changing frequently for a while.

2024-06-10 16:58 UTC, nwneisen commented on content/docs/setup/getting-started/installation.md
> +Refer to [Install the MKE 4 CLI](install-mke4-cli) for detailed information.
We could also get the permalinks for these files from github so that this passes and we know it will work. We can switch it once the actual docs website is being published.

2024-06-10 17:50 UTC, ry4nz commented on content/docs/setup/getting-started/install-mke4-cli.md
> +bucket](https://s3.us-east-2.amazonaws.com/packages-stage-mirantis.com/v4.0.0-alpha1.0).
List all images for now:

uploaded - v4.0.0-alpha1.0/mkectl_linux_x86_64.tar.gz
located - https://s3.us-east-2.amazonaws.com/packages-stage-mirantis.com/v4.0.0-alpha1.0/mkectl_linux_x86_64.tar.gz
uploaded - v4.0.0-alpha1.0/mkectl_darwin_arm64.tar.gz
located - https://s3.us-east-2.amazonaws.com/packages-stage-mirantis.com/v4.0.0-alpha1.0/mkectl_darwin_arm64.tar.gz
uploaded - v4.0.0-alpha1.0/mkectl_darwin_x86_64.tar.gz
located - https://s3.us-east-2.amazonaws.com/packages-stage-mirantis.com/v4.0.0-alpha1.0/mkectl_darwin_x86_64.tar.gz
uploaded - v4.0.0-alpha1.0/mkectl_windows_x86_64.zip
located - https://s3.us-east-2.amazonaws.com/packages-stage-mirantis.com/v4.0.0-alpha1.0/mkectl_windows_x86_64.zip
uploaded - v4.0.0-alpha1.0/mkectl_windows_arm64.zip
located - https://s3.us-east-2.amazonaws.com/packages-stage-mirantis.com/v4.0.0-alpha1.0/mkectl_windows_arm64.zip
uploaded - v4.0.0-alpha1.0/mkectl_linux_arm64.tar.gz
located - https://s3.us-east-2.amazonaws.com/packages-stage-mirantis.com/v4.0.0-alpha1.0/mkectl_linux_arm64.tar.gz

2024-06-10 18:07 UTC, ry4nz commented on content/docs/setup/getting-started/install-mke4-cli.md
> +- [Linux x86 64 image](https://s3.us-east-2.amazonaws.com/packages-stage-mirantis.com/v4.0.0-alpha1.0/mkectl_linux_x86_64.tar.gz)
```suggestion
- [Linux x86_64 image](https://s3.us-east-2.amazonaws.com/packages-stage-mirantis.com/v4.0.0-alpha1.0/mkectl_linux_x86_64.tar.gz)
```

2024-06-10 18:07 UTC, ry4nz commented on content/docs/setup/getting-started/install-mke4-cli.md
> +- [Darwin arm64 image](https://s3.us-east-2.amazonaws.com/packages-stage-mirantis.com/v4.0.0-alpha1.0/mkectl_darwin_arm64.tar.gz)
```suggestion
- [MacOS arm64 image](https://s3.us-east-2.amazonaws.com/packages-stage-mirantis.com/v4.0.0-alpha1.0/mkectl_darwin_arm64.tar.gz)
```

2024-06-10 18:08 UTC, ry4nz commented on content/docs/setup/getting-started/install-mke4-cli.md
> +- [Darwin x86 64 image](https://s3.us-east-2.amazonaws.com/packages-stage-mirantis.com/v4.0.0-alpha1.0/mkectl_darwin_x86_64.tar.gz)
```suggestion
- [MacOS x86_64 image](https://s3.us-east-2.amazonaws.com/packages-stage-mirantis.com/v4.0.0-alpha1.0/mkectl_darwin_x86_64.tar.gz)
```

2024-06-10 18:08 UTC, ry4nz commented on content/docs/setup/getting-started/install-mke4-cli.md
> +- [Windows x86 64 image](https://s3.us-east-2.amazonaws.com/packages-stage-mirantis.com/v4.0.0-alpha1.0/mkectl_windows_x86_64.zip)
```suggestion
- [Windows x86_64 image](https://s3.us-east-2.amazonaws.com/packages-stage-mirantis.com/v4.0.0-alpha1.0/mkectl_windows_x86_64.zip)
```

2024-06-10 18:10 UTC, ry4nz approved these changes

2024-06-11 07:52 UTC, MagdaDziadosz requested changes

2024-06-11 07:52 UTC, MagdaDziadosz commented on content/docs/setup/getting-started/create-a-cluster.md
> +is normally located at `~/.kube/config`. If the default kubeconfig is changed,
```suggestion
is located at `~/.kube/config`. If the default kubeconfig is changed,
```

2024-06-11 07:52 UTC, MagdaDziadosz commented on content/docs/setup/getting-started/install-mke4-cli.md
> +additional dependencies, as of `MKE 4.0.0-alpha.1.0` the MKE CLI still requires
```suggestion
additional dependencies, the MKE 4 CLI requires
```
I suggest not using the release name if we can avoid it, you will have to change it at every release if there is a change in the requirements.

2024-06-11 07:52 UTC, MagdaDziadosz commented on content/docs/setup/getting-started/install-mke4-cli.md
> +>The `install.sh` script detects whether kubectl is already installed on your
```suggestion
>The `install.sh` script detects whether `kubectl` is already installed on your
```

2024-06-11 07:52 UTC, MagdaDziadosz commented on content/docs/setup/getting-started/install-mke4-cli.md
> +3. Confirm the installations:
```suggestion
2. Confirm installations:
```

2024-06-11 07:52 UTC, MagdaDziadosz commented on content/docs/setup/getting-started/install-mke4-cli.md
> +1. Install the dependencies:
```suggestion
1. Install dependencies:
```

2024-06-11 07:52 UTC, MagdaDziadosz commented on content/docs/setup/getting-started/install-mke4-cli.md
> +   1. To confirm `mkectl`, run:
-  1. will not be 1. in the output. The output will show roman numbers in lower case: i, ii, iii... I suggest changing it to a), b) or tabs.
- Add empty lines between points and before and after every code example.

2024-06-11 07:52 UTC, MagdaDziadosz commented on content/docs/setup/getting-started/install-mke4-cli.md
> +   3. To confirm kubectl, run:
```suggestion
   3. To confirm `kubectl`, run:
   
```

2024-06-11 07:52 UTC, MagdaDziadosz commented on content/docs/setup/getting-started/install-mke4-cli.md
> +       ```
```suggestion
      ```shell
      Version: v4.0.0-alpha.1.0
      ```
```

2024-06-11 07:52 UTC, MagdaDziadosz commented on content/docs/setup/getting-started/install-mke4-cli.md
> +       ```
```suggestion
       ```shell
       k0sctl version
       ```
```

2024-06-11 07:52 UTC, MagdaDziadosz commented on content/docs/setup/getting-started/install-mke4-cli.md
> +       ```
```suggestion
      ```shell
      version: v0.17.8
      commit: b061291
      ```
```

2024-06-11 07:52 UTC, MagdaDziadosz commented on content/docs/setup/getting-started/install-mke4-cli.md
> +       ```
```suggestion
      ```shell
      Client Version: v1.30.0
      Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
      Server Version: v1.29.3+k0s
      ```
```

2024-06-11 07:52 UTC, MagdaDziadosz commented on content/docs/setup/getting-started/install-mke4-cli.md
> +       ```
```suggestion
       ```shell
       kubectl version
       ```
```

2024-06-11 07:52 UTC, MagdaDziadosz commented on content/docs/setup/getting-started/install-mke4-cli.md
> +```
```suggestion
### Start debug mode

To turn the debug mode on, run:

```shell
sudo DEBUG=true /bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/Mirantis/mke-docs/main/content/docs/setup/install.sh)"
```
```

2024-06-11 07:52 UTC, MagdaDziadosz commented on content/docs/setup/getting-started/install-mke4-cli.md
> +```shell
```suggestion
Example:

```shell
```

2024-06-11 07:52 UTC, MagdaDziadosz commented on content/docs/setup/getting-started/install-mke4-cli.md
> +```shell
```suggestion
Example output:

```shell
```

2024-06-11 07:52 UTC, MagdaDziadosz commented on content/docs/setup/getting-started/k0s-in-aws/terraform-scenario.md
> +**Scenario**: Create a k0s cluster in AWS using Terraform and install MKE 4 on that cluster.
```suggestion
# Scenario: Create a k0s cluster in AWS using Terraform and install MKE 4 on that cluster
```

2024-06-11 07:52 UTC, MagdaDziadosz commented on content/docs/setup/getting-started/k0s-in-aws/terraform-scenario.md
> +### Prerequisites
```suggestion
## Prerequisites
```

2024-06-11 07:52 UTC, MagdaDziadosz commented on content/docs/setup/getting-started/k0s-in-aws/terraform-scenario.md
> +### Create virtual machines on AWS
```suggestion
## Create virtual machines on AWS
```

2024-06-11 07:52 UTC, MagdaDziadosz commented on content/docs/setup/getting-started/k0s-in-aws/terraform-scenario.md
> +### Install MKE4 on `k0s`
```suggestion
## Install MKE4 on `k0s`
```

2024-06-11 07:52 UTC, MagdaDziadosz commented on content/docs/setup/getting-started/k0s-in-aws/terraform-scenario.md
> +### Cleanup
```suggestion
## Cleanup
```

2024-06-11 07:52 UTC, MagdaDziadosz commented on content/docs/setup/getting-started/k0s-in-aws/terraform-scenario.md
> +you must have the following componenets installed:
```suggestion
you must have the following components installed:
```

2024-06-11 07:52 UTC, MagdaDziadosz commented on content/docs/setup/getting-started/k0s-in-aws/terraform-scenario.md
> +1. Copy the example Terraform folder to your local machine,
```suggestion
1. Copy the [example Terraform folder](./terraform/) to your local machine.
```
I suggest putting link in the point where user must do something with it.

2024-06-11 07:52 UTC, MagdaDziadosz commented on content/docs/setup/getting-started/k0s-in-aws/terraform-scenario.md
> +[example Terraform scripts](./terraform/):
```suggestion
example Terraform scripts:
```

2024-06-11 07:52 UTC, MagdaDziadosz commented on content/docs/setup/getting-started/k0s-in-aws/terraform-scenario.md
> +   ```
```suggestion
2. Create a `terraform.tfvars` file with content similar to:

   ```
```

2024-06-11 07:52 UTC, MagdaDziadosz commented on content/docs/setup/getting-started/k0s-in-aws/terraform-scenario.md
> +> ```
```suggestion
> To get detailed information on the VMs using the AWS CLI, run:
>
> ```
```

2024-06-11 07:52 UTC, MagdaDziadosz commented on content/docs/setup/getting-started/k0s-in-aws/terraform-scenario.md
> +3. Run `terraform init`.
Add empty line above

2024-06-11 07:52 UTC, MagdaDziadosz commented on content/docs/setup/getting-started/k0s-in-aws/terraform-scenario.md
> +* env variables, set for AWS CLI:
```suggestion
- [Terraform](https://developer.hashicorp.com/terraform/tutorials/aws-get-started/install-cli)
  (required for creating VMs in AWS)
- AWS account
- env variables, set for AWS CLI:
```

2024-06-11 07:52 UTC, MagdaDziadosz commented on content/docs/setup/getting-started/prerequisites.md
> +### Known limitations
```suggestion
## Known limitations
```

2024-06-11 07:52 UTC, MagdaDziadosz commented on content/docs/setup/getting-started/prerequisites.md
> +
This section could use an intro.

2024-06-11 07:52 UTC, MagdaDziadosz commented on content/docs/setup/getting-started/prerequisites.md
> +#### Operating systems
```suggestion
### Operating systems
```

2024-06-11 07:52 UTC, MagdaDziadosz commented on content/docs/setup/getting-started/prerequisites.md
> +#### Architecture
```suggestion
### Architecture
```

2024-06-11 07:52 UTC, MagdaDziadosz commented on content/docs/setup/getting-started/prerequisites.md
> +#### CNI
```suggestion
### CNI
```

2024-06-11 07:52 UTC, MagdaDziadosz commented on content/docs/setup/getting-started/prerequisites.md
> +#### mkectl
```suggestion
### mkectl
```

2024-06-11 07:52 UTC, MagdaDziadosz commented on content/docs/setup/getting-started/prerequisites.md
> +## Prerequisites
```suggestion
# Prerequisites
```

2024-06-11 07:52 UTC, MagdaDziadosz commented on content/docs/setup/getting-started/prerequisites.md
> +### System requirements for cluster nodes
```suggestion
## System requirements for cluster nodes
```

2024-06-11 07:52 UTC, MagdaDziadosz commented on content/docs/setup/getting-started/prerequisites.md
> +* Ubuntu 20.04 Linux
```suggestion
- Ubuntu 22.04 Linux
- Ubuntu 20.04 Linux
```

2024-06-11 07:52 UTC, MagdaDziadosz commented on content/docs/setup/getting-started/prerequisites.md
> +`calico` is the only CNI plugin that MKE 4 supports.
```suggestion
MKE 4 only supports `calico` CNI plugin.
```

2024-06-11 07:52 UTC, MagdaDziadosz commented on content/docs/setup/getting-started/uninstallation.md
> +## Uninstallation
```suggestion
# Uninstallation
```

2024-06-11 07:52 UTC, MagdaDziadosz commented on content/docs/setup/upgrade-from-mke-3/perform-upgrade.md
> +- Run pre-upgrade checks, to verify the upgradability of the cluster.
```suggestion
- Run pre-upgrade checks to verify the upgradability of the cluster.
```

2024-06-11 07:52 UTC, MagdaDziadosz commented on content/docs/setup/upgrade-from-mke-3/perform-upgrade.md
> +- Carry out pre-upgrade migrations, to prepare the cluster for a migration from
```suggestion
- Carry out pre-upgrade migrations to prepare the cluster for a migration from
```

2024-06-11 07:52 UTC, MagdaDziadosz commented on content/docs/setup/upgrade-from-mke-3/perform-upgrade.md
> +- Carry out post-upgrade cleanup, to remove MKE 3 components.
```suggestion
- Carry out post-upgrade cleanup to remove MKE 3 components.
```

2024-06-11 07:52 UTC, MagdaDziadosz commented on content/docs/setup/upgrade-from-mke-3/perform-upgrade.md
> +## Perform the Upgrade
```suggestion
# Perform upgrade
```

2024-06-11 07:52 UTC, MagdaDziadosz commented on content/docs/setup/upgrade-from-mke-3/perform-upgrade.md
> +are performed through the use of the `mkectl` tool:
Add empty line

2024-06-11 07:52 UTC, MagdaDziadosz commented on content/docs/setup/upgrade-from-mke-3/perform-upgrade.md
> +```
Add empty line after code sample

2024-06-11 07:52 UTC, MagdaDziadosz commented on content/docs/setup/upgrade-from-mke-3/perform-upgrade.md
> +>The MKE 3 cluster will no longer be accessible by way of the previously
```suggestion
>The MKE 3 cluster will no longer be accessible through the previously
```

2024-06-11 07:52 UTC, MagdaDziadosz commented on content/docs/setup/upgrade-from-mke-3/upgrade-prerequisites.md
> +## Prerequisites
```suggestion
# Upgrade prerequisites
```

2024-06-11 07:52 UTC, MagdaDziadosz commented on content/docs/setup/upgrade-from-mke-3/upgrade-prerequisites.md
> +Verify that you have the following components in place before you begin the upgrade process:
```suggestion
Verify that you have the following components in place before you begin the MKE 3 to MKE 4 upgrade process:
```

2024-06-11 07:52 UTC, MagdaDziadosz commented on content/docs/setup/upgrade-from-mke-3/upgrade-prerequisites.md
> +  ```
Add empty line between code samples

2024-06-11 07:52 UTC, MagdaDziadosz commented on content/docs/setup/upgrade-from-mke-3/upgrade-prerequisites.md
> +  ```
Add empty line after the code sample

2024-06-11 07:52 UTC, MagdaDziadosz commented on content/docs/setup/upgrade-from-mke-3/upgrade-prerequisites.md
> +  connect to each node by way of SSH.
```suggestion
  connect to each node with SSH.
```

2024-06-11 13:45 UTC, merged