Update Dashboard content from old PR.
Mirantis/mke-docs pull request #162
Opened 2024-10-28 17:13 UTC by KoryKessel-Mirantis

2024-10-28 17:22 UTC, brianbancroft approved these changes
I have one small comment which you can ignore if you wish. Otherwise, is accurate and looks good to me.

2024-10-28 17:22 UTC, brianbancroft commented on content/docs/configuration/dashboard.md
> +The MKE Dashboard add-on provides a web UI with which you can manage
Re "with which you can manage". You're def the lead on docs, but I'm a fan of a more authoritative tone as it requires less words :)

2024-10-28 18:07 UTC, KoryKessel-Mirantis commented on content/docs/configuration/dashboard.md
> +The MKE Dashboard add-on provides a web UI with which you can manage
Changed to "that you can use to manage". :-)

2024-10-29 07:00 UTC, MagdaDziadosz requested changes

2024-10-29 07:00 UTC, MagdaDziadosz commented on content/docs/configuration/dashboard.md
> +in the `dashboard` section of the `config.yaml` file:
```suggestion
in the `dashboard` section of the MKE configuration file:
```

2024-10-29 10:43 UTC, MagdaDziadosz approved these changes

2024-10-29 10:51 UTC, merged