Metallb edits structure make ready
Mirantis/mke-docs pull request #165
Opened 2024-10-29 00:16 UTC by KoryKessel-Mirantis

2024-10-29 17:39 UTC, sakshisharma84 commented on content/docs/configuration/metallb/_index.md
> +
Add a callout: FRR mode is disabled by default.

2024-10-29 18:49 UTC, sakshisharma84 approved these changes
lgtm!

2024-10-29 20:11 UTC, quadespresso requested changes

2024-10-29 20:11 UTC, quadespresso commented on content/docs/configuration/metallb/_index.md
> + namespace: metallb-system
Please change the indent from 1 space to 2 spaces, ie,

```yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: example1
  namespace: metallb-system
spec:
  addresses:
  - 192.168.10.0/24
  - 192.168.1.0/24
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: example2
  namespace: metallb-system
spec:
  addresses:
  - 192.155.10.0/24
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty
  namespace: metallb-system
```

2024-10-29 22:02 UTC, quadespresso requested changes

2024-10-29 22:02 UTC, quadespresso commented on content/docs/configuration/metallb/_index.md
> +| chart.values.<br>controller.tolerations | Tolerations for the<br>MetalLB controller pod.             | YAML: <br><br> - key: node-role.kubernetes.io/master<br>   &nbsp; operator: Exists <br>  &nbsp
Unify into a single string, and add backticks: `chart.values.controller.tolerations`

2024-10-29 22:02 UTC, quadespresso commented on content/docs/configuration/metallb/_index.md
> +| chart.values.<br>speaker.frr.enabled    | Enablement state of FRR<br>with regard to MetalLB speaker. | false                                                                                     |
Unify into a single string and add backticks: `chart.values.speaker.frr.enabled`

and add backticks: `false`

2024-10-29 22:30 UTC, KoryKessel-Mirantis commented on content/docs/configuration/metallb/_index.md
> + namespace: metallb-system
Done.

2024-10-29 23:08 UTC, quadespresso approved these changes

2024-10-30 07:33 UTC, MagdaDziadosz requested changes

2024-10-30 07:33 UTC, MagdaDziadosz commented on content/docs/configuration/metallb/_index.md
> +- `kube-proxy` running in `iptables` mode.
```suggestion
- A `kube-proxy` component running in `iptables` mode.
```

Listed as component in the official doc: https://kubernetes.io/docs/concepts/overview/components/#node-components

2024-10-30 07:33 UTC, MagdaDziadosz commented on content/docs/configuration/metallb/_index.md
> +You configure MetalLB through the `Addons` section of the MKE 4 configuration
```suggestion
You can configure MetalLB through the `Addons` section of the MKE 4 configuration
```

2024-10-30 07:33 UTC, MagdaDziadosz commented on content/docs/configuration/metallb/_index.md
> +1. Obtain the default configuration file.
```suggestion
1. Obtain the default configuration file:
```

2024-10-30 07:33 UTC, MagdaDziadosz commented on content/docs/configuration/metallb/_index.md
> +  <callout type="info"> Support for IP address pool configuration is deprecated in MKE 4, and thus you must now independently manage the configuration. </callout>
```suggestion
  <callout type="info"> Support for IP address pool configuration is deprecated in MKE 4, and thus you must now manage the configuration independently. </callout>
```

Check if the note is wrapped in the output, if not, divide it between two lines.

2024-10-30 07:33 UTC, MagdaDziadosz commented on content/docs/configuration/metallb/_index.md
> +Refer to the upgrade summary for guidance in the creation of IP address pools. To create the pools, you can use the template that follows or consult the official MetalLB documentation [Layer 2 config
```suggestion
Refer to the upgrade summary for guidance in the creation of IP address pools. To create the pools,
you can use the template that follows or consult the official MetalLB documentation
[Layer 2 configuration](https://metallb.universe.tf/configuration/#layer-2-configuration) for assistance.
```

2024-10-30 07:33 UTC, MagdaDziadosz commented on content/docs/configuration/metallb/_index.md
> +   The example that follows presents the MetalLB configuration section as it is used to deploy MetalLB as a Helm chart within the cluster:
```suggestion
   The following example presents the MetalLB configuration section used to deploy MetalLB as a Helm chart within the cluster:
```

2024-10-30 07:33 UTC, MagdaDziadosz commented on content/docs/configuration/metallb/_index.md
> +  For information on how to create IP address pools, refer to the official MetalLB documentation, [Layer 2 configuration](https://metallb.universe.tf/configuration/#layer-2-configuration).
```suggestion
  For information on how to create IP address pools, refer to the official MetalLB documentation,
  [Layer 2 configuration](https://metallb.universe.tf/configuration/#layer-2-configuration).
```

2024-10-30 10:01 UTC, KoryKessel-Mirantis commented on content/docs/configuration/metallb/_index.md
> +- `kube-proxy` running in `iptables` mode.
Yes, kube-proxy is a Kubernetes component, but drawing it out as such reads _awkward_. I would go with 'instance' before 'component'. That said, though, it does bring up a question. @sakshisharma84, should be saying "A kube-proxy instance running in `iptables` mode on each cluster node."?

2024-10-30 10:10 UTC, KoryKessel-Mirantis commented on content/docs/configuration/metallb/_index.md
> +   The example that follows presents the MetalLB configuration section as it is used to deploy MetalLB as a Helm chart within the cluster:
The edit changes the emphasis of the sentence.

2024-10-30 11:04 UTC, KoryKessel-Mirantis commented on content/docs/configuration/metallb/_index.md
> +1. Obtain the default configuration file:
```suggestion
1. Obtain the default MKE configuration file:
```

2024-10-30 11:05 UTC, KoryKessel-Mirantis commented on content/docs/configuration/metallb/_index.md
> +MetalLB is configured through the `Addons` section of the MKE 4 configuration
```suggestion
MetalLB is configured through the `addons` section of the MKE 4 configuration
```

2024-10-30 11:53 UTC, MagdaDziadosz approved these changes

2024-10-30 13:18 UTC, merged