[DOC] Authentication section update
Mirantis/mke-docs pull request #17
Opened 2024-05-29 14:57 UTC by MagdaDziadosz

Update of the authentication section

2024-06-06 15:07 UTC, ry4nz commented on content/docs/reference/authentication/authentication.md
> +# Authentication
Add a link to https://github.com/Mirantis/mke-docs/blob/main/content/releases/README.md

2024-06-10 15:30 UTC, nwneisen commented on content/docs/reference/authentication/authentication.md
> +***Caution: Changing authentication method***
This should say "disabling" instead of "changing". Users will already have to configure authentication themselves, we just have tooling to make it easier.

If they disable the authentication section, then they are removing everything completely including our tooling and they will be responsible for 100% of the authentication

2024-06-10 15:32 UTC, KoryKessel-Mirantis requested changes

2024-06-10 15:32 UTC, KoryKessel-Mirantis commented on content/docs/reference/authentication/authentication.md
> +Changing the authentication method will require you to configure
Suggest editing to read (and it is extra wordy on purpose, as that tends to add to the *fear* factor):

"Be aware that if you opt to use an authentication method other than dex, you will need to undertake all tasks and responsibilities associated with configuring and maintaining that method."

2024-06-10 15:32 UTC, KoryKessel-Mirantis commented on content/docs/reference/authentication/authentication.md
> +For more information on authentication feature status in the release, go to
```suggestion
For more information on authentication feature status per release, go to
```

2024-06-10 15:32 UTC, KoryKessel-Mirantis commented on content/docs/reference/authentication/authentication.md
> +- Identity Provider (IdP) - To set OIDC or SAML you need to configure an IdP with an application.
Suggest:

- Identity Provider (IdP)

(text to run underneath the bullet, before the next bullet): To set OIDC or SAML, you must configure an IdP with an application.

2024-06-10 15:32 UTC, KoryKessel-Mirantis commented on content/docs/reference/authentication/authentication.md
> +Refer to [Add a SAML Identity Provider](https://help.okta.com/en-us/content/topics/security/idp-add-saml.htm)
```suggestion
Refer to the official Okta documentation tutorial [Add a SAML Identity Provider](https://help.okta.com/en-us/content/topics/security/idp-add-saml.htm).
```

2024-06-10 15:32 UTC, KoryKessel-Mirantis commented on content/docs/reference/authentication/authentication.md
> +- LDAP Server - To set LDAP you need to configure an LDAP server with a user.
Suggest:

- LDAP Server

(text to run underneath the bullet, before the next bullet): To set LDAP, you must configure an LDAP server with a user.

2024-06-10 15:32 UTC, KoryKessel-Mirantis commented on content/docs/reference/authentication/authentication.md
> +Authentication can be configured in the `authentication` section of the MKE 4 config.
Suggest:

You can configure authentication for MKE 4 through the 'authentication' section of the MKE configuration file. `authentication` is enabled by default, however the settings for each of the individual authentication methods are disabled. To enable a service, set its 'enabled' configuration option to 'true'.

2024-06-10 15:32 UTC, KoryKessel-Mirantis commented on content/docs/reference/authentication/authentication.md
> +This will completely remove any authentication-related components from being
Suggest:

"Doing so will completely remove any authentication-related components from being installed on your cluster."

2024-06-10 15:32 UTC, KoryKessel-Mirantis commented on content/docs/reference/authentication/authentication.md
> +To learn more, refer to the documentation on specific authentication methods:
```suggestion
Documentation for specific authentication methods as they apply to MKE 4 is available:
```

2024-06-10 15:32 UTC, KoryKessel-Mirantis commented on content/docs/reference/authentication/authentication.md
> +- [OpenID Connect (OIDC)](OIDC.md)
```suggestion
- [OIDC (OpenID Connect)](OIDC.md)
```

2024-06-10 15:32 UTC, KoryKessel-Mirantis commented on content/docs/reference/authentication/authentication.md
> +- [Security Assertion Markup Language (SAML)](SAML.md)
```suggestion
- [SAML (Security Assertion Markup Language)](SAML.md)
```

2024-06-10 15:32 UTC, KoryKessel-Mirantis commented on content/docs/reference/authentication/authentication.md
> +- [Lightweight Directory Access Protocol (LDAP)](LDAP.md)
```suggestion
- [LDAP (Lightweight Directory Access Protocol)](LDAP.md)
```

2024-06-11 14:59 UTC, nwneisen commented on content/docs/reference/authentication/LDAP.md
> +**To test the Authentication flow:**
This should be a heading section not bold text

2024-06-11 14:59 UTC, nwneisen commented on content/docs/reference/authentication/OIDC.md
> +For information on how to obtain the field values, refer to
This would then say "For information on how to obtain the field values, refer to the section for your provider of choice: link"

2024-06-11 14:59 UTC, nwneisen commented on content/docs/reference/authentication/OIDC.md
> +**To create a new application in Okta:**
This should be a heading not just bold

2024-06-13 19:39 UTC, ry4nz commented on content/docs/reference/authentication/LDAP.md
> +## Test authentication flow
What's the reason for adding "Test"?

2024-06-14 08:18 UTC, MagdaDziadosz commented on content/docs/reference/authentication/LDAP.md
> +## Test authentication flow
@ry4nz It's for consistency. If the user looks at headings, they will see:

<img width="277" alt="image" src="https://github.com/Mirantis/mke-docs/assets/160592158/299f4b4d-f9a3-49aa-a632-e3c6349db7a5">
  
All lower headings describe an action and explain what the user will do in a specific section, first they configure MKE then they test if everything works.

2024-06-14 08:40 UTC, KoryKessel-Mirantis requested changes

2024-06-14 08:40 UTC, KoryKessel-Mirantis commented on content/docs/reference/authentication/authentication.md
> +Doing so will install authentication method of your choice on your cluster.
Tap 'the' 'will' and 'install'.

2024-06-14 09:05 UTC, KoryKessel-Mirantis approved these changes

2024-06-14 09:05 UTC, merged