RBAC docs #160
Mirantis/mke-docs pull request #177
Opened 2024-11-07 15:03 UTC by MagdaDziadosz

2024-11-07 15:54 UTC, nwneisen commented on content/docs/migrate-from-MKE-3.md
> +├── entireCompany:org (AggregatedRole)
The `:` should be `-` in these names. I originally tried to use `:` but it broke some k8s naming conventions and I had to switch them.

We may want to specifically point out that what used to be an org or a team will now have `-org` or `-team` appended to the name.

2024-11-07 15:54 UTC, nwneisen commented on content/docs/migrate-from-MKE-3.md
> +In the example above, the binding grants ``edit`` permissions only to the
This description doesn't match the example structure above. It looks like the previous one might've been copied instead

2024-11-07 15:54 UTC, nwneisen commented on content/docs/migrate-from-MKE-3.md
> +Swarm roles do not directly translate to Kubernetes roles. During migration,
I updated the issue after talking to you yesterday. The roles are actually created but without any permissions. The none role is used if a team had no roles previously as k8s requires an aggregated role to have atleast one role. This `none` role has no permissions and is still a placeholder to maintain the structure.

2024-11-07 15:54 UTC, nwneisen commented on content/docs/migrate-from-MKE-3.md
> +**Example company binding:**
company -> org or organization

I'm doing more RBAC testing today and I'll see if I can get you some example bindings

2024-11-07 15:54 UTC, nwneisen commented on content/docs/migrate-from-MKE-3.md
> +### Fresh cluster RBAC
We might want to say something about using vanilla RBAC in the overall RBAC description since a migrated cluster will be using it also. The fresh install section should be removed from here because this page is for migration information. I think an RBAC section should be added in the overall configs that just says we are using vanilla k8s RBAC and point users to the k8s docs

2024-11-07 15:54 UTC, nwneisen commented on content/docs/migrate-from-MKE-3.md
> +authorization. Thus, the RBAC configuration for Swarm mode does not exist in
nit: using `authorization` instead of `RBAC` to eliminate acronyms.

2024-11-07 18:59 UTC, nwneisen commented on content/docs/migrate-from-MKE-3.md
> +├── entireCompany (org)
Probably change this to `entire-company`. You can't use capital letters for orgs in mke3

2024-11-07 19:01 UTC, MagdaDziadosz commented on content/docs/migrate-from-MKE-3.md
> +In the example above, the binding grants ``edit`` permissions only to the
Fixed

2024-11-07 19:07 UTC, nwneisen commented on content/docs/migrate-from-MKE-3.md
> +├── entireCompany-org (AggregatedRole)
The other ones too

entireCompany -> entire-company

2024-11-07 19:10 UTC, nwneisen commented on content/docs/migrate-from-MKE-3.md
> +The ``none`` roles have no permissions and are only used to maintain the
Slight wording change.

There is only one `none` role. It is referenced in multiple places but it is only defined once

2024-11-12 15:50 UTC, KoryKessel-Mirantis requested changes

2024-11-12 16:01 UTC, nwneisen approved these changes

2024-11-13 07:27 UTC, MagdaDziadosz commented on content/docs/migrate-from-MKE-3.md
> +[Using RBAC Authorization](https://kubernetes.io/docs/reference/access-authn-authz/rbac/).
```suggestion
```

2024-11-13 10:48 UTC, KoryKessel-Mirantis approved these changes

2024-11-13 10:49 UTC, merged