Added Licensing documentation
Mirantis/mke-docs pull request #179
Opened 2024-11-07 18:26 UTC by MagdaDziadosz

2024-11-13 12:43 UTC, KoryKessel-Mirantis requested changes
See about getting an updated screenshot that also contains the **Save settings** button.

2024-11-13 12:43 UTC, KoryKessel-Mirantis commented on content/docs/getting-started/obtain-license.md
> +   your Designated Administrator.
```suggestion
1. Locate the _Welcome to Mirantis' CloudCare Portal _email sent to you from Mirantis
Support. If you do not have the email, confirm with your Designated Administrator
that you have added as a Designated Contact.
```

2024-11-13 12:43 UTC, KoryKessel-Mirantis commented on content/docs/getting-started/obtain-license.md
> +3. In the top navigation bar, click **Environments**.
```suggestion
2. Click **Environments** in the top navigation bar of the MKE web UI.
```

2024-11-13 12:43 UTC, KoryKessel-Mirantis commented on content/docs/getting-started/obtain-license.md
> +4. Click the **Cloud Name** associated with the license you want to download.
```suggestion
3. Click the **Cloud Name** that is associated with the license you want to download.
```

2024-11-13 12:43 UTC, KoryKessel-Mirantis commented on content/docs/getting-started/obtain-license.md
> +   A new tab opens in your browser.
Is it a new tab that opens? Or a dialog window? Also, what is the name of the tab/window? Assuming it has a name of some sort, the sentence should read "The <name-of> tab/dialog will open."

2024-11-13 12:43 UTC, KoryKessel-Mirantis commented on content/docs/getting-started/obtain-license.md
> +to request a free trial license.
```suggestion
Though MKE4 is generally a subscription-only service, you can obtain a free trial license from Mirantis. Make your request using the [Mirantis contact form](https://www.mirantis.com/contact).
```

2024-11-13 12:43 UTC, KoryKessel-Mirantis commented on content/docs/getting-started/obtain-license.md
> +## Set the license in MKE web UI
```suggestion
## Set the license
```

2024-11-13 12:43 UTC, KoryKessel-Mirantis commented on content/docs/getting-started/obtain-license.md
> +title: Obtain the license
```suggestion
title: Licensing MKE4
```

2024-11-13 12:43 UTC, KoryKessel-Mirantis commented on content/docs/getting-started/obtain-license.md
> +## Set the license in MKE web UI
To keep it simple, we should refer to the environment for each licensing step at the start of the sections and not in the headings.

2024-11-13 12:43 UTC, KoryKessel-Mirantis commented on content/docs/getting-started/obtain-license.md
> +1. Log in to your MKE instance using an administrator account.
```suggestion
1. Log in to the MKE web UI with an administrator account.
```

2024-11-13 12:43 UTC, KoryKessel-Mirantis commented on content/docs/getting-started/obtain-license.md
> +2. In the left panel, navigate to **Admin Settings** -> **License**.
```suggestion
2. In the left-side navigation panel, navigate to **Admin Settings** -> **License**. 
```

2024-11-13 12:43 UTC, KoryKessel-Mirantis commented on content/docs/getting-started/obtain-license.md
> +3. Paste the token as a string into a **license key** text box, or click
Token? Modal?

I suggest editing this step to read:

"Insert the license into the **license key** field. To do this,  click **Choose File** and navigate to the .lic file you previously downloaded. Alternately, you can copy-paste the contents of the .lic file into the field as a text string."

2024-11-13 12:43 UTC, KoryKessel-Mirantis commented on content/docs/getting-started/obtain-license.md
> +5. Scroll down to **License Information** and click the **License File URL**.
```suggestion
4. Scroll down to **License Information** and click the **License File URL**. 
```

2024-11-13 12:43 UTC, KoryKessel-Mirantis commented on content/docs/getting-started/obtain-license.md
> +6. Click **View file** to download your license file.
```suggestion
5. Click **View file** to download your license file.
```

2024-11-13 12:43 UTC, KoryKessel-Mirantis commented on content/docs/getting-started/obtain-license.md
> +4. Click **Save settings**. MKE will automatically update with the new settings.
```suggestion
4. Click **Save settings** to update the MKE4 license.
```

2024-11-13 12:43 UTC, KoryKessel-Mirantis commented on content/docs/getting-started/obtain-license.md
> +4. Click **Save settings**. MKE will automatically update with the new settings.
Nothing automatic about it, as the user has to click something to make it happen.

2024-11-13 12:43 UTC, KoryKessel-Mirantis commented on content/docs/getting-started/obtain-license.md
> +1. Set the license token under ``spec.license.token`` in the MKE 4
```suggestion
1. Set the license under ``spec.license.token`` in the MKE4
```

2024-11-13 12:43 UTC, KoryKessel-Mirantis commented on content/docs/getting-started/obtain-license.md
> +        token: <your-license-token>
```suggestion
        token: <your-license-file>
```

2024-11-13 12:43 UTC, KoryKessel-Mirantis commented on content/docs/getting-started/obtain-license.md
> +3. Check the license status, users can see the status of the ``mkeconfig``
```suggestion
3. Check the license status:
```

2024-11-13 13:27 UTC, KoryKessel-Mirantis requested changes

2024-11-13 13:27 UTC, KoryKessel-Mirantis commented on content/docs/getting-started/obtain-license.md
> +
```suggestion
## Obtain your MKE4 license

[Install the MKE image](install-MKE-CLI.md) prior to downloading your MKE4 license.
```

```

2024-11-13 13:27 UTC, KoryKessel-Mirantis commented on content/docs/getting-started/obtain-license.md
> +   resource:
```suggestion
3. Check the license status:
```

2024-11-14 15:27 UTC, byDimasik requested changes
Hey! Thanks for working on this! It's almost perfect, just a few comments before I approve.

2024-11-14 15:27 UTC, byDimasik commented on content/docs/getting-started/licensing-mke4.md
> +[Install the MKE image](install-MKE-CLI.md) prior to downloading your MKE4 license.
```suggestion
[Install the MKE CLI](install-MKE-CLI.md) prior to downloading your MKE4 license.
```

Using the word "Image" is not correct here, MKE CLI is a binary, not an image. The correct options would be
- mkectl binary
- MKE CLI
- MKE CLI binary

> prior to downloading your MKE4 license

Also, not sure why it has to be done prior to getting a license. Not necessarily. Users can get their license first and then proceed with installing MKE 4: getting the binary, configuring and deploying their cluster.

2024-11-14 15:27 UTC, byDimasik commented on content/docs/getting-started/licensing-mke4.md
> +5. Click **View file** to download your license file.
I don't remember seeing these steps in MKE 3 docs, so, I cannot say if this is the correct way or not. Maybe someone who is more familiar with the process of getting license should also review this.

2024-11-14 15:27 UTC, byDimasik commented on content/docs/getting-started/licensing-mke4.md
> +     "subject": "sf|0014W0000341gYFQAY|a2X4W000000ZeatUAC",
```suggestion
     "subject": "example",
```

let's not expose the ugly dev's subject.

2024-11-14 18:08 UTC, byDimasik commented on content/docs/getting-started/licensing-mke4.md
> +5. Click **View file** to download your license file.
oh I just realized that these are actually on the MKE 3 docs. I don't know how I never saw them. I thought you got it from somewhere else, but since we have it in MKE 3, and no one complained, I think we should be good

2024-11-14 18:20 UTC, byDimasik approved these changes
LGTM! Thank you!

2024-11-14 18:41 UTC, KoryKessel-Mirantis requested changes
A few small nits, and a reminder to add the new add-a-license.png screenshot.

2024-11-14 18:41 UTC, KoryKessel-Mirantis commented on content/docs/getting-started/licensing-mke4.md
> +1. Locate the Welcome to Mirantis' CloudCare Portal email sent to you from Mirantis
```suggestion
[Install the MKE CLI](install-MKE-CLI.md) prior to downloading your MKE4 license.

1. Locate the Welcome to Mirantis' CloudCare Portal email sent to you from Mirantis
```

2024-11-14 18:41 UTC, KoryKessel-Mirantis commented on content/docs/getting-started/licensing-mke4.md
> +   that you have added as a Designated Contact.
```suggestion
   Support. If you do not have the email, confirm with your Designated Administrator
   that you have been added as a Designated Contact.
```

2024-11-14 18:41 UTC, KoryKessel-Mirantis commented on content/docs/getting-started/licensing-mke4.md
> +1. Set the license under ``spec.license.token`` in the MKE4
```suggestion
1. Insert the license into ``spec.license.token`` in the MKE4
```

2024-11-15 11:34 UTC, KoryKessel-Mirantis approved these changes

2024-11-15 11:34 UTC, merged

2024-11-15 19:07 UTC, brianbancroft commented
Thank you @MagdaDziadosz!