[DOC] Edit backuprestore content initial
Mirantis/mke-docs pull request #21
Opened 2024-05-31 14:30 UTC by KoryKessel-Mirantis

Initial edit of MKE 4 backuprestore content, including text changes and content restructuring/granulation.

2024-06-03 16:38 UTC, tppolkow requested changes

2024-06-05 22:59 UTC, tppolkow approved these changes
LGTM

2024-06-06 23:25 UTC, KoryKessel-Mirantis commented on content/docs/reference/backuprestore/backup-restore.md
> +## Create backups and restores
I discussed the word 'restore' in this context with @tppolkow, and he informed me that **restore** is the name of the underlying Kubernetes object. Alongside that, I did a bit of Internet searching and found the use of **restore** as a verb in reference to software systems is quite common. So all of that said, I suggest we meet in the middle and insert **perform** but keep **restores**.

2024-06-06 23:30 UTC, KoryKessel-Mirantis commented on content/docs/reference/backuprestore/external.md
> +Example Output:
I suggest we stick with **Example output

2024-06-06 23:35 UTC, KoryKessel-Mirantis commented on content/docs/reference/backuprestore/in_cluster.md
> +>The offered instructions assume that you have created a cluster and
In my opinion, yes, this type of content should usually be set apart from the main textual flow in some manner.

2024-06-07 15:53 UTC, ogusarenko approved these changes

2024-06-07 15:57 UTC, merged