Upgrade Pre-requisite and dealing with etcdv3/kdd backend error
Mirantis/mke-docs pull request #231
Opened 2024-11-22 10:02 UTC by MagdaDziadosz

2024-11-22 20:05 UTC, moshiurH commented on content/docs/migrate-from-MKE-3.md
> +$ mkectl upgrade --hosts-path hosts.yaml --mke3-admin-username admin --mke3-admin-password orcaorcaorca -l debug --config-out new-mke4.yaml --external-address "147.75.202.233"
I am not sure what the documentation convention is but maybe we should change the password example to something more like:
--mke3-admin-password <mke_admin_password>

(put the brackets to instruct readers to insert their appropriate MKE admin password)

--external-address <mke4_external_address>

(put the brackets to instruct readers to insert their appropriate MKE 4 external address)

2024-11-22 20:07 UTC, moshiurH commented on content/docs/migrate-from-MKE-3.md
> +To resolve the issue, ensure that the ``calico_kdd`` flag in the ``toml`` flag
To resolve the issue, ensure that the ``calico_kdd`` flag in the **MKE 3 toml file** is set to ``true`` **and applied to the MKE 3 cluster**:

2024-11-22 20:08 UTC, moshiurH commented on content/docs/migrate-from-MKE-3.md
> +$ mkectl upgrade --hosts-path hosts.yaml --mke3-admin-username admin --mke3-admin-password orcaorcaorca -l debug --config-out new-mke4.yaml --external-address "147.75.202.233"
So something like:
mkectl upgrade --hosts-path hosts.yaml --mke3-admin-username admin --mke3-admin-password <mke_admin_password> -l debug --config-out new-mke4.yaml --external-address <mke4_external_address>

2024-11-22 20:37 UTC, moshiurH commented on content/docs/migrate-from-MKE-3.md
> +### Unsupported configuration for MKE4 upgrade
@MagdaDziadosz @KoryKessel-Mirantis 

I think it's perfectly fine to keep the title as is but just double checking.
Would changing it to something like this make more sense?
### MKE3 etcdv3 backend unsupported for MKE 4 upgrade 

I think this would help end users find their issues faster (the keyword etcdv3 is in the title).

2024-11-22 20:57 UTC, moshiurH commented
Can we also mention the following under the pre-requistes section?
![image](https://github.com/user-attachments/assets/39012f96-eb2b-4d0a-9026-8d8847848132)

2024-11-23 08:10 UTC, vikramhh commented
Hello,

1. We may want to capture that switch to kdd can be accomplished either in a fully automated way or manually (in case someone wants to monitor each and every step for peace of mind). Mirantis recommends automated way documented already by you but we may want to share the below steps for "manual mode"

```
The below assumes a default location of /var/lib/docker for docker root directory. In case you have a custom/non-default value for docker root directory, please adjust the paths below appropriately before proceeding.

Root access is required for the following because typically only root users have access to the docker root directory.
Before proceeding with the steps below, ensure you have a backup of the cluster in case some unexpected issue is encountered.
Do not proceed if the cluster has one or more pods pending because there are no nodes left to schedule that pod. The procedure below causes calico-node daemonset's pods to restart. At the outset of this procedure, if there are any pods in pending condition, they may get scheduled on the node when calico-node daemonset's pods are terminated and as a result, the "replacement" calico-node daemonset's pod may not get successfully scheduled on this node. 
Do not change any *other* configuration values(besides calico_kdd) when you are enabling kdd mode through toml-config. The key calico_kdd should be the only one whose state should change in the toml-config before uploading it. 
Version numbers shown below in various outputs are just for example. Anytime these instructions are followed, calicoctl used should have version that exactly matches that of calico-node [you can get this by looking at the tag of images in any calico pods such as calico-node or calico-cni or calico-kube-controllers]  

-1. Start from a cluster that is functional in every respect. We assume that in this initial state, it is possible to create k8s objects (such as pods) and have them run with no issues. 
0. Confirm that there are no existing calico CRD-s present in the cluster. This can be done like so by using kubectl: kubectl api-resources -o wide|grep projectcalico. If there are any, it is likely a leftover from an earlier attempt at migration and we need to start with a clean state by deleting such CRD - do that by using kubectl delete $(kubectl get crds -o name | grep projectcalico.org) 
1. Create a temporary directory say /calico-migration and run the following commands from that directory - mkdir -p /calico-migration && cd /calico-migration 
2. Download calicoctl using the instructions on https://docs.tigera.io/calico/latest/operations/calicoctl/install. Specifically follow the instructions in the section https://docs.tigera.io/calico/latest/operations/calicoctl/install#install-calicoctl-as-a-binary-on-a-single-host : curl -L https://github.com/projectcalico/calico/releases/download/v3.28.1/calicoctl-linux-amd64 -o calicoctl && chmod +x ./calicoctl && export PATH="`pwd`:$PATH"
3. Confirm that calico is operating in etcd mode: DATASTORE_TYPE=etcdv3 ETCD_ENDPOINTS=127.0.0.1:12378 ETCD_CA_CERT_FILE=/var/lib/docker/volumes/ucp-kv-certs/_data/ca.pem  ETCD_KEY_FILE=/var/lib/docker/volumes/ucp-kv-certs/_data/key.pem ETCD_CERT_FILE=/var/lib/docker/volumes/ucp-kv-certs/_data/cert.pem calicoctl version
4. Confirm that the above command executed without any error and that each of the below 4 keys has a value available:
Client Version:    v3.27.3
Git commit:        638464f94
Cluster Version:   v3.28.0
Cluster Type:      k8s,kubeadm

Furthermore "Cluster Type" should not include kdd. If the Client Version and Cluster Version do not match, make sure to download calicoctl with the same version as the Cluster Version (otherwise the next step will not work). 

Also confirm that in this state, trying to access the cluster 

5. Lock the datastore to prepare for migration: DATASTORE_TYPE=etcdv3 ETCD_ENDPOINTS=127.0.0.1:12378 ETCD_CA_CERT_FILE=/var/lib/docker/volumes/ucp-kv-certs/_data/ca.pem  ETCD_KEY_FILE=/var/lib/docker/volumes/ucp-kv-certs/_data/key.pem ETCD_CERT_FILE=/var/lib/docker/volumes/ucp-kv-certs/_data/cert.pem calicoctl datastore migrate lock
Confirm that the command executed without any error - and the string "Datastore locked." was displayed.

6. Export existing calico data like so: DATASTORE_TYPE=etcdv3 ETCD_ENDPOINTS=127.0.0.1:12378 ETCD_CA_CERT_FILE=/var/lib/docker/volumes/ucp-kv-certs/_data/ca.pem  ETCD_KEY_FILE=/var/lib/docker/volumes/ucp-kv-certs/_data/key.pem ETCD_CERT_FILE=/var/lib/docker/volumes/ucp-kv-certs/_data/cert.pem calicoctl datastore migrate export > `pwd`/calico-exported-data
Confirm that the command executed without any error - and the resulting file calico-exported-data is not empty. Instead it should have entries for CR-s of different Kind-s, all of them belonging to the GV projectcalico.org/v3 

7. [As a sanity check and to make sure, in case you may be re-executing this step after encountering and fixing some error message - always confirm that there are no existing calico CRD-s present in the cluster at this stage. This can be ensured by executing kubectl delete $(kubectl get crds -o name | grep projectcalico.org) followed by repeating the confirmation in Step 0 above]. Now import the data in this file to the existing k8s cluster: DATASTORE_TYPE=kubernetes CALICO_KUBECONFIG="/var/lib/docker/volumes/ucp-node-certs/_data/kubelet.conf" calicoctl datastore migrate import -f `pwd`/calico-exported-data

Confirm that the command executed without any error - here is an example output from a successful execution:

Datastore locked.
Successfully applied 5 resource(s)
Importing IPAM resources
Successfully applied 8 IPAM resource(s)
Datastore information successfully imported. Please refer to the datastore migration documentation for next steps.

8. Confirm that the expected Calico CRD-s are present in the cluster at this stage. This can be done by: exist=$(kubectl api-resources -o wide|grep projectcalico|cut -d ' ' -f1|sort|paste -s -d ',' - -) && [ $exist = "bgpconfigurations,bgppeers,blockaffinities,caliconodestatuses,clusterinformations,felixconfigurations,globalnetworkpolicies,globalnetworksets,hostendpoints,ipamblocks,ipamconfigs,ipamhandles,ippools,ipreservations,kubecontrollersconfigurations,networkpolicies,networkset" ]

9. At this stage, please ensure that calico is operating in kdd mode:  DATASTORE_TYPE=kubernetes CALICO_KUBECONFIG="/var/lib/docker/volumes/ucp-node-certs/_data/kubelet.conf" calicoctl version

Confirm that the above command executed without any error and that each of the below 4 keys has a value available:
Client Version:    v3.28.0
Git commit:        711528eeb
Cluster Version:   v3.28.0
Cluster Type:      kdd

Furthermore "Cluster Type" should be exactly kdd

10. Try to create or delete a pod at this stage and ensure that it fails to enter running state due to the CNI being locked[Calico is currently not ready to process requests]: kubectl run nginx --image=nginx --restart=Never

The below is representative the type of error you will see in events (kubectl get events)

                        
LAST SEEN   TYPE      REASON                   OBJECT      MESSAGE
38m         Normal    Scheduled                pod/nginx   Successfully assigned default/nginx to t-ubuntu-0
38m         Warning   FailedCreatePodSandBox   pod/nginx   Failed to create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "2545b5c147d5fcf1c2afd09d5f16ae643aca0f88e9d9b695681a3baee728a52c" network for pod "nginx": networkPlugin cni failed to set up pod "nginx_default" network: plugin type="calico" failed (add): Calico is currently not ready to process requests, failed to clean up sandbox container "2545b5c147d5fcf1c2afd09d5f16ae643aca0f88e9d9b695681a3baee728a52c" network for pod "nginx": networkPlugin cni failed to teardown pod "nginx_default" network: plugin type="calico" failed (delete): Calico is currently not ready to process requests]
38m         Normal    SandboxChanged       [...]

2024-11-29 16:43 UTC, moshiurH requested changes

2024-11-29 16:43 UTC, moshiurH commented on content/docs/migrate-from-MKE-3.md
> +- The configuration is applied to the MKE 3 cluster.
@MagdaDziadosz @KoryKessel-Mirantis @vikramhh  Based on Vikram's suggestions, maybe we should add a disclaimer for point 7 and 8:

> 7. We should mention that migration to kdd mode is an irreversible process once it is completed successfully
> 8. We should also mention that in case an enterprise cluster needs to be migrated, a ticket should be opened with Mirantis so that the process can be planned and monitored during execution to reduce risk

Something like: "Please note that migration to kdd mode is an irreversible process once it is completed successfully. For migrating enterprise cluster, a ticket should be opened with Mirantis so that the process can be planned and monitored during execution to reduce risk."

2024-11-29 16:49 UTC, moshiurH commented
The following two PRs work on similar stuff. Not sure how merging these two content would work...

https://github.com/Mirantis/mke-docs/pull/231
https://github.com/Mirantis/mke-docs/pull/242

2024-12-07 00:38 UTC, KoryKessel-Mirantis commented
Merged content from this PR into https://github.com/Mirantis/mke-docs/pull/242, as per @moshiurH's comments in Slack and with the help of his wildly useful art. Once that PR is merged, this one should be closed as a duplicate.

2024-12-09 20:29 UTC, KoryKessel-Mirantis commented
Closing the PR as https://github.com/Mirantis/mke-docs/pull/242 has taken precedence.

2024-12-09 20:29 UTC, closed without merging