Insert Calico KDD into the migrate topic prerequisites.
Mirantis/mke-docs pull request #242
Opened 2024-11-23 00:35 UTC by KoryKessel-Mirantis

2024-11-28 12:21 UTC, vikramhh commented
@moshiurH @rleap-m - could you please take a look in light of my comments here. I feel we need to emphasize the latest release and de-emphasize 3.7.12. Also what I found regarding the total time is approximately a node done every 10 seconds - so I feel the time value given here needs to be revised accordingly.

2024-11-29 16:29 UTC, moshiurH requested changes
One issue with the writeup, otherwise everything else looks good!

2024-11-29 16:29 UTC, moshiurH commented on content/docs/migrate-from-MKE-3.md
> +     mkectl apply  -f <mke-configuration-file>.yaml
`mkectl` commands are used to modify the MKE 4 configurations only.

To modify mke 3 configurations, we will need to perform the following bash commands to apply the new TOML configurations (which can be found in the [mke 3 documentation for working with toml](https://docs.mirantis.com/mke/3.7/ops/administer-cluster/configure-an-mke-cluster/use-an-mke-configuration-file.html)):
```bash
$ AUTHTOKEN=$(curl --silent --insecure --data '{"username":"'$MKE_USERNAME'","password":"'$MKE_PASSWORD'"}' https://$MKE_HOST/auth/login | jq --raw-output .auth_token)
$ curl --silent --insecure -X PUT -H "accept: application/toml" -H "Authorization: Bearer $AUTHTOKEN" --upload-file 'mke-config.toml' https://$MKE_HOST/api/ucp/config-toml
{"message":"Calico datastore migration from etcd to kdd successful"}
```

2024-11-29 16:44 UTC, moshiurH requested changes

2024-11-29 16:44 UTC, moshiurH commented on content/docs/migrate-from-MKE-3.md
> +{"message":"Calico datastore migration from etcd to kdd successful"}
@KoryKessel-Mirantis @rleap-m @vikramhh 
Based on Vikram's [suggestions](https://github.com/Mirantis/mke-docs/pull/231#issuecomment-2495394192), maybe we should add a disclaimer for point 7 and 8:

> 7. We should mention that migration to kdd mode is an irreversible process once it is completed successfully
> 8. We should also mention that in case an enterprise cluster needs to be migrated, a ticket should be opened with Mirantis so that the process can be planned and monitored during execution to reduce risk

Something like: "Please note that migration to kdd mode is an irreversible process once it is completed successfully. For migrating enterprise cluster, a ticket should be opened with Mirantis so that the process can be planned and monitored during execution to reduce risk."

2024-12-07 00:36 UTC, KoryKessel-Mirantis commented
@moshiurH, I performed the merging of the https://github.com/Mirantis/mke-docs/pull/231 content into this PR, as you outlined so clearly and eloquently in Slack (pretty pictures!). Please let me know if all is well or if I lost the plot.

2024-12-09 17:41 UTC, moshiurH approved these changes
~~Looks fantastic! Thank you for completing this task @KoryKessel-Mirantis!~~

Sorry for my miss but I noticed one change that was not applied, see https://github.com/Mirantis/mke-docs/pull/242#discussion_r1876482418.

2024-12-09 18:28 UTC, moshiurH requested changes

2024-12-09 18:28 UTC, moshiurH commented on content/docs/migrate-from-MKE-3.md
> +     mkectl apply  -f <mke-configuration-file>.yaml
@KoryKessel-Mirantis Sorry for my miss on this but this change is required. Please take a look.

2024-12-09 19:01 UTC, rleap-m commented on content/docs/migrate-from-MKE-3.md
>  Verify that you have the following components in place before you begin upgrading MKE3 to MKE 4:
Inconsistent spacing: `MKE3` vs `MKE 4`.

2024-12-09 19:05 UTC, rleap-m commented on content/docs/migrate-from-MKE-3.md
> +- A running MKE 3.7.x cluster running version 3.7.12 or later:
I believe @vikramhh had requested we move away from calling out the .12 version and instead word it to use the latest MKE 3.7.x or 3.8.x release.

2024-12-09 19:07 UTC, rleap-m commented on content/docs/migrate-from-MKE-3.md
> +     mkectl apply  -f <mke-configuration-file>.yaml
+1 on this - need to instruct them how to obtain and apply an MKE3 config file.

2024-12-09 19:14 UTC, KoryKessel-Mirantis commented on content/docs/migrate-from-MKE-3.md
> +- A running MKE 3.7.x cluster running version 3.7.12 or later:
@rleap-m, does this work?

"An MKE cluster running the latest 3.7.x or 3.8.x release:"

2024-12-09 19:18 UTC, rleap-m commented on content/docs/migrate-from-MKE-3.md
> +KDD may take up to 30 minutes, depending on the size of the cluster. On
@vikramhh made a comment in a related PR about 10 seconds per node.  My experience with it showed that it took a little longer (I timed it while doing performance testing with 125 nodes and it took 30 minutes).  Anyway, that's a bit longer than 10 seconds per node so perhaps just to set expectations we can say something similar to "_The conversion of the Calico datastore from etcd to KDD takes somewhere between 10 and 20 seconds per node._"

2024-12-09 20:28 UTC, KoryKessel-Mirantis commented on content/docs/migrate-from-MKE-3.md
> +KDD may take up to 30 minutes, depending on the size of the cluster. On
Changed timing clause to read, ""The conversion of the Calico datastore from etcd to KDD typically takes about 20 seconds per node, "

2024-12-09 20:38 UTC, rleap-m commented on content/docs/migrate-from-MKE-3.md
> +  2. Obtain the MKE 3 configuration file.
We provide instructions on uploading in step 4, but we missed how to obtain the config toml in step 3 - I stole this from the MKE3 docs:

```shell
$ export MKE_USERNAME=<mke-username>
$ export MKE_PASSWORD=<mke-password>
$ export MKE_HOST=<mke-fqdm-or-ip-address>
$ curl --silent --insecure -X GET "https://$MKE_HOST/api/ucp/config-toml" -H "accept: application/toml" -H "Authorization: Bearer $AUTHTOKEN" > mke-config.toml

2024-12-09 20:41 UTC, rleap-m requested changes
Needs the "latest 3.7.x or 3.8.x release" change that @KoryKessel-Mirantis suggested and instructions for obtaining the MKE config toml (only has instructions for uploading and the uploading instructions misses both the part where you set env vars and download the file first).

2024-12-09 21:26 UTC, rleap-m approved these changes

2024-12-10 07:50 UTC, MagdaDziadosz requested changes

2024-12-10 07:50 UTC, MagdaDziadosz commented on content/docs/migrate-from-MKE-3.md
> +- The ``calico_kdd`` flag in the MKE 3  configuration file is set to `true`.
```suggestion
- The ``calico_kdd`` flag in the MKE 3 configuration file is set to `true`.
```

2024-12-10 07:50 UTC, MagdaDziadosz commented on content/docs/migrate-from-MKE-3.md
> +  1. Verify that the MKE 3.x instance is being upgraded to MKE 4 is 3.7.12 or
```suggestion
  1. Verify that the MKE 3.x instance being upgraded to MKE 4 is running version 3.7.12 or
```

2024-12-10 07:50 UTC, MagdaDziadosz commented on content/docs/migrate-from-MKE-3.md
> +
```suggestion
{{< /callout >}}

```

2024-12-10 07:50 UTC, MagdaDziadosz commented on content/docs/migrate-from-MKE-3.md
> +- The MKE 3 source is version 3.7.12 or later.
```suggestion
- The MKE 3 source is running version 3.7.12 or later.
```

2024-12-10 12:03 UTC, KoryKessel-Mirantis commented on content/docs/migrate-from-MKE-3.md
> +- The MKE 3 source is version 3.7.12 or later.
Leaving as-is.

2024-12-10 12:40 UTC, MagdaDziadosz approved these changes

2024-12-10 12:40 UTC, merged