[BOP-1572] Add etcd configuration and custom flag migration info
Mirantis/mke-docs pull request #243
Opened 2024-11-23 22:01 UTC by nsteph

This change adds:

- etcd configuration page (similar to other Kube components)
- subsections on the MKE 3 configuration migration docs that cover kubernetes custom flags and kubelet custom flag profiles

2024-12-06 23:22 UTC, KoryKessel-Mirantis commented on content/docs/migrate-from-MKE-3.md
> +Any flags that cannot be automatically converted will be listed in the upgrade summary.
```suggestion
MKE 4 supports an `extraArgs` field for each of these components, accepting a map of key-value pairs, converting the custom flags to the corresponding `extraArgs` field during the upgrade process.
Any flags that cannot be automatically converted are listed in the upgrade summary.
```

2024-12-06 23:34 UTC, KoryKessel-Mirantis commented on content/docs/migrate-from-MKE-3.md
> +each specified as a list of strings.
```suggestion
MKE 3 and MKE 4 both support the application of additional flags to Kubernetes components that have the following fields in the MKE configuration file,
each specified as a list of strings.
```

2024-12-06 23:54 UTC, KoryKessel-Mirantis requested changes

2024-12-06 23:54 UTC, KoryKessel-Mirantis commented on content/docs/migrate-from-MKE-3.md
> +#### Example of custom flags conversion
```suggestion
Example of custom flags conversion:
```

2024-12-06 23:54 UTC, KoryKessel-Mirantis commented on content/docs/migrate-from-MKE-3.md
> +```
```suggestion
- MKE 3 configuration file:

  ```
  [cluster_config.custom_kube_api_server_flags] = ["--enable-garbage-collector=false"]
  ```

- MKE 4 configuration file:

  ```
  spec:
    apiServer:
      extraArgs:
        enable-garbage-collector: false
  ```
```

2024-12-06 23:54 UTC, KoryKessel-Mirantis commented on content/docs/migrate-from-MKE-3.md
> +```
Not sure that accepting the suggestion will result in a correct rendering, so I will try to offer here how I would like to see this example present.

* MKE 3 configuration file:

  ```
  [cluster_config.custom_kube_api_server_flags] = ["--enable-garbage-collector=false"]
  ```

* MKE 4 configuration file:

  ```
  spec
    apiServer:
      extraArgs:
        enable-garbage-collector: false
  ```

2024-12-06 23:54 UTC, KoryKessel-Mirantis commented on content/docs/migrate-from-MKE-3.md
> +corresponding kubelet custom profile.
```suggestion
MKE 4 does not support kubelet flag profiles, but you can use [Kubelet custom profiles](../configuration/kubernetes/kubelet.md#kubelet-custom-profiles) to map `KubeletConfiguration` values to specific nodes. MKE 4 does supports the migration of MKE 3 kubelet flag profiles to kubelet custom profiles.

The conversion of flags to `KubeletConfiguration` values is best-effort ,and any flags that cannot be
converted are listed in the upgrade summary. Hosts with a custom flag profile label are marked for the
corresponding kubelet custom profile.
```

2024-12-11 18:51 UTC, nsteph commented on content/docs/migrate-from-MKE-3.md
> +```
I tried to match this by bullet pointing the config examples.

2024-12-11 18:54 UTC, nsteph commented
@KoryKessel-Mirantis As discussed, I based the etcd pag on the existing MKE 3 docs, just changing the text to match the MKE 4 config and featureset.

The other sections (defrag/cleaning/alarm) describe features not yet implemented in MKE 4.

2025-01-09 20:06 UTC, KoryKessel-Mirantis requested changes

2025-01-09 20:25 UTC, KoryKessel-Mirantis requested changes

2025-01-09 20:25 UTC, KoryKessel-Mirantis commented on content/docs/configuration/kubernetes/etcd.md
> +weight: 2
```suggestion
weight: 6
```

2025-01-09 23:36 UTC, KoryKessel-Mirantis approved these changes

2025-01-13 12:05 UTC, MagdaDziadosz requested changes

2025-01-13 13:37 UTC, KoryKessel-Mirantis commented on content/docs/migrate-from-MKE-3.md
> +MKE 4 does not support kubelet flag profiles, but you can use [Kubelet custom profiles](../configuration/kubernetes/kubelet.md#kubelet-custom-profiles) to map `KubeletConfiguration` values to specifi
It is good as-is.

2025-01-13 13:45 UTC, KoryKessel-Mirantis commented on content/docs/migrate-from-MKE-3.md
> +MKE 4 does not support kubelet flag profiles, but you can use [Kubelet custom profiles](../configuration/kubernetes/kubelet.md#kubelet-custom-profiles) to map `KubeletConfiguration` values to specifi
```suggestion
MKE 4 does not support kubelet flag profiles, but you can use [Kubelet custom profiles](../configuration/kubernetes/kubelet.md#kubelet-custom-profiles) to map `KubeletConfiguration` values to specific nodes. MKE 4 does support the migration of MKE 3 kubelet flag profiles to kubelet custom profiles.
```

2025-01-13 13:54 UTC, MagdaDziadosz approved these changes

2025-01-13 13:54 UTC, merged