Create Service Node Deployment section.
Mirantis/mke-docs pull request #257
Opened 2024-12-10 15:09 UTC by KoryKessel-Mirantis

2024-12-10 22:46 UTC, byDimasik requested changes
Hey! Thanks for the great work! Apparently, I lied to you when I said the taint name change is the only change needed. After careful review, I found more differences and inconsistencies between MKE 3 and 4. Considering all my comments below, I feel like the first and the last pages are mostly redundant. Maybe it makes sense to combine them into 1 page. Wdyt?

2024-12-10 22:46 UTC, byDimasik commented on content/docs/configuration/sevice-node-deployment/allow-service-deploy-kube-manager-or-msr-nodes.md
> +specification.
UI part is not applicable in MKE 4 so we can just remove it

2024-12-10 22:46 UTC, byDimasik commented on content/docs/configuration/sevice-node-deployment/allow-service-deploy-kube-manager-or-msr-nodes.md
> +title: Allow services deployment on Kubernetes MKE manager or MSR nodes
```suggestion
title: Allow services deployment on Kubernetes MKE manager
```

MSR is a different story, there are different versions and I am not sure what taints they use so let's focus on MKE and skip MSR here and below

2024-12-10 22:46 UTC, byDimasik commented on content/docs/configuration/sevice-node-deployment/allow-service-deploy-kube-manager-or-msr-nodes.md
> +   operator: "Exists"
```suggestion
   - key: "node-role.kubernetes.io/master"
     operator: "Exists"
```

2024-12-10 22:46 UTC, byDimasik commented on content/docs/configuration/sevice-node-deployment/allow-service-deploy-kube-manager-or-msr-nodes.md
> +   operator: "Exists"
there is a typo in MKE 3 docs, `key` and `operator` must be on the same level

2024-12-10 22:46 UTC, byDimasik commented on content/docs/configuration/sevice-node-deployment/allow-service-deploy-kube-manager-or-msr-nodes.md
> +A ``NoSchedule`` taint is present on MKE manager and MSR nodes, and if you
```suggestion
A ``NoSchedule`` taint is present on MKE manager nodes, and if you
```

2024-12-10 22:46 UTC, byDimasik commented on content/docs/configuration/sevice-node-deployment/allow-service-deploy-kube-manager-or-msr-nodes.md
> +``kube-system`` namespace.
I do not understand what this paragraph is about. Maybe we should just remove it? I don't understand it in the context of MKE 3 either 😞

2024-12-10 22:46 UTC, byDimasik commented on content/docs/configuration/sevice-node-deployment/_index.md
> +performant and to enhance cluster security.
This is the default behavior, and the page below describes how to override this and allow running workloads on managers in addition to workers, so I am not sure how meaningful this is. I feel like this entire page is redundant, but I am not sure what was the reason for adding it in MKE 3, so maybe I am missing something

2024-12-10 22:46 UTC, byDimasik commented on content/docs/configuration/sevice-node-deployment/restrict-service-deploy-to-kube-workers.md
> +to prevent user workloads from deploying to MKE manager or MSR nodes.
```suggestion
to prevent user workloads from deploying to MKE manager nodes.
```

2024-12-10 22:46 UTC, byDimasik commented on content/docs/configuration/sevice-node-deployment/restrict-service-deploy-to-kube-workers.md
> +the taint, and the workload is scheduled on all node types.
This doesn't apply to MKE 4. I actually didn't know we had this in MKE 3, so we may wanna implement something like this for feature parity. For now, let's remove it.

2024-12-10 23:52 UTC, KoryKessel-Mirantis commented on content/docs/configuration/sevice-node-deployment/_index.md
> +performant and to enhance cluster security.
There is a better-than-bad chance that this page was only added to serve as a top-level page for the child-pages topics that fall under it. If we can consolidate all of the needed information from this page and 'allow' and 'restrict' into one topic for the MKE 4 docs...celebration?

2024-12-11 00:03 UTC, KoryKessel-Mirantis commented on content/docs/configuration/sevice-node-deployment/allow-service-deploy-kube-manager-or-msr-nodes.md
> +``kube-system`` namespace.
Leaving this directive in for now, so you can see it in the context of the merged iteration of the topic. If it still makes no sense and we cannot find anyone who can make sense of it, then I will pull out my scalpel. :-)

2024-12-11 23:03 UTC, byDimasik commented on content/docs/configuration/sevice-node-deployment/allow-service-deploy-kube-manager-or-msr-nodes.md
> +``kube-system`` namespace.
After reading this more carefully, something caught my attention

> a toleration for that taint will not be applied to the deployments

this implies tolerations can be applied automatically, but as I already mentioned in [my other comment](https://github.com/Mirantis/mke-docs/pull/257#discussion_r1879017846) we do not apply tolerations automatically in MKE 4. This is why we're writing this article - to provide steps on how to manually apply those tolerations. Thus, I think we should not include this part in the MKE 4 docs

2024-12-11 23:04 UTC, byDimasik commented on content/docs/configuration/sevice-node-deployment/_index.md
> +performant and to enhance cluster security.
yeah, that was my understanding as well. I guess since this is now just one page describing how to add tolerations to schedule workloads on manager nodes, we do not need this paragraph anymore

2024-12-12 00:16 UTC, byDimasik reviewed
I must be the biggest liar. I feel so bad for saying "almost no changes needed". I guess I just didn't read it very closely in my initial skimming, but the more I read it, the more MKE 3 legacy I see. I hope we can still be friends after this 😭

2024-12-12 00:16 UTC, byDimasik commented on content/docs/configuration/service-node-deployment.md
> +     operator: "Exists"
I just checked how we set it for system components, and there is one more field to set
```suggestion
   - key: "node-role.kubernetes.io/master"
     operator: "Exists"
     effect: "NoSchedule"
```

2024-12-12 00:16 UTC, byDimasik commented on content/docs/configuration/service-node-deployment.md
> +}
```suggestion
{
  "effect": "NoSchedule",
  "key": "node-role.kubernetes.io/master",
  "operator": "Exists"
}
```

2024-12-12 00:16 UTC, byDimasik commented on content/docs/configuration/service-node-deployment.md
> +   kubectl get <object> <workload> -o json | jq -r '.spec.template.spec.tolerations | .[]'
this particular command doesn't work for all object types. E.g. it won't work for `kubectl get pod` but will work for `kubectl get deployment`. Maybe it would be better to just remove the command and the example and just write something like 

> Confirm the successful application of the toleration by inspecting the modified object.

2024-12-12 00:16 UTC, byDimasik commented on content/docs/configuration/service-node-deployment.md
> +   MKE web UI or using the `kubectl edit <object> <workload>` command:
```suggestion
   MKE web UI or using the `kubectl edit <resource> <name>` command:
```

2024-12-12 00:16 UTC, byDimasik commented on content/docs/configuration/service-node-deployment.md
> +If for whatever reason a user deploys a malicious service that can affect
```suggestion
If for whatever reason a user deploys a malicious workload that can affect
```

The term `service` comes from Docker Swarm where this was a general name for workloads, but in kubernetes, the word "service" is reserved for a special resource type which is not necessarily a workload, so I suggest that here and below we use the word `workload` instead.

2024-12-12 00:16 UTC, byDimasik commented on content/docs/configuration/service-node-deployment.md
> +title: Service node deployment
considering the comment above, I guess the page should also be renamed, but "Workload node deployment" doesn't sound as good to me, or am I tripping?

2024-12-12 00:16 UTC, byDimasik commented on content/docs/configuration/service-node-deployment.md
> +Restrict services deployment to Kubernetes worker nodes
```suggestion
Restrict workload deployment to Kubernetes worker nodes
```

2024-12-12 00:16 UTC, byDimasik commented on content/docs/configuration/service-node-deployment.md
> +Allow services deployment on Kubernetes MKE manager
```suggestion
Allow workload deployment on Kubernetes MKE manager
```

2024-12-12 00:17 UTC, byDimasik commented on content/docs/configuration/service-node-deployment.md
> +Allow services deployment on Kubernetes MKE manager
you get the idea, there are a few more places with the same edit

2024-12-12 00:21 UTC, byDimasik commented on content/docs/configuration/service-node-deployment.md
> +For details, refer to [Restrict services deployment to Kubernetes worker nodes](../restrict-service-deploy-to-kube-workers).
there is no such page anymore

2024-12-12 09:45 UTC, KoryKessel-Mirantis commented on content/docs/configuration/service-node-deployment.md
> +title: Service node deployment
Works for me.

2024-12-12 09:46 UTC, KoryKessel-Mirantis commented on content/docs/configuration/service-node-deployment.md
> +Allow services deployment on Kubernetes MKE manager
Grabbed it up.

2024-12-12 09:54 UTC, MagdaDziadosz commented on content/docs/configuration/workload-node-deployment.md
> +By default, user workloads cannot run in manager nodes, to ensure that cluster
```suggestion
By default, user workloads cannot run in manager nodes to ensure that cluster
```

2024-12-12 09:54 UTC, MagdaDziadosz commented on content/docs/configuration/workload-node-deployment.md
> +If for whatever reason a user deploys a malicious workload that can affect
```suggestion
If user deploys a malicious workload that can affect
```

2024-12-12 09:54 UTC, MagdaDziadosz commented on content/docs/configuration/workload-node-deployment.md
> +tolerations](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/).
Do we need two links to the same page? Maybe we can add it in the intro and skip it here and above.

2024-12-12 14:32 UTC, byDimasik approved these changes
LGTM. Thanks for addressing all my comments!

2024-12-12 15:35 UTC, KoryKessel-Mirantis commented on content/docs/configuration/workload-node-deployment.md
> +By default, user workloads cannot run in manager nodes. This is to ensure that cluster
```suggestion
By default, user workloads cannot run on manager nodes. This is to ensure that cluster
```

2024-12-12 15:43 UTC, KoryKessel-Mirantis commented on content/docs/configuration/workload-node-deployment.md
> +tolerations](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/).
Somewhat redundant, but useful to the user who visits the topic for the purpose of viewing/using only one of the two sections.

2024-12-12 17:50 UTC, MagdaDziadosz approved these changes

2024-12-12 18:40 UTC, merged