MKE 3 -> MKE 4 pre-migration backup instructions
Mirantis/mke-docs pull request #260
Opened 2024-12-12 21:17 UTC by quadespresso

This PR is a first effort to call out activities relating to a pre-migration backup.

I believe this might address issue #123 as well.

2024-12-12 22:41 UTC, tppolkow commented on content/docs/migrate-from-MKE-3.md
> +Non-MKE 3 components such as standalone containers or volumes will be deleted, and **not** migrated
@quadespresso I believe you are referring to swarm containers / volumes here, if so - I think we should call that out explicitly.

 This is not accurate as a general statement, most MKE3 workloads should be migrated ( that are non - swarm ). I believe if anything non-swarm & non mke3 specific is not being migrated then that is a bug.

2024-12-13 00:23 UTC, quadespresso commented on content/docs/migrate-from-MKE-3.md
> +Non-MKE 3 components such as standalone containers or volumes will be deleted, and **not** migrated
@tppolkow right -- the context I was considering was not Swarm, but rather the edge case where a user happened to have set up a local container or volume outside the management of either Swarm or MKE 3.

That said, I will rephrase in an effort to clarify.

2024-12-14 01:02 UTC, KoryKessel-Mirantis requested changes

2024-12-14 01:02 UTC, KoryKessel-Mirantis commented on content/docs/migrate-from-MKE-3.md
> +
As discussed in Slack, I suggest that this example be removed entirely. The responsibility for backup documentation for non-MKE components (read: non-Mirantis products) is on the companies who develop, market, and support those components. It is not our job to do so, nor do we want to be on the hook for getting the information right and keeping it up to date.

2025-01-10 15:12 UTC, KoryKessel-Mirantis requested changes

2025-01-10 15:12 UTC, KoryKessel-Mirantis commented on content/docs/migrate-from-MKE-3.md
> +rather than migrated to MKE 4.
Delete, as the point has been moved up to the prior sentence.

2025-04-30 16:27 UTC, tppolkow approved these changes
LGTM

2025-04-30 16:28 UTC, sakshisharma84 approved these changes
looks good!

2025-04-30 23:49 UTC, KoryKessel-Mirantis approved these changes

2025-05-02 23:06 UTC, nwneisen approved these changes
Seems fine to me

2025-05-03 14:52 UTC, KoryKessel-Mirantis commented on content/docs/upgrade-from-MKE-3.md
> +### MKE 3 `etcdv3` backend is unsupported for MKE 4 upgrade
```suggestion
{{< callout type="important" >}}

The MKE 3 `etcdv3` backend is not supported for upgrade to MKE 4k.

{{< /callout >}}
```

2025-05-03 14:57 UTC, merged