Added TLS certificates documentation
Mirantis/mke-docs pull request #264
Opened 2024-12-16 14:20 UTC by MagdaDziadosz

2024-12-17 16:26 UTC, byDimasik requested changes
Hey! Thanks for working on this! I have a few minor comments that hopefully won't bother you much.

2024-12-17 16:26 UTC, byDimasik commented on content/docs/configuration/tls-certificates.md
> +certificates to access MKE from the CLI.
The second part of this statement is no longer applicable. I suggest we rewrite it to something like this

```suggestion
Your applications will continue to run normally. However, the Ingress Controller will restart, and if you use it to expose your applications to the outside world, they may be unavailable for a short time.
```

2024-12-17 16:26 UTC, byDimasik commented on content/docs/configuration/tls-certificates.md
> +download new client certificate bundles.
```suggestion
```

Client bundles are not implemented yet

2024-12-17 16:26 UTC, byDimasik commented on content/docs/configuration/tls-certificates.md
> +   ```
these requirements also apply to the "Server Certificate" from the UI table above, so we should either repeat it there or add a note that would apply to both, UI and CLI, sections

2024-12-17 16:26 UTC, byDimasik commented on content/docs/configuration/tls-certificates.md
> +   If you are using Linux, use `base64 -w0` instead.
hmm, I know I wrote it, but as time goes by, I'm gaining more wisdom, and now I think we should provide two sets of commands, e.g.

For MacOS users:
```bash
   CA_CERT=$(cat ca.pem | base64 -b0)
   SERVER_CERT=$(cat cert.pem | base64 -b0)
   SERVER_KEY=$(cat key.pem | base64 -b0)
```

For Linux users:
```bash
   CA_CERT=$(cat ca.pem | base64 -w0)
   SERVER_CERT=$(cat cert.pem | base64 -w0)
   SERVER_KEY=$(cat key.pem | base64 -w0)
```

2024-12-17 16:27 UTC, byDimasik commented on content/docs/configuration/tls-certificates.md
> +   To get the list of all required hosts, run the following command:
```suggestion
   To get the list of all required hosts, run the following command from the folder where your config file is located:
```

2024-12-17 17:04 UTC, KoryKessel-Mirantis requested changes

2024-12-17 17:04 UTC, KoryKessel-Mirantis commented on content/docs/configuration/tls-certificates.md
> +
```suggestion

4. In the configuration, set the `defaultSslCertificate` of the Ingress
   Controller to the previously established secret name.

```

2024-12-17 17:04 UTC, KoryKessel-Mirantis commented on content/docs/configuration/tls-certificates.md
> +   Example Ingress Controller section in the MKE configuration file:
```suggestion
   Example MKE configuration file `ingressController` section:
```

2024-12-17 17:10 UTC, KoryKessel-Mirantis commented
Ayi-yi-yi. Seeing that @byDimasik and I were reviewing at roughly the same time. Naturally, @byDimasik's comments must take precedence. I will reengage once the PR has his approval.

2024-12-19 11:00 UTC, KoryKessel-Mirantis requested changes

2024-12-19 11:00 UTC, KoryKessel-Mirantis commented on content/docs/configuration/tls-certificates.md
> +## Use the MKE web UI to align your TLS certificates and keys
```suggestion
## Use the MKE web UI to align TLS artifacts

To configure MKE with the MKE web UI to use your own TLS certificates and keys:
```

2024-12-19 16:34 UTC, byDimasik approved these changes
Great work! Thank you!

2024-12-19 19:07 UTC, KoryKessel-Mirantis requested changes

2024-12-19 19:07 UTC, KoryKessel-Mirantis commented on content/docs/configuration/tls-certificates.md
> +   **Admin Settings** > **Certificates**.
```suggestion
2. In the left-side navigation panel, navigate to **Admin Settings** > **Certificates**.
```

2024-12-19 19:07 UTC, KoryKessel-Mirantis commented on content/docs/configuration/tls-certificates.md
> +3. Upload your certificates and keys based on the following table.
```suggestion
3. Upload your certificates and keys.
```

2024-12-19 19:07 UTC, KoryKessel-Mirantis commented on content/docs/configuration/tls-certificates.md
> +3. Upload your certificates and keys based on the following table.
The "based on the following table" clause is problemantic here because it does not actually _follow_. In the source MKE 3.x content this is not a problem (not a big one, anyway) because the directive is very small, which is not the case here. In my opinion, the user does not need the clause, anyway, so I suggest we jettison it.

2024-12-20 11:30 UTC, KoryKessel-Mirantis commented on content/docs/configuration/tls-certificates.md
> +    HOSTS=$(yq '[(.spec.apiServer.externalAddress, .spec.hosts.[] | select(.role == "controller+worker") | .ssh.address)] | join(" ")' <MKE CONFIGURATION FILE NAME>)
```suggestion
    HOSTS=$(yq '[(.spec.apiServer.externalAddress, .spec.hosts.[] | select(.role == "controller+worker") | .ssh.address)] | join(" ")' <mke-configuration-file-name>.yaml)
```

2024-12-20 11:44 UTC, KoryKessel-Mirantis requested changes

2024-12-20 11:44 UTC, KoryKessel-Mirantis commented on content/docs/configuration/tls-certificates.md
> +    {{< /callout >}}
@byDimasik , is the MKE configuration file cited in this command always going to be a YAML file? If so, @MagdaDziadosz, please change `<MKE CONFIGURATION FILE NAME>` to` <mke-configuration-file-name>.yaml` (otherwise, please change it to `<mke-configuration-file-name>`.

Also, for me there is a dissonance between 'allowed hosts' and 'required hosts'. My gut is telling me that the second reference should just read "To obtain the list of hosts, run the....etc." If that is accurate, @MagdaDziadosz, please indent "To obtain..." and the accompanying code-block to align under the bullet.

2024-12-20 11:44 UTC, KoryKessel-Mirantis commented on content/docs/configuration/tls-certificates.md
> +   ```
Same comment as above....

@byDimasik , is the MKE configuration file cited in this command always going to be a YAML file? If so, @MagdaDziadosz, please change <MKE CONFIGURATION FILE NAME> to <mke-configuration-file-name>.yaml (otherwise, please change it to <mke-configuration-file-name>.

Also, for me there is a dissonance between 'allowed hosts' and 'required hosts'. My gut is telling me that the second reference should just read "To obtain the list of hosts, run the....etc." If that is accurate, @MagdaDziadosz, please indent "To obtain..." and the accompanying code-block to align under the bullet.

2024-12-20 15:39 UTC, byDimasik commented on content/docs/configuration/tls-certificates.md
> +    {{< /callout >}}
@KoryKessel-Mirantis @MagdaDziadosz 
>  is the MKE configuration file cited in this command always going to be a YAML file?

yes. Also, if it's named exactly `mke4.yaml`, `mkectl` will find it automatically, so you can just run
```sh
mkectl apply
``` 

from the folder where the file is located. If the name is any different, users must explicitly specify it with `-f` flag

```
mkectl apply -f irenameditfornogoodreason.yaml
```

So, I think in our docs we could consider using `mke4.yaml` everywhere, and mention once that if it's renamed, it's a tiny bit more typing when applying it. This way we may convince our customers to stick with the good default name.

> Also, for me there is a dissonance between 'allowed hosts' and 'required hosts'. 

Certificates have a list of _allowed_ hosts called SANs (subject alternative names), and MKE 4 _requires_ to have manager IPs in that list. So, I'd suggest we drop the second part from here

> IP addresses for all manager nodes in the list of allowed hosts

to make it just

> IP addresses for all manager nodes

And rephrase the intro:

> All keys and certificates must be uploaded in PEM format, and the
    certificates must include the following SANs:

2024-12-23 14:02 UTC, MagdaDziadosz commented on content/docs/configuration/tls-certificates.md
> +    {{< /callout >}}
I checked other topics, and we use `mke4.yaml` without referencing any other possible name for the config file, so I'll just use it in the intro and commands.

2024-12-23 21:54 UTC, KoryKessel-Mirantis requested changes

2024-12-23 21:54 UTC, KoryKessel-Mirantis commented on content/docs/configuration/tls-certificates.md
> +      the directory containing the `mke4.yaml` file:
```suggestion
      the directory that contains the `mke4.yaml` file:
```

2024-12-23 21:54 UTC, KoryKessel-Mirantis commented on content/docs/configuration/tls-certificates.md
> +     the directory containing the `mke4.yaml` file:
```suggestion
     the directory that contains the `mke4.yaml` file:
```

2024-12-24 09:27 UTC, KoryKessel-Mirantis approved these changes

2024-12-24 09:34 UTC, merged