Docs for dashboard
Mirantis/mke-docs pull request #27
Opened 2024-06-06 17:46 UTC by rachaelbrownie

2024-06-06 17:52 UTC, rachaelbrownie commented on content/docs/reference/ui.md
> +[INSERT SCREENSHOT]
Not sure if we want this? 👍 or 👎 ?

2024-06-06 17:54 UTC, rachaelbrownie commented on content/docs/reference/ui.md
> +- View kubernetes resources by namespace, or all namespaces at once
```suggestion
 - View kubernetes resources by namespace, or all namespaces at once
```

2024-06-06 18:28 UTC, ry4nz commented on content/docs/reference/ui.md
> +# Dashboard add-on for MKE
Let's specify that this addon is not available until alpha.2.0

2024-06-06 22:20 UTC, quadespresso requested changes

2024-06-06 22:20 UTC, quadespresso commented on content/docs/reference/ui.md
> +## 4.0.0-apha.1v
Typo?

Not sure what was intended here, eg,

```
## 4.0.0-alpha.1v
```

or

```
## v4.0.0-alpha.1
```

or something else

2024-06-07 14:45 UTC, rachaelbrownie commented on content/docs/reference/ui.md
> +## 4.0.0-apha.1v
Glad you made a comment, it should actually be alpha2. how about ?

```suggestion
## 4.0.0-alpha.2 release
```

2024-06-07 14:47 UTC, rachaelbrownie commented on content/docs/reference/ui.md
> +# Dashboard add-on for MKE
How about

```suggestion
# Dashboard add-on for MKE [`v4.0.0-alpha.2.0`+]
```
Or we can make a separate folder or something for it ? 🤷

2024-06-07 15:01 UTC, rachaelbrownie commented on content/docs/reference/ui.md
> +```
who can answer this?

2024-06-07 15:46 UTC, brianbancroft commented on content/docs/reference/ui.md
> +[INSERT SCREENSHOT]
Yes.

2024-06-07 15:47 UTC, brianbancroft commented on content/docs/reference/ui.md
> +- View kubernetes resources by namespace, or all namespaces at once
Whitespace in this file seems uneven

2024-06-07 17:29 UTC, quadespresso commented on content/docs/reference/ui.md
> +- View kubernetes resources by namespace, or all namespaces at once
I'm strongly inclined to say that all the lines with a single leading space should have a double leading space. It makes sense (to me, at this particular moment in time) that lines 21-28 would all be bullets subordinate to line 20. And that line 29 would be a fresh "level 1" bullet.

I defer to the original author :slightly_smiling_face:

2024-06-07 19:41 UTC, brianbancroft commented on content/docs/reference/ui.md
> +```
Leave as-is. Out of scope for this PR. Will be solved as part of [BOP-740](https://mirantis.jira.com/browse/BOP-740)

2024-06-10 15:42 UTC, rachaelbrownie commented on content/docs/reference/ui.md
> +```
that's a good point, we could add later

2024-06-10 15:59 UTC, ry4nz commented
Could you add a link in https://github.com/Mirantis/mke-docs/blob/main/content/releases/README.md with the page you created for discoverability ?

2024-06-13 17:33 UTC, rachaelbrownie commented
Ryan has also requested that i add a "what's new" section for things that have a major change compared to MKE4. So I will add that in the next day.

2024-06-13 17:35 UTC, rachaelbrownie commented on content/docs/reference/ui.md
> +[INSERT SCREENSHOT]
I will add this as soon as we have the icons added to the MDS.

2024-06-25 14:24 UTC, ry4nz approved these changes

2024-06-26 18:11 UTC, quadespresso approved these changes

2024-06-26 20:06 UTC, merged