[BOP-1475] Improve custom worker profiles docs
Mirantis/mke-docs pull request #272
Opened 2024-12-19 08:27 UTC by MagdaDziadosz

2024-12-19 19:43 UTC, byDimasik commented on content/docs/configuration/kubernetes/kubelet.md
> +- Add `allowedUnsafeSysctls` as namespaced `sysctls`. Non-namespaced `sysctls`
I am not sure I understand what you mean by "as namespaced". 
I had a typo in my initial description that might have made it unclear.
There are two types of sysctls: namespaced and non-namespaced. They may look identical because this particular setting doesn't imply specifying the namespace, it only needs the name of the sysctl. So, the second sentence here is correct, we do not support non-namespaced, and the first sentence should say that only namespaced ones are supported. Maybe my English isn't good enough, but the phrase "add as namespaced" doesn't read right to me.

I found example of the same idea in OpenShift docs for reference - https://docs.openshift.com/container-platform/4.11/nodes/containers/nodes-containers-sysctls.html#namespaced-and-node-level-sysctls

2024-12-20 17:34 UTC, MagdaDziadosz commented on content/docs/configuration/kubernetes/kubelet.md
> +- Add `allowedUnsafeSysctls` as namespaced `sysctls`. Non-namespaced `sysctls`
@byDimasik I changed the problematic sentence, I hope it is clearer now.

2024-12-20 17:55 UTC, byDimasik approved these changes
LGTM! Thank you for the great work!

2024-12-23 12:11 UTC, KoryKessel-Mirantis requested changes

2024-12-23 12:11 UTC, KoryKessel-Mirantis commented on content/docs/configuration/kubernetes/kubelet.md
> +   profile-related errors.
Unless the purpose of this step is to send the user back to Step 1 of the procedure, I suggest that it be wrapped into the preceding step.

"Check the logs of the k0scontroller system service `journalctl -u k0scontroller`. Repeat the process for every manager node until you find errors related to kubelet or to worker profiles."

2024-12-23 12:11 UTC, KoryKessel-Mirantis commented on content/docs/configuration/kubernetes/kubelet.md
> +When creating the custom profile, ensure the following:
The transition between the lead-in and the bullets is jarring. Please reword -- either, or -- to make for a smoother communication.

2024-12-23 12:11 UTC, KoryKessel-Mirantis commented on content/docs/configuration/kubernetes/kubelet.md
>  Hosts can be assigned a custom profile through the `hosts` section of the MKE
```suggestion
You can assign a custom profile through the `hosts` section of the MKE
```

2024-12-23 15:12 UTC, KoryKessel-Mirantis requested changes

2024-12-23 22:15 UTC, KoryKessel-Mirantis approved these changes

2024-12-24 06:53 UTC, merged