Fix typo in telemetry docs
Mirantis/mke-docs pull request #274
Opened 2024-12-20 18:18 UTC by byDimasik

Resolves https://github.com/Mirantis/mke-docs/issues/273

2024-12-20 18:57 UTC, quadespresso requested changes

2024-12-20 18:57 UTC, quadespresso commented on content/docs/configuration/telemetry.md
> +2. Set the ``spec.tracking.enabled`` field to `true`.
s/b:

```
Set the `spec.tracking.enabled` field to `true`.
```

2024-12-20 23:50 UTC, KoryKessel-Mirantis approved these changes

2024-12-21 00:43 UTC, quadespresso approved these changes
LGTM :tada:

2024-12-21 00:43 UTC, merged