Enhance the Getting Started documentation.
Mirantis/mke-docs pull request #276
Opened 2024-12-23 15:20 UTC by KoryKessel-Mirantis

2025-01-06 16:32 UTC, nwneisen approved these changes
The changes look good to me.

The only thought I have is that many project keep the `Getting Started` page as simple and bare bones as possible.
- https://docs.k0sproject.io/stable/install/
- https://git-scm.com/book/ms/v2/Getting-Started-First-Time-Git-Setup
Some of the topics here seem like they are getting into more advanced usage that isn't necessary to spin up a basic cluster. We could still include links to them in the usage page to point someone to the right direction after getting setup. Just some food for thought.

Otherwise, just a reminder to check the links you created. I can't remember if the bare string page names work once built for github.

2025-01-07 10:01 UTC, MagdaDziadosz requested changes

2025-01-07 15:37 UTC, KoryKessel-Mirantis commented on content/docs/getting-started/_index.md
> +and [how to uninstall a cluster](uninstall-cluster).
My intent in structuring the paragraph in this manner was to make it read more _conversational_, and less like a list of what else can be learned in the section, which might beg the question "Why did these topics not get the bigger H3 treatment?"

2025-01-08 07:18 UTC, MagdaDziadosz approved these changes

2025-01-08 12:54 UTC, merged