[DOC] Edit monitoring
Mirantis/mke-docs pull request #29
Opened 2024-06-06 19:10 UTC by MagdaDziadosz

A slightly bigger edit, added descriptions and tables.

2024-06-06 21:35 UTC, nsteph approved these changes
LGTM. Thanks!

2024-06-06 22:47 UTC, KoryKessel-Mirantis requested changes

2024-06-06 22:47 UTC, KoryKessel-Mirantis commented on content/docs/reference/monitoring/monitoring.md
> +This document provides guidance on setting up monitoring for your
Suggest losing this intro-ish sentence. as the heading does the same job, given the topic context.

2024-06-06 22:47 UTC, KoryKessel-Mirantis commented on content/docs/reference/monitoring/monitoring.md
> +The monitoring setup is based on the [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack),
Tap 'MKE 4' in front of 'monitoring'.

2024-06-06 22:47 UTC, KoryKessel-Mirantis commented on content/docs/reference/monitoring/monitoring.md
> +
```suggestion
Detail for the MKE 4 monitor tools is provided in the following table:

```

2024-06-06 22:47 UTC, KoryKessel-Mirantis commented on content/docs/reference/monitoring/monitoring.md
> +| Opscare    | disabled      | `monitoring.enableOpscare` | (Future feature) Includes additional monitoring capabilities like Alertmanager |
```suggestion
| Opscare    | disabled      | `monitoring.enableOpscare` | (Future feature) Supplies additional monitoring capabilities, such as Alertmanager |
```

2024-06-06 22:47 UTC, KoryKessel-Mirantis commented on content/docs/reference/monitoring/monitoring.md
> +
```suggestion
[Grafana](https://grafana.com/) is an open-source monitoring platform that provides a rich set of tools for visualizing time-series data. It
includes a variety of graph types and dashboards.

```

2024-06-06 22:47 UTC, KoryKessel-Mirantis commented on content/docs/reference/monitoring/monitoring.md
> +Grafana is enabled in MKE 4 by default and may be disabled through the configuration:
```suggestion
Grafana is enabled in MKE 4 by default and may be disabled through the MKE configuration file:
```

2024-06-06 22:47 UTC, KoryKessel-Mirantis commented on content/docs/reference/monitoring/monitoring.md
> +2. Access Grafana dashboard through [http://localhost:3000](http://localhost:3000).
```suggestion
2. Go to [http://localhost:3000](http://localhost:3000).
```

2024-06-06 22:47 UTC, KoryKessel-Mirantis commented on content/docs/reference/monitoring/monitoring.md
> +toolkit designed for reliability and scalability. It collects and stores metrics
```suggestion
toolkit that is designed for reliability and scalability. It collects and stores metrics
```

2024-06-06 22:47 UTC, KoryKessel-Mirantis commented on content/docs/reference/monitoring/monitoring.md
> +To access Grafana dashboard:
```suggestion
To access the Grafana dashboard:
```

2024-06-06 22:47 UTC, KoryKessel-Mirantis commented on content/docs/reference/monitoring/monitoring.md
> +To access Prometheus dashboard:
```suggestion
To access the Prometheus dashboard:
```

2024-06-06 22:47 UTC, KoryKessel-Mirantis commented on content/docs/reference/monitoring/monitoring.md
> +2. Access Prometheus dashboard through [http://localhost:9090](http://localhost:9090).
```suggestion
2. Go to [http://localhost:9090](http://localhost:9090).
```

2024-06-06 22:47 UTC, KoryKessel-Mirantis commented on content/docs/reference/monitoring/monitoring.md
> +Future releases will include more integrations, such as a Salesforce-notifier component.
Suggest removing this line. Need to refrain from making promises for the future.

2024-06-06 22:47 UTC, KoryKessel-Mirantis commented on content/docs/reference/monitoring/monitoring.md
> +[Prometheus Alertmanager](https://prometheus.io/docs/alerting/latest/alertmanager/).
```suggestion
an advanced monitoring and alerting solution. Once it is integrated, Mirantis Opscare will enhance the monitoring
capabilities of MKE 4 by incorporating additional tools and features, such as
[Prometheus Alertmanager](https://prometheus.io/docs/alerting/latest/alertmanager/).
```

2024-06-06 22:47 UTC, KoryKessel-Mirantis commented on content/docs/reference/monitoring/monitoring.md
> +Mirantis OpsCare is disabled by default and may be enabled through the MKE4 configuration.
Disabled by default, you will enable Mirantis Opscare through the MKE configuration file.
```suggestion
Disabled by default, you will enable Mirantis Opscare through the MKE configuration file.
```

2024-06-07 06:29 UTC, MagdaDziadosz commented on content/docs/reference/monitoring/monitoring.md
> +Mirantis OpsCare is disabled by default and may be enabled through the MKE4 configuration.
```suggestion
Disabled by default, you can enable Mirantis Opscare through the MKE configuration file.
```

2024-06-07 09:06 UTC, KoryKessel-Mirantis commented
LGTM

2024-06-07 09:06 UTC, KoryKessel-Mirantis approved these changes
LGTM

2024-06-07 09:09 UTC, merged