Fix typo
Mirantis/mke-docs pull request #52
Opened 2024-07-25 05:50 UTC by ogusarenko

2024-07-25 06:39 UTC, MagdaDziadosz requested changes

2024-07-25 06:39 UTC, MagdaDziadosz commented on content/docs/concepts/cni.md
> +The following table includes the details on all of the configurable `network` fields.
```suggestion
The following table includes details on all of the configurable `network` fields.
```

2024-07-25 06:39 UTC, MagdaDziadosz commented on content/docs/concepts/cni.md
> +The following table includes the details on the configurable settings
```suggestion
The following table includes details on the configurable settings
```

2024-07-25 06:39 UTC, MagdaDziadosz commented on content/docs/concepts/cni.md
> +| `mode` | Sets the ipv4 overlay networking mode. | `ipip`, `vxlan` | `vxlan` |
```suggestion
| `mode` | Sets the IPv4 overlay networking mode. | `ipip`, `vxlan` | `vxlan` |
```

2024-07-25 06:39 UTC, MagdaDziadosz commented on content/docs/concepts/cni.md
> +and they may need to be changed at the same time as the `nodePortRange`.
```suggestion
Components using `nodeports` may have their own specific way of specifying the port numbers for NodePorts,
and these may need to be changed simultaneusly with the `nodePortRange`.
```

2024-07-25 06:39 UTC, MagdaDziadosz commented on content/docs/concepts/cni.md
> +| Field | Description | Valid values |  Default |
Too many uses of “valid”, suggesting changing the header to Values, and consider removing valid from the table values as well.

2024-07-25 06:39 UTC, MagdaDziadosz commented on content/docs/concepts/cni.md
> +| Field   | Description  | Valid values        |  Default     |
Same comment as in the table above.

2024-07-26 03:55 UTC, vikramhh commented on content/docs/concepts/cni.md
> +and they may need to be changed at the same time as the `nodePortRange`.
@MagdaDziadosz - spellings of simultaneously

2024-07-26 03:56 UTC, vikramhh approved these changes
LGTM - I am good either way with https://github.com/Mirantis/mke-docs/pull/52#discussion_r1690893236

2024-07-26 06:15 UTC, MagdaDziadosz approved these changes

2024-07-26 06:27 UTC, merged