[BOP-972] Add docs for GPU workloads
Mirantis/mke-docs pull request #74
Opened 2024-08-08 21:40 UTC by nwneisen

https://mirantis.jira.com/browse/BOP-972

Adds documentation for enabling GPU in MKE4

Should be merged in after https://github.com/MirantisContainers/mke-operator/pull/40

2024-08-09 04:29 UTC, ry4nz commented
Looks great!  Could you please also add a section talking about upgrade?

2024-08-09 13:51 UTC, nwneisen commented
@ry4nz Thanks for the reminder!

2024-08-09 16:54 UTC, ry4nz commented
@MagdaDziadosz please review

2024-08-12 15:18 UTC, MagdaDziadosz requested changes

2024-08-12 15:18 UTC, MagdaDziadosz commented on content/docs/migrate-from-MKE-3.md
> +you must perform the [GPU prerequisites](/docs/operations/gpu/#prerequisites) before upgrading {{< /callout >}}
```suggestion
{{< callout type="info" >}} To upgrade an MKE 3 cluster with GPU enabled,
ensure you complete the [GPU prerequisites](/docs/operations/gpu/#prerequisites) before
starting the upgrade process. {{< /callout >}}
```

2024-08-12 15:18 UTC, MagdaDziadosz commented on content/docs/operations/gpu.md
> +To enable GPU support, MKE will install the NVIDIA GPU Operator on your cluster.
```suggestion
To enable GPU support, MKE installs the NVIDIA GPU Operator on your cluster.
```

2024-08-12 15:18 UTC, MagdaDziadosz commented on content/docs/operations/gpu.md
> +
```suggestion
GPU support is disabled by default. To enable GPU support, configure
the `gpu` section of the MKE configuration file:

```

2024-08-12 15:18 UTC, MagdaDziadosz commented on content/docs/operations/gpu.md
> +This informs MKE to install the NVIDIA GPU Operator on your cluster.
```suggestion
Configuration enables MKE to install the NVIDIA GPU Operator on your cluster.
```

2024-08-13 03:50 UTC, MagdaDziadosz approved these changes

2024-08-13 16:02 UTC, merged