Create Remove nodes from cluster topic.
Mirantis/mke-docs pull request #84
Opened 2024-09-02 23:29 UTC by KoryKessel-Mirantis

2024-10-25 20:41 UTC, byDimasik approved these changes

2024-10-25 20:42 UTC, byDimasik commented
LGTM. Thank you!

2024-10-28 12:44 UTC, MagdaDziadosz requested changes

2024-10-28 12:44 UTC, MagdaDziadosz commented on content/docs/operations/remove-node-from-cluster
> +for informaation on how to remove a control plane node from an MKE 4 cluster.
```suggestion
for information on how to remove a control plane node from an MKE 4 cluster.
```

2024-10-28 12:44 UTC, MagdaDziadosz commented on content/docs/operations/remove-node-from-cluster
> +operation.
```suggestion
To remove a worker node from an MKE 4 cluster:
```

2024-10-28 12:55 UTC, KoryKessel-Mirantis commented on content/docs/operations/remove-node-from-cluster
> +operation.
Removing the line entirely and editing Step 1.

2024-10-28 12:55 UTC, KoryKessel-Mirantis commented on content/docs/operations/remove-node-from-cluster
> +1. Run the following  `kubectl` command:
```suggestion
1. Delete the worker node from the MKE 4 cluster:
```

2024-10-28 12:57 UTC, MagdaDziadosz approved these changes

2024-10-28 12:57 UTC, merged