Insertion of CoreDNS Lameduck information into migration topic.
Mirantis/mke-docs pull request #90
Opened 2024-09-13 17:38 UTC by KoryKessel-Mirantis

2024-09-13 22:32 UTC, moshiurH requested changes
I hope you can address the two nit-picks/feedbacks. Otherwise looking good 👍

2024-09-13 22:32 UTC, moshiurH commented on content/docs/migrate-from-MKE-3.md
> +MKE 4 supports migration MKE 3 systems with CoreDNS and Lameduck enabled. Refer
I think it should be:
"MKE 4 supports migration **from** MKE 3 systems with CoreDNS and Lameduck enabled."

I am hoping that in this migration guide, we are asking users to use the latest MKE 3.7 builds when performing the migration. We have not fully tested or guranteed migration success for MKE builds that are not latest (MKE 3.4, 3.5, and 3.6). We should probably have some verbiage for making sure users are on the latest MKE 3.7 (or new-ish MKE 3.7).

Otherwise I am happy with the CoreDNS and Lameduck writeup!

2024-09-13 22:32 UTC, moshiurH commented on content/docs/migrate-from-MKE-3.md
> +| [cluster_config.core_dns_lameduck_config.duration]    |  dns.lameduck.duration
LGTM!

2024-09-16 06:21 UTC, MagdaDziadosz approved these changes

2024-09-16 06:21 UTC, MagdaDziadosz commented on content/docs/migrate-from-MKE-3.md
> +| [cluster_config.core_dns_lameduck_config.duration]    |  dns.lameduck.duration
```suggestion
| MKE 3                                              | MKE 4                 |
|----------------------------------------------------|-----------------------|
| [cluster_config.core_dns_lameduck_config.enabled]  | dns.lameduck.enabled  |
| [cluster_config.core_dns_lameduck_config.duration] | dns.lameduck.duration |
```
Formatting fix

2024-09-16 17:20 UTC, moshiurH approved these changes
LGTM

2024-09-16 17:50 UTC, merged

2024-09-17 16:45 UTC, KoryKessel-Mirantis commented on content/docs/migrate-from-MKE-3.md
> +MKE 4 supports migration MKE 3 systems with CoreDNS and Lameduck enabled. Refer
@moshiurH, please consider reviewing the Migration page in depth and submitting any observations, feedback, issues, etc. via an Issue here in mke-docs (sure to be seen).

2024-09-18 17:13 UTC, moshiurH commented on content/docs/migrate-from-MKE-3.md
> +MKE 4 supports migration MKE 3 systems with CoreDNS and Lameduck enabled. Refer
@KoryKessel-Mirantis I'll try to take a detailed look at https://mirantis.github.io/mke-docs/docs/migrate-from-mke-3/ sometime this week and log any issues as I see them. Thank you for providing me with the expected workflow for logging issues 👍.