Authentication review edit restructure
Mirantis/mke-docs pull request #95
Opened 2024-09-17 22:46 UTC by KoryKessel-Mirantis

2024-09-18 14:30 UTC, nwneisen commented on content/docs/operations/authentication/OIDC-providers/OIDC.md
> +<summary>Okta</summary>
Sorry I was meaning keep these on their own pages but put those pages into their own dropdown section in the navigation sidebar. I don't think these should all be on one page because some of them will get very large

2024-09-18 16:30 UTC, nwneisen commented on content/docs/tutorials/authentication-provider-setup/auth-provider-setup.md
> +<summary>Okta</summary>
This tutorial shows how to configure an Okta application as you OIDC provider and where to retrieve the values needed to configure MKE

2024-09-18 16:30 UTC, nwneisen commented on content/docs/tutorials/authentication-provider-setup/auth-provider-setup.md
> +<summary>Okta</summary>
This tutorial shows how to configure an Okta application as you SAML provider and where to retrieve the values needed to configure MKE

2024-09-18 16:30 UTC, nwneisen commented on content/docs/tutorials/authentication-provider-setup/auth-provider-setup.md
> +- Lightweight Directory Access Protocol (LDAP)
This tutorial shows how to deploy an OpenLDAP server on your local machine with a basic configuration that can be used for testing with MKE

2024-09-18 21:40 UTC, KoryKessel-Mirantis commented on content/docs/tutorials/authentication-provider-setup/auth-provider-setup.md
> +- Lightweight Directory Access Protocol (LDAP)
I do not have content for this tutorial topic as of yet.

2024-09-19 14:35 UTC, nwneisen approved these changes
LGTM

2024-09-20 14:19 UTC, MagdaDziadosz requested changes

2024-09-20 14:19 UTC, MagdaDziadosz commented on content/docs/operations/authentication/_index.md
> +- **Identity Provider (IdP):** To set OIDC or SAML you must configure an IdP
```suggestion
- **Identity Provider (IdP):** To set OIDC or SAML, you must configure an IdP
```

2024-09-20 14:19 UTC, MagdaDziadosz commented on content/docs/tutorials/authentication-provider-setup/oidc-provider-setup.md
> +as as your [OIDC authentication](../../../operations/authentication/OIDC) provider for MKE 4.
```suggestion
Configure an Okta application to serve as your [OIDC authentication](../../../operations/authentication/OIDC) provider for MKE 4:
```

2024-09-20 14:19 UTC, MagdaDziadosz commented on content/docs/tutorials/authentication-provider-setup/saml-provider-setup.md
> +for MKE 4.
```suggestion
Configure an Okta application to serve as your [SAML authentication](../../../operations/authentication/SAML) provider for MKE 4.
```

2024-09-20 14:25 UTC, KoryKessel-Mirantis commented on content/docs/operations/authentication/LDAP.md
> +the interactions with your LDAP server.
It is a 'service', not a 'server'. As such, in my opinion the possessive applies.

2024-09-20 14:26 UTC, KoryKessel-Mirantis commented on content/docs/operations/authentication/OIDC.md
> +In the MKE configuration file `authentication.oidc` section, enable your
See above note about 'service' versus 'server'.

2024-09-20 14:26 UTC, KoryKessel-Mirantis commented on content/docs/operations/authentication/LDAP.md
> +In the MKE configuration file `authentication.ldap` section, enable your
See above note about 'service' versus 'server'.

2024-09-20 14:39 UTC, KoryKessel-Mirantis commented on content/docs/tutorials/authentication-provider-setup/oidc-provider-setup.md
> +as as your [OIDC authentication](../../../operations/authentication/OIDC) provider for MKE 4.
```suggestion
To configure an Okta application to serve as your [OIDC authentication](../../../operations/authentication/OIDC) provider for MKE 4:
```

2024-09-20 14:40 UTC, KoryKessel-Mirantis commented on content/docs/tutorials/authentication-provider-setup/saml-provider-setup.md
> +for MKE 4.
```suggestion
To configure an Okta application to serve as your [SAML authentication](../../../operations/authentication/SAML) provider for MKE 4:
```

2024-09-20 14:43 UTC, MagdaDziadosz approved these changes

2024-09-20 14:48 UTC, merged