Update monitoring.md
Mirantis/mke-docs pull request #96
Opened 2024-09-20 04:33 UTC by Rajakavitha1

Fixes: https://github.com/Mirantis/mke-docs/issues/88

2024-09-20 16:29 UTC, KoryKessel-Mirantis requested changes

2024-09-20 16:29 UTC, KoryKessel-Mirantis commented on content/docs/operations/monitoring.md
> +1. Get the `admin` user password of the Grafana dashboard from the `monitoring-grafana` secret in the `mke` namespace.
```suggestion
1. Obtain the `admin` user password for the Grafana dashboard from the `monitoring-grafana` secret in the `mke` namespace.
```

2024-09-20 16:29 UTC, KoryKessel-Mirantis commented on content/docs/operations/monitoring.md
>  1. Run the following command to `port-forward` Grafana:
```suggestion
2. Run the following command to `port-forward` Grafana:
```

2024-09-20 16:29 UTC, KoryKessel-Mirantis commented on content/docs/operations/monitoring.md
> +   Login using the default username `admin` and provide the password that you retrieved from the `monitoring-grafana` secret.
```suggestion
3. Navigate to `http://localhost:3000` to access the **Welcome to Grafana** login page.

4. Enter the default username **admin** into the **Email or username** field and type the password you retrieved from the `monitoring-grafana` secret into the **Password** field.

5. Click **Log In**.
```

2024-10-03 12:26 UTC, KoryKessel-Mirantis requested changes

2024-10-03 12:26 UTC, KoryKessel-Mirantis commented on content/docs/operations/monitoring.md
> +    ```
```suggestion
   ```bash
   kubectl get secret monitoring-grafana -n mke -o jsonpath="{.data.admin-password}" | base64 --decode
   ```
```

2024-10-06 10:20 UTC, KoryKessel-Mirantis requested changes

2024-10-06 10:20 UTC, KoryKessel-Mirantis commented on content/docs/operations/monitoring.md
> +   kubectl get secret monitoring-grafana -n mke -o jsonpath="{.data.admin-password}" | base64 --decode
Please put a line between the step and the codeblock. Also, the codeblock formatting should be closed with ```. I tried to do show that as a Suggestion, however I could not get it to work. A good reference is the codeblock under step 2.

2024-10-06 10:20 UTC, KoryKessel-Mirantis commented on content/docs/operations/monitoring.md
> +2. Run the following command to `port-forward` Grafana:
```suggestion
2. Port forward Grafana:
```

2024-10-06 10:20 UTC, KoryKessel-Mirantis commented on content/docs/operations/monitoring.md
> +2. Run the following command to `port-forward` Grafana:
Please change the similar step for Prometheus to read in the same manner.

2024-10-06 10:20 UTC, KoryKessel-Mirantis commented on content/docs/operations/monitoring.md
> +3. Navigate to `http://localhost:3000` to access the **Welcome to Grafana** login page.
Please edit the similar step in Prometheus to read the same way. Something like:

"Navigate to <URL> to access the <name of Prometheus entry page> page."

2024-10-08 23:11 UTC, KoryKessel-Mirantis requested changes

2024-10-08 23:11 UTC, KoryKessel-Mirantis commented on content/docs/operations/monitoring.md
> +   kubectl get secret monitoring-grafana -n mke -o jsonpath="{.data.admin-password}" | base64 --decode
```suggestion
1. Obtain the `admin` user password for the Grafana dashboard from the `monitoring-grafana` secret in the `mke` namespace.

   ```bash
   kubectl get secret monitoring-grafana -n mke -o jsonpath="{.data.admin-password}" | base64 --decode
   ```
```

2024-10-09 04:40 UTC, Rajakavitha1 commented on content/docs/operations/monitoring.md
> +3. Navigate to `http://localhost:3000` to access the **Welcome to Grafana** login page.
done. at localist:9090 Prometheus displays the status page of Prometheus (https://prometheus.io/docs/prometheus/latest/getting_started/#starting-prometheus).

2024-10-09 11:54 UTC, KoryKessel-Mirantis approved these changes

2024-10-09 11:54 UTC, merged