Backup restore restructure
Mirantis/mke-docs pull request #99
Opened 2024-09-20 13:31 UTC by MagdaDziadosz

2024-10-01 22:36 UTC, KoryKessel-Mirantis requested changes

2024-10-01 22:36 UTC, KoryKessel-Mirantis commented on content/docs/operations/backup-restore/external.md
> +## Create an external storage backup
```suggestion
## Create an external backup
```

2024-10-01 22:36 UTC, KoryKessel-Mirantis commented on content/docs/operations/backup-restore/external.md
> +from those backups.
Suggest deleting this sentence, as it offers nothing interesting, mentions restores when restores are not documented in this section, and because it has no counterpart in the In-Cluster section.

2024-10-01 22:36 UTC, KoryKessel-Mirantis commented on content/docs/operations/backup-restore/external.md
> +##  Restore from an external storage backup
```suggestion
##  Restore from an external backup
```

2024-10-01 22:36 UTC, KoryKessel-Mirantis commented on content/docs/operations/backup-restore/external.md
> +time of a backup creation.
```suggestion
A restore operation returns the Kubernetes cluster to the state it was in at the time the backup you select was created.
```

2024-10-01 22:36 UTC, KoryKessel-Mirantis commented on content/docs/operations/backup-restore/external.md
> +go to your AWS console and navigate to the **backups** section:
```suggestion
Using your AWS console, you can verify the presence of your backups and restores in the S3 bucket.
```

2024-10-01 22:36 UTC, KoryKessel-Mirantis commented on content/docs/operations/backup-restore/in-cluster.md
> +Optional. To view detailed logs of a backup, run:
```suggestion
To view detailed logs of a backup, run:
```

2024-10-01 22:36 UTC, KoryKessel-Mirantis commented on content/docs/operations/backup-restore/in-cluster.md
> +time of a backup creation.
```suggestion
A restore operation returns the Kubernetes cluster to the state it was in at the time the backup you select was created.
```

2024-10-01 22:36 UTC, KoryKessel-Mirantis commented on content/docs/operations/backup-restore/in-cluster.md
> +Optional. To view detailed logs, run:
```suggestion
To view detailed logs, run:
```

2024-10-02 23:01 UTC, KoryKessel-Mirantis commented
An FYI, @MagdaDziadosz. Due to PR102 you will need to rebase before working my comments.

2024-10-07 08:57 UTC, MagdaDziadosz commented on content/docs/operations/backup-restore/external.md
> +   for an MKE 4.
```suggestion
      AWS S3 is currently the only external backup storage supported by MKE 4.
```

2024-10-07 13:09 UTC, KoryKessel-Mirantis requested changes

2024-10-07 13:09 UTC, KoryKessel-Mirantis commented on content/docs/operations/backup-restore/_index.md
> +backup functionality works, even if the UI is disabled.
Edit to read:

"Set `enable_ui` to `true` to expose the MinIO Console through the Ingress and make it accessible through the UI. Core backup functionality works, even if the UI is disabled."

2024-10-07 13:09 UTC, KoryKessel-Mirantis commented on content/docs/operations/backup-restore/_index.md
>  `backup` fields:
```suggestion
Refer to the following list for detail on all the configuration file `backup` fields:
```

2024-10-07 13:09 UTC, KoryKessel-Mirantis commented on content/docs/operations/backup-restore/_index.md
> +: Name of the external storage provider. AWS is currently the only available option.
```suggestion
: Name of the external storage provider. Currently, AWS is the only available option.
```

2024-10-07 13:09 UTC, KoryKessel-Mirantis commented on content/docs/operations/backup-restore/external.md
> +title: Back up with an external storage provider
```suggestion
title: Back up using an external storage provider
```

2024-10-07 13:09 UTC, KoryKessel-Mirantis commented on content/docs/operations/backup-restore/external.md
> +6. Run the `apply` command:
```suggestion
6. Apply the configuration:
```

2024-10-07 19:25 UTC, tppolkow commented on content/docs/operations/backup-restore/_index.md
> +the UI is disabled.  Core backup functionality works, even if the UI is disabled.
`Core backup functionality works, even if the UI is disabled.` seems to be duplicated.

2024-10-07 19:25 UTC, tppolkow commented on content/docs/operations/backup-restore/_index.md
> +`storage_provider.in_cluster_options.exposed`
With the latest mkectl build `exposed` is removed, and should be replaced with `enable_ui` (which is true or false; default to true).

2024-10-07 19:25 UTC, tppolkow commented on content/docs/operations/backup-restore/in-cluster.md
> +To view detailed logs of a backup, run:
We will actually be disabling the `logs` command due to some technical issues we won't have time to fix before GA. I was going to create a new PR to remove it but if you can, feel free to remove it here ( both `backup logs` and `restore logs`).

Users can view the logs via the minio UI (in in-cluster case) or S3 (in External case) - so we could replace it with a sentence pointing the users there if they wish to see the detailed logs.

2024-10-08 17:53 UTC, tppolkow approved these changes
LGTM! Thanks for addressing the comments.

2024-10-10 22:13 UTC, KoryKessel-Mirantis approved these changes

2024-10-10 22:15 UTC, KoryKessel-Mirantis commented
@MagdaDziadosz, once you *Squash and merge*, please do a quick once-over of the published docs with your eagle eyes. :-)

2024-10-11 07:17 UTC, merged